function session = callSessionInit()
%CALLSESSIONINIT Initialize lightweight dPMR call aggregation state.
session = struct( ...
    'active', false, ...
    'src', '', ...
    'dst', '', ...
    'colorCode', [], ...
    'firstSample', [], ...
    'lastSample', [], ...
    'headerCount', 0, ...
    'voiceCount', 0, ...
    'cchCount', 0, ...
    'records', struct([]), ...
    'syncTypes', {{}}, ...
    'superframeParts', {{}}, ...
    'communicationModes', [], ...
    'versions', [], ...
    'commsFormats', [], ...
    'emergencyPriorities', []);
end
