function out = cchExtra(record)
%CCHEXTRA Convert CCH record to output struct.
if isempty(record)
    out = [];
    return;
end
out = struct( ...
    'frame_number', record.frame_number, ...
    'id_half', record.id_half, ...
    'communication_mode', record.communication_mode, ...
    'version', record.version, ...
    'comms_format', record.comms_format, ...
    'emergency_priority', record.emergency_priority, ...
    'reserved', record.reserved, ...
    'slow_data', record.slow_data, ...
    'crc_ok', record.crc_ok, ...
    'crc_value', record.crc_value, ...
    'crc_computed', record.crc_computed, ...
    'hamming_ok', record.hamming_ok, ...
    'hamming_blocks_ok', record.hamming_blocks_ok, ...
    'corrected_bits', record.corrected_bits);
end

