function cfg = config()
%CONFIG dPMR protocol defaults copied from Python DPMRConfig.
cfg = struct();
cfg.targetSampleRateHz = 48000.0;
cfg.symbolRateHz = 2400.0;
cfg.samplesPerSymbol = 20;
cfg.frontendCutoffHz = 3500.0;
cfg.frontendTaps = 151;
cfg.frontendMinSamples = 512;
cfg.frontendPsdNperseg = 4096;
cfg.nominalDeviationHz = 1050.0;
cfg.syncThreshold = 0.82;
cfg.syncMaxSymbolErrors = 0;
cfg.syncMinDistanceSamples = 1200;
cfg.syncDedupWindowSymbols = 3;
cfg.syncErrorPhaseMin = -12.0;
cfg.syncErrorPhaseMax = 12.0;
cfg.syncErrorPhaseSteps = 13;
cfg.spsSearchMin = 20.0;
cfg.spsSearchMax = 20.0;
cfg.spsSearchSteps = 1;
cfg.phaseSearchMin = -12.0;
cfg.phaseSearchMax = 12.0;
cfg.phaseSearchSteps = 25;
cfg.sampleWindows = 0;
cfg.decisionAmbiguousThreshold = 0.35;
cfg.frameSymbols = 384;
cfg.headerSyncCandidateLimit = 50;
cfg.headerSymbolCandidateLimit = 16;
cfg.voiceSyncCandidateLimit = 100;
cfg.voiceSymbolCandidateLimit = 8;
cfg.dedupFrameBucketSamples = 3840;
cfg.stableColorMinRepeats = 2;
cfg.streamDcTimeConstantSec = 0.25;
cfg.streamFrequencyEstimateSec = 1.0;
cfg.streamFlushPaddingSec = 0.010;
cfg.streamSeenKeyLimit = 512;
end
