function [idSession, pdu] = decodeSyncCandidate( ...
        idSession, y, candidate, cfg, varargin)
%DECODESYNCCANDIDATE Decode one complete dPMR FS1/FS2 candidate.
if nargin < 4 || isempty(cfg), cfg = dpmr.config(); end
p = inputParser;
p.addParameter('SampleOffset', 0);
p.parse(varargin{:});
c = dpmr.constants();
pdu = [];
switch char(candidate.sync_type)
    case 'FS1'
        symbolCandidates = dpmr.recoverFrameSymbolCandidates( ...
            y, candidate, 'TotalSymbols', c.frameSymbols, ...
            'PhaseSearch', symbolPhaseSearch(cfg), ...
            'SpsSearch', spsSearch(cfg), ...
            'SampleWindows', cfg.sampleWindows, ...
            'Limit', cfg.headerSymbolCandidateLimit, ...
            'DecisionAmbiguousThreshold', cfg.decisionAmbiguousThreshold);
        [best, timing] = bestHeader(symbolCandidates, c);
        if isempty(best), return; end
        extra = struct( ...
            'color_code', best.color_code, ...
            'sync_type', 'FS1', ...
            'polarity_inverted', candidate.polarity_inverted, ...
            'sync_ncc', candidate.ncc, ...
            'symbol_sps', timing.sps, ...
            'symbol_phase', timing.phase, ...
            'symbol_resid', timing.resid, ...
            'symbol_sample_window', timing.sample_window, ...
            'segment_timing', struct('header', timing), ...
            'fs_start', candidate.fs_start + p.Results.SampleOffset, ...
            'superframe_part', best.superframe_part, ...
            'quality', best.quality, ...
            'cch', cchList(best.cch_records), ...
            'cch_offsets', best.cch_offsets, ...
            'color_code_candidates', best.color_codes, ...
            'color_code_offsets', best.color_offsets, ...
            'frame_numbers', frameNumbers(best.cch_records));
        pdu = struct('protocol', 'dPMR', 'type', 'DPMR_HEADER', ...
            'src', best.src, 'dst', best.dst, 'ts', 0, ...
            'flco', 'HEADER', 'fid', '', 'extra', extra, ...
            'raw_bits', best.raw_bits);

    case 'FS2'
        symbolCandidates = dpmr.recoverFrameSymbolCandidates( ...
            y, candidate, 'TotalSymbols', c.voiceFs2TotalSymbols, ...
            'PhaseSearch', symbolPhaseSearch(cfg), ...
            'SpsSearch', spsSearch(cfg), ...
            'SampleWindows', cfg.sampleWindows, ...
            'Limit', cfg.voiceSymbolCandidateLimit, ...
            'DecisionAmbiguousThreshold', cfg.decisionAmbiguousThreshold);
        [best, timing] = bestVoice(symbolCandidates);
        if isempty(best), return; end
        quality = best.quality;
        quality.timing_coherent = true;
        quality.front_end_confidence = quality.confidence;
        [idSession, src, dst, superframePart] = ...
            dpmr.sessionFeed(idSession, best.cch0, best.cch1);
        exposeIds = strcmp(quality.confidence, 'high') && ...
            any(strcmp(superframePart, {'src', 'dst'}));
        if ~exposeIds, src = ''; dst = ''; end
        records = appendRecords(best.cch0, best.cch1);
        extra = struct( ...
            'color_code', best.color_code, ...
            'sync_type', 'FS2', ...
            'polarity_inverted', candidate.polarity_inverted, ...
            'sync_ncc', candidate.ncc, ...
            'symbol_sps', timing.sps, ...
            'symbol_phase', timing.phase, ...
            'symbol_resid', timing.resid, ...
            'symbol_sample_window', timing.sample_window, ...
            'segment_timing', struct( ...
                'cch0', timing, 'cc', timing, 'cch1', timing), ...
            'fs_start', candidate.fs_start + p.Results.SampleOffset, ...
            'superframe_part', superframePart, ...
            'quality', quality, ...
            'cch', cchList(records), ...
            'frame_numbers', frameNumbers(records));
        pdu = struct('protocol', 'dPMR', 'type', 'DPMR_VOICE', ...
            'src', src, 'dst', dst, 'ts', 0, 'flco', 'VOICE', ...
            'fid', '', 'extra', extra, 'raw_bits', best.raw_bits);
end
if ~isempty(pdu), pdu = radio.normalizePdus(pdu); end
end

function [best, timing] = bestHeader(items, c)
best = [];
timing = [];
bestScore = -inf;
bestTie = -inf;
for k = 1:numel(items)
    payload = items(k).symbols(numel(c.fs1Symbols)+1:end);
    decoded = dpmr.decodeHeaderPayload(payload);
    if isempty(decoded), continue; end
    score = headerScore(decoded, items(k).resid);
    tie = -items(k).resid;
    if score > bestScore || (score == bestScore && tie > bestTie)
        bestScore = score;
        bestTie = tie;
        best = decoded;
        timing = timingStruct(items(k));
    end
end
end

function [best, timing] = bestVoice(items)
best = [];
timing = [];
bestScore = -inf;
for k = 1:numel(items)
    decoded = dpmr.decodeVoiceSymbols(items(k).symbols);
    if isempty(decoded), continue; end
    score = voiceScore(decoded, items(k).resid);
    if score > bestScore
        bestScore = score;
        best = decoded;
        timing = timingStruct(items(k));
    end
end
end

function score = voiceScore(decoded, resid)
records = appendRecords(decoded.cch0, decoded.cch1);
score = 2 * double(decoded.color_code >= 0);
frames = [];
for k = 1:numel(records)
    score = score + 5 * double(records(k).crc_ok) + ...
        2 * double(records(k).hamming_ok);
    frames(end+1) = records(k).frame_number; %#ok<AGROW>
end
if all(ismember([0 1], frames)) || all(ismember([2 3], frames))
    score = score + 3;
end
score = score - 0.2 * resid;
end

function score = headerScore(decoded, resid)
score = 0;
frames = [];
for k = 1:numel(decoded.cch_records)
    record = decoded.cch_records(k);
    score = score + 8 * double(record.crc_ok) + ...
        2 * double(record.hamming_ok);
    if dpmr.cchUsable(record)
        frames(end+1) = record.frame_number; %#ok<AGROW>
    end
end
score = score + 2 * double(~isempty(decoded.color_codes));
if all(ismember([0 1], frames)) || all(ismember([2 3], frames))
    score = score + 3;
end
score = score - 0.2 * resid;
end

function timing = timingStruct(item)
timing = struct('sps', item.sps, 'phase', item.phase, ...
    'resid', item.resid, 'sample_window', item.sample_window, ...
    'decision_error_p90', item.decision_error_p90, ...
    'ambiguous_symbols', item.ambiguous_symbols);
end

function values = symbolPhaseSearch(cfg)
values = linspace(cfg.phaseSearchMin, ...
    cfg.phaseSearchMax, cfg.phaseSearchSteps);
end

function values = spsSearch(cfg)
values = linspace(cfg.spsSearchMin, cfg.spsSearchMax, cfg.spsSearchSteps);
end

function records = appendRecords(first, second)
records = struct([]);
if ~isempty(first), records = first; end
if ~isempty(second)
    if isempty(records), records = second; else, records(end+1) = second; end
end
end

function list = cchList(records)
list = struct([]);
for k = 1:numel(records)
    item = dpmr.cchExtra(records(k));
    if isempty(list), list = item; else, list(end+1) = item; end
end
end

function values = frameNumbers(records)
if isempty(records), values = []; else, values = [records.frame_number]; end
end
