function report = frameDecoderReport(state)
%FRAMEDECODERREPORT Summarize persistent dPMR frame state.
report = struct( ...
    'candidateCount', double(state.candidateCount), ...
    'decodedPduCount', double(state.decodedPduCount), ...
    'crcValidPduCount', double(state.crcValidPduCount), ...
    'seenKeyCount', numel(state.seenKeys), ...
    'callSessionActive', logical(state.callSession.active), ...
    'finalized', logical(state.finalized));
end
