function state = frameDecoderInit(cfg)
%FRAMEDECODERINIT Initialize persistent dPMR frame/session state.
if nargin < 1 || isempty(cfg), cfg = dpmr.config(); end
state = struct( ...
    'cfg', cfg, ...
    'idSession', dpmr.sessionInit(), ...
    'callSession', dpmr.callSessionInit(), ...
    'seenKeys', {cell(0, 1)}, ...
    'candidateCount', uint64(0), ...
    'decodedPduCount', uint64(0), ...
    'crcValidPduCount', uint64(0), ...
    'finalized', false);
end
