function spec = spec()
%SPEC dPMR ProtocolSpec-compatible adapter.
spec = struct( ...
    'name', 'dPMR', ...
    'aliases', {{'dpmr'}}, ...
    'config', dpmr.config(), ...
    'frontendFcn', @dpmr.frontend, ...
    'decodeFcn', @dpmr.decode, ...
    'postprocessFcn', @dpmr.postprocess, ...
    'dedupFcn', @dpmr.dedupKey, ...
    'formatterFcn', @dpmr.formatPdu, ...
    'targetSampleRateHz', 48000.0, ...
    'scanIqFcn', []);
end
