function spec = spec()
%SPEC dPMR ProtocolSpec-compatible adapter.
spec = struct( ...
    'name', 'dPMR', ...
    'aliases', {{'dpmr'}}, ...
    'config', dpmr.config(), ...
    'frontendKey', 'dpmr_4fsk', ...
    'frontendFcn', @dpmr.frontend, ...
    'decodeFcn', @dpmr.decode, ...
    'postprocessFcn', @dpmr.postprocess, ...
    'dedupFcn', @dpmr.dedupKey, ...
    'formatterFcn', @dpmr.formatPdu, ...
    'scanMode', 'narrowband_4fsk', ...
    'targetSampleRateHz', 48000.0, ...
    'scanIqFcn', [], ...
    'supportsBlindSearch', true, ...
    'supportsFrequencyOffsets', true, ...
    'defaultBasebandScan', true, ...
    'defaultFreqListScan', true, ...
    'defaultBlindSearch', true);
end
