function [state, output] = streamFlush(state)
%STREAMFLUSH Drain causal frontend latency and finalize dPMR call state.
if state.finalized
    output = emptyOutput(state);
    return;
end
if isempty(state.sourceOriginSample)
    state.finalized = true;
    output = emptyOutput(state);
    return;
end
paddingCount = max(1, ceil((state.cfg.streamFlushPaddingSec + ...
    state.rateConverterDelaySec) * state.inputSampleRateHz));
padding = radio.stream.makeIqChunk( ...
    complex(zeros(paddingCount, 1)), state.inputSampleRateHz, ...
    state.expectedSourceSample, 'SequenceNumber', state.feedCount);
[state, drained] = dpmr.streamDecodeChunk(state, padding);
[state.frameState, finalPdus] = ...
    dpmr.frameDecoderFinalize(state.frameState);
finalSamples = pduSourceSamples(state, finalPdus);
pdus = appendPdus(drained.pdus, finalPdus);
sourceSamples = [drained.sourceSamples; finalSamples];
state.finalized = true;
output = struct( ...
    'pdus', radio.normalizePdus(pdus), ...
    'sourceSamples', sourceSamples, ...
    'diagnostics', dpmr.frameDecoderReport(state.frameState), ...
    'frequencyOffsetHz', drained.frequencyOffsetHz, ...
    'timingState', drained.timingState, ...
    'nativeStreaming', true, ...
    'inputSampleCount', paddingCount, ...
    'resampledSampleCount', drained.resampledSampleCount, ...
    'demodulatedSampleCount', drained.demodulatedSampleCount, ...
    'elapsedSec', drained.elapsedSec);
end

function output = emptyOutput(state)
output = struct('pdus', struct([]), ...
    'sourceSamples', zeros(0, 1, 'uint64'), ...
    'diagnostics', dpmr.frameDecoderReport(state.frameState), ...
    'frequencyOffsetHz', state.coarseFrequencyOffsetHz, ...
    'timingState', struct(), 'nativeStreaming', true, ...
    'inputSampleCount', 0, 'resampledSampleCount', 0, ...
    'demodulatedSampleCount', 0, 'elapsedSec', 0);
end

function samples = pduSourceSamples(state, pdus)
samples = zeros(numel(pdus), 1, 'uint64');
for k = 1:numel(pdus)
    targetSample = radio.getNestedField(pdus(k), 'extra.fs_start', []);
    if isempty(targetSample)
        targetSample = radio.getNestedField(pdus(k), 'extra.end_sample', []);
    end
    if isempty(targetSample)
        targetSample = radio.getNestedField(pdus(k), 'extra.start_sample', 0);
    end
    inputOffset = round(max(0, double(targetSample)) * ...
        state.inputSampleRateHz / state.targetSampleRateHz);
    samples(k) = state.sourceOriginSample + uint64(max(0, inputOffset));
end
end

function value = appendPdus(value, items)
if isempty(items), return; end
if isempty(value), value = items; else, value(end+1:end+numel(items)) = items; end
end
