%% Unified DMR/P25/dPMR/NXDN/TETRA scanner entry
% Edit the configuration block, then click Run in MATLAB.

TARGET_FILE = '/home/lzkj/lzkj_workspace/DMR_signal/1.bvsp';

% 'serial' keeps the compatibility scanner. 'parallel' races all requested
% protocols on one already-centered baseband channel, then fully decodes the
% winner. 'tuned-parallel' first extracts one known carrier from wideband IQ,
% then enters the same protocol race. 'wideband' performs streaming PFB
% discovery before starting one protocol race per active carrier.
EXECUTION_MODE = 'parallel';

% RF center represented by complex baseband. Set the actual SDR tuning
% frequency for raw wideband input. BVSP input reads this value from its
% header. Zero keeps reported values as offsets for headerless recordings.
WIDEBAND_CENTER_FREQUENCY_HZ = 0;

% Use {} for scan-mode defaults, or: {'dmr'}, {'p25'}, {'dpmr'}, {'nxdn'}, {'tetra'}.
% Parallel mode with {} races all five protocols. Serial defaults retain the
% existing resolver behavior; use {'tetra'} explicitly for centered TETRA.
PROTOCOLS = {};

% Leave SAMPLE_RATE empty to infer it from names like dmr_1_78125.rawiq.
SAMPLE_RATE = [];

% Use [] for centered baseband. Tuned-parallel currently accepts exactly one
% relative carrier offset, for example 1235200 for a carrier 1.2352 MHz above
% the capture center.
FREQ_LIST = [1235200,];

% Set true for wideband/multi-channel IQ when the signal offset is unknown.
BLIND_SEARCH = false;

% Show diagnostic figure with IQ, PSD, frontend output, and decoded PDU text.
SHOW_FIGURE = false;

% Set false to keep repeated frames for debugging and golden comparison.
DEDUPLICATE = true;

% Use the native MATLAB backend. Set either value to 'python' for fallback.
PIPELINE_BACKEND = 'matlab';     % 'matlab' or 'python'
DECODER_BACKEND = 'matlab';      % 'matlab' or 'python'
IQ_DTYPE = 'int16';

%% Run
projectRoot = fileparts(mfilename('fullpath'));
addpath(projectRoot);
startup;

isTunedParallel = any(strcmpi(EXECUTION_MODE, ...
    {'tuned-parallel', 'known-frequency', 'known-carrier'})) || ...
    (strcmpi(EXECUTION_MODE, 'parallel') && ~isempty(FREQ_LIST) && ...
    any(FREQ_LIST(:) ~= 0));
if strcmpi(EXECUTION_MODE, 'wideband') || ...
        strcmpi(EXECUTION_MODE, 'wideband-streaming')
    [widebandPdus, widebandReport] = radio.scanFile(TARGET_FILE, ...
        'ProtocolNames', PROTOCOLS, ...
        'SampleRate', SAMPLE_RATE, ...
        'IqDType', IQ_DTYPE, ...
        'FreqList', FREQ_LIST, ...
        'PipelineBackend', PIPELINE_BACKEND, ...
        'ExecutionMode', 'wideband', ...
        'CenterFrequencyHz', WIDEBAND_CENTER_FREQUENCY_HZ, ...
        'ShowProgress', true);
    result = struct( ...
        'pdus', widebandPdus, ...
        'scanReport', widebandReport, ...
        'sampleRate', widebandReport.sampleRateHz, ...
        'lines', {radio.formatLines(widebandPdus)});
    if SHOW_FIGURE
        warning('scanner:WidebandFigure', ...
            ['Wideband streaming intentionally avoids loading the complete ', ...
            'file; the whole-file diagnostic figure is disabled.']);
    end
elseif isTunedParallel
    [tunedPdus, tunedReport] = radio.scanFile(TARGET_FILE, ...
        'ProtocolNames', PROTOCOLS, ...
        'SampleRate', SAMPLE_RATE, ...
        'IqDType', IQ_DTYPE, ...
        'FreqList', FREQ_LIST, ...
        'BlindSearch', false, ...
        'PipelineBackend', PIPELINE_BACKEND, ...
        'DecoderBackend', DECODER_BACKEND, ...
        'Deduplicate', DEDUPLICATE, ...
        'ExecutionMode', 'tuned-parallel', ...
        'CenterFrequencyHz', WIDEBAND_CENTER_FREQUENCY_HZ, ...
        'ShowProgress', true);
    result = struct( ...
        'pdus', tunedPdus, ...
        'scanReport', tunedReport, ...
        'sampleRate', tunedReport.basebandSampleRateHz, ...
        'lines', {radio.formatLines(tunedPdus)});
    if SHOW_FIGURE
        warning('scanner:TunedFigure', ...
            ['Tuned streaming avoids loading the complete wideband file; ', ...
             'the whole-file diagnostic figure is disabled.']);
    end
else
    result = viz.analyzeFile(TARGET_FILE, ...
        'ProtocolNames', PROTOCOLS, ...
        'SampleRate', SAMPLE_RATE, ...
        'IqDType', IQ_DTYPE, ...
        'FreqList', FREQ_LIST, ...
        'BlindSearch', BLIND_SEARCH, ...
        'PipelineBackend', PIPELINE_BACKEND, ...
        'DecoderBackend', DECODER_BACKEND, ...
        'Deduplicate', DEDUPLICATE, ...
        'ShowProgress', true, ...
        'ExecutionMode', EXECUTION_MODE, ...
        'CreateFigure', SHOW_FIGURE);
end

pdus = result.pdus;
fprintf('\n=== %s ===\n', TARGET_FILE);
fprintf('Sample rate: %.0f Hz\n', result.sampleRate);
fprintf('Decoded PDUs: %d\n', numel(pdus));
if strcmpi(EXECUTION_MODE, 'wideband') || ...
        strcmpi(EXECUTION_MODE, 'wideband-streaming')
    fprintf('Wideband outcome: %s\n', result.scanReport.outcome);
    fprintf('Candidate tracks: %d (activated: %d)\n', ...
        result.scanReport.candidateTrackCount, ...
        result.scanReport.activatedTrackCount);
    fprintf('RF Epochs: %d (confirmed: %d)\n', ...
        result.scanReport.epochCount, ...
        result.scanReport.confirmedEpochCount);
    fprintf('Processing real-time factor: %.3f\n', ...
        result.scanReport.realTimeFactor);
    for frequencyHz = result.scanReport.detectedFrequenciesHz
        fprintf('  Detected RF frequency: %.3f MHz\n', frequencyHz / 1e6);
    end
elseif isTunedParallel
    fprintf('Tuned-parallel outcome: %s\n', result.scanReport.outcome);
    fprintf('Input rate: %.3f MHz; baseband rate: %.0f Hz\n', ...
        result.scanReport.inputSampleRateHz / 1e6, ...
        result.scanReport.basebandSampleRateHz);
    fprintf('Capture center: %.6f MHz\n', ...
        result.scanReport.inputCenterFrequencyHz / 1e6);
    fprintf('Selected carrier: %.6f MHz (offset %+.3f kHz)\n', ...
        result.scanReport.targetFrequencyHz / 1e6, ...
        result.scanReport.frequencyOffsetHz / 1e3);
    if ~isempty(result.scanReport.selectedProtocol)
        fprintf('Selected protocol: %s\n', ...
            result.scanReport.selectedProtocol);
    end
    fprintf('DDC factor: %d; total real-time factor: %.3f\n', ...
        result.scanReport.extraction.decimationFactor, ...
        result.scanReport.realTimeFactor);
    fprintf('RF Epochs: %d (confirmed: %d)\n', ...
        result.scanReport.epochCount, ...
        result.scanReport.confirmedEpochCount);
elseif strcmpi(EXECUTION_MODE, 'parallel')
    fprintf('Parallel outcome: %s\n', result.scanReport.outcome);
    if ~isempty(result.scanReport.selectedProtocol)
        fprintf('Selected protocol: %s\n', result.scanReport.selectedProtocol);
    end
    fprintf('Protocol race mode: %s\n', result.scanReport.executionMode);
    fprintf('Classification time: %.3f s\n', ...
        result.scanReport.classificationElapsedSec);
    fprintf('RF Epochs: %d (confirmed: %d)\n', ...
        result.scanReport.epochCount, ...
        result.scanReport.confirmedEpochCount);
    for epochIndex = 1:result.scanReport.epochCount
        epoch = result.scanReport.epochs(epochIndex);
        fprintf(['  Epoch %d: %.3f-%.3f s  protocol=%s  ', ...
            'outcome=%s  pdus=%d  close=%s\n'], ...
            epoch.epochId, ...
            double(epoch.candidateStartSample) / result.sampleRate, ...
            double(epoch.endSample) / result.sampleRate, ...
            valueOr(epoch.protocol, '-'), epoch.outcome, ...
            epoch.pduCount, epoch.closeReason);
    end
end
for k = 1:numel(result.lines)
    fprintf('%s\n', result.lines{k});
end

function value = valueOr(value, fallback)
if isempty(value), value = fallback; end
end
