function ddcActorWorker(spec, outputQueue, actorId)
%DDCACTORWORKER Own DDC state and consume the shared IQ ring in order.
ringReader = [];
ringAttached = false;
ringMaxOutputQueueChunks = inf;
ringLastProgressToken = tic;
ringConsumedSampleEnd = uint64(0);
try
    state = radio.tuned.multiDdcInit( ...
        spec.inputSampleRateHz, spec.frequencyOffsetsHz, ...
        'Config', spec.config, ...
        'InputCenterFrequencyHz', spec.inputCenterFrequencyHz, ...
        'Capacity', spec.capacity, ...
        'Prewarm', logical(spec.prewarm));
    inputQueue = parallel.pool.PollableDataQueue;
    send(outputQueue, struct('type', 'ready', ...
        'actorId', uint64(actorId), 'inputQueue', inputQueue));
    while true
        didWork = false;
        message = poll(inputQueue, 0);
        while ~isempty(message)
            if isstruct(message) && isfield(message, 'type') && ...
                    message.actorId == actorId
                switch char(message.type)
                    case 'stop'
                        send(outputQueue, struct( ...
                            'type', 'stopped', ...
                            'actorId', uint64(actorId)));
                        return;
                    case 'retarget'
                        state = radio.tuned.multiDdcRetarget( ...
                            state, message.frequencyOffsetsHz, ...
                            'InputCenterFrequencyHz', ...
                                message.inputCenterFrequencyHz);
                    case 'reset'
                        ringAttached = false;
                        ringReader = [];
                        ringConsumedSampleEnd = uint64(0);
                        state = radio.tuned.multiDdcReset(state);
                        send(outputQueue, struct( ...
                            'type', 'reset', ...
                            'actorId', uint64(actorId)));
                    case 'attach_ring'
                        if ringAttached
                            error('radio:live:ddcActorWorker:RingAttached', ...
                                'The DDC actor already has a ring input.');
                        end
                        ringReader = radio.live.sharedIqRingReader( ...
                            message.descriptor, message.startSequence);
                        ringAttached = true;
                        ringMaxOutputQueueChunks = ...
                            double(message.maxOutputQueueChunks);
                        ringConsumedSampleEnd = ...
                            uint64(message.startSourceSample);
                        ringLastProgressToken = tic;
                        send(outputQueue, ringProgressMessage( ...
                            'ring_attached', ringReader, actorId, ...
                            ringConsumedSampleEnd));
                end
                didWork = true;
            end
            message = poll(inputQueue, 0);
        end

        if ringAttached
            processed = 0;
            while processed < 8 && ...
                    outputQueue.QueueLength < ringMaxOutputQueueChunks
                [ringReader, chunk, ringStatus] = ...
                    radio.live.sharedIqRingRead(ringReader);
                if ~isempty(chunk)
                    [state, reply] = processRingChunk( ...
                        state, chunk, ringStatus, actorId);
                    ringConsumedSampleEnd = uint64(chunk.sourceSampleEnd);
                    reply.ringConsumedSampleEnd = ringConsumedSampleEnd;
                    send(outputQueue, reply);
                    processed = processed + 1;
                    didWork = true;
                    continue;
                end
                switch char(ringStatus.state)
                    case 'overrun'
                        error('radio:live:ddcActorWorker:RingOverrun', ...
                            ['Shared IQ ring overrun before sequence %d ', ...
                             '(writer=%d, lost=%d chunks).'], ...
                            ringStatus.sequence, ...
                            ringStatus.writeSequence, ...
                            ringStatus.lostChunks);
                    case 'drained'
                        [state, reply] = flushState( ...
                            state, actorId, ringReader.nextSequence);
                        reply.ringSequence = ...
                            ringReader.nextSequence - uint64(1);
                        reply.ringWriteSequence = ...
                            ringStatus.writeSequence;
                        reply.ringSourceSampleEnd = ...
                            ringStatus.sourceSampleEnd;
                        reply.ringConsumedSampleEnd = ...
                            ringConsumedSampleEnd;
                        send(outputQueue, reply);
                        ringAttached = false;
                        didWork = true;
                    otherwise
                        if toc(ringLastProgressToken) >= 0.05
                            send(outputQueue, ringProgressMessage( ...
                                'ring_progress', ringReader, actorId, ...
                                ringConsumedSampleEnd));
                            ringLastProgressToken = tic;
                        end
                end
                break;
            end
        end
        if ~didWork, pause(0.001); end
    end
catch ME
    send(outputQueue, struct('type', 'error', ...
        'actorId', uint64(actorId), ...
        'errorReason', sprintf('%s: %s', ME.identifier, ME.message)));
end
end

function [state, reply] = processRingChunk( ...
        state, chunk, ringStatus, actorId)
inputCount = uint64(numel(chunk.iq));
token = tic;
[state, basebandChunks] = radio.tuned.multiDdcFeed(state, chunk);
elapsedSec = toc(token);
descriptor = chunk;
descriptor.iq = complex(zeros(0, 1, 'single'));
descriptor.transportSampleCount = inputCount;
reply = basebandMessage(actorId, ringStatus.sequence, descriptor, ...
    basebandChunks, inputCount, elapsedSec);
reply.ringSequence = ringStatus.sequence;
reply.ringWriteSequence = ringStatus.writeSequence;
reply.ringSourceSampleEnd = ringStatus.sourceSampleEnd;
end

function reply = basebandMessage(actorId, requestId, descriptor, ...
        basebandChunks, inputCount, elapsedSec)
basebandChunks = singleChunks(basebandChunks);
reply = struct( ...
    'type', 'baseband', ...
    'actorId', uint64(actorId), ...
    'requestId', uint64(requestId), ...
    'widebandDescriptor', descriptor, ...
    'basebandChunks', {basebandChunks}, ...
    'inputSampleCount', uint64(inputCount), ...
    'computeSec', elapsedSec);
end

function [state, reply] = flushState(state, actorId, requestId)
token = tic;
[state, basebandChunks] = radio.tuned.multiDdcFlush(state);
elapsedSec = toc(token);
basebandChunks = singleChunks(basebandChunks);
sourceSample = uint64(0);
if ~isempty(state.expectedInputSample)
    sourceSample = uint64(state.expectedInputSample);
end
marker = radio.stream.makeIqChunk( ...
    complex(zeros(0, 1, 'single')), ...
    state.inputSampleRateHz, sourceSample, ...
    'CenterFrequencyHz', state.inputCenterFrequencyHz);
marker.transportSampleCount = uint64(0);
reply = struct( ...
    'type', 'flushed', ...
    'actorId', uint64(actorId), ...
    'requestId', uint64(requestId), ...
    'widebandDescriptor', marker, ...
    'basebandChunks', {basebandChunks}, ...
    'computeSec', elapsedSec, ...
    'ringDrained', true);
end

function message = ringProgressMessage( ...
        type, reader, actorId, consumedSampleEnd)
mapping = reader.mapping;
message = struct( ...
    'type', type, ...
    'actorId', uint64(actorId), ...
    'readSequence', reader.nextSequence - uint64(1), ...
    'writeSequence', uint64(mapping.Data.writeSequence), ...
    'sourceSampleEnd', uint64(mapping.Data.sourceSampleEnd), ...
    'consumedSampleEnd', uint64(consumedSampleEnd));
end

function chunks = singleChunks(chunks)
for k = 1:numel(chunks)
    if isempty(chunks{k}), continue; end
    chunks{k}.iq = single(chunks{k}.iq);
end
end
