function actor = ddcActorStart(pool, ddcState, varargin)
%DDCACTORSTART Start one ordered, persistent matrix-DDC worker.
p = inputParser;
p.addParameter('MaxQueueSec', 2.0);
p.parse(varargin{:});
if isempty(pool) || isa(pool, 'parallel.ThreadPool')
    error('radio:live:ddcActorStart:Pool', ...
        'The live DDC actor requires a process pool.');
end
persistent nextActorId
if isempty(nextActorId), nextActorId = uint64(1); end
actorId = nextActorId;
nextActorId = nextActorId + uint64(1);
outputQueue = parallel.pool.PollableDataQueue;
future = parfeval(pool, @radio.live.ddcActorWorker, 0, ...
    ddcState, outputQueue, actorId);
inputSampleRateHz = double(ddcState.inputSampleRateHz);
initialConfigured = true;
if isfield(ddcState, 'initialConfigured')
    initialConfigured = logical(ddcState.initialConfigured);
end
actor = struct( ...
    'actorId', actorId, ...
    'future', future, ...
    'outputQueue', outputQueue, ...
    'inputQueue', [], ...
    'ready', false, ...
    'configured', initialConfigured, ...
    'retargetPending', false, ...
    'resetPending', false, ...
    'stopped', false, ...
    'failed', false, ...
    'flushRequested', false, ...
    'flushed', false, ...
    'nextRequestId', uint64(1), ...
    'pendingMessages', {cell(0, 1)}, ...
    'pendingInputSamples', uint64(0), ...
    'maxPendingInputSamples', uint64(0), ...
    'processedInputSamples', uint64(0), ...
    'ringAttached', false, ...
    'ringDrained', false, ...
    'ringStartSequence', uint64(0), ...
    'ringReadSequence', uint64(0), ...
    'ringWriteSequence', uint64(0), ...
    'ringSourceSampleEnd', uint64(0), ...
    'ringConsumedSampleEnd', uint64(0), ...
    'ringOverrunCount', uint64(0), ...
    'inputSampleRateHz', inputSampleRateHz, ...
    'maxQueueSec', double(p.Results.MaxQueueSec), ...
    'computeCount', uint64(0), ...
    'totalComputeSec', 0, ...
    'maxComputeSec', 0, ...
    'errorReason', '');
end
