function actor = ddcActorAttachRing( ...
        actor, descriptor, startSequence, startSourceSample)
%DDCACTORATTACHRING Let the DDC process consume IQ without a UI relay.
if isempty(actor) || actor.stopped || actor.failed
    error('radio:live:ddcActorAttachRing:Unavailable', ...
        'The prewarmed DDC actor is not ready for ring attachment.');
end
if actor.processedInputSamples ~= 0 || actor.ringAttached
    error('radio:live:ddcActorAttachRing:Started', ...
        'A DDC actor can attach to only one live input epoch.');
end
validateattributes(startSequence, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'});
validateattributes(startSourceSample, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'nonnegative'});
message = struct( ...
    'type', 'attach_ring', ...
    'actorId', actor.actorId, ...
    'descriptor', descriptor, ...
    'startSequence', uint64(startSequence), ...
    'startSourceSample', uint64(startSourceSample), ...
    'maxOutputQueueChunks', max(2, ceil( ...
        actor.maxQueueSec * descriptor.sampleRateHz / ...
        double(descriptor.chunkSamples))));
if actor.ready
    send(actor.inputQueue, message);
else
    actor.pendingMessages{end+1, 1} = message;
end
actor.ringAttached = true;
actor.ringDrained = false;
actor.ringStartSequence = uint64(startSequence);
actor.ringReadSequence = uint64(startSequence) - uint64(1);
actor.ringWriteSequence = uint64(startSequence) - uint64(1);
actor.ringSourceSampleEnd = uint64(startSourceSample);
actor.ringConsumedSampleEnd = uint64(startSourceSample);
actor.pendingInputSamples = uint64(0);
actor.maxPendingInputSamples = uint64(0);
actor.flushed = false;
actor.flushRequested = false;
end
