function actor = fileProducerStart(config)
%FILEPRODUCERSTART Start a paced, background file-IQ producer.
required = {'path', 'sampleRateHz', 'centerFrequencyHz', 'iqDType', ...
    'headerBytes', 'chunkDurationSec', 'replayMode', 'maxLoops', ...
    'epochSilenceSec', 'playoutDelaySec', 'sharedRing'};
missing = required(~isfield(config, required));
if ~isempty(missing)
    error('radio:live:fileProducerStart:Config', ...
        'Producer config is missing field: %s', missing{1});
end
persistent nextActorId
if isempty(nextActorId), nextActorId = uint64(1); end
actorId = nextActorId;
nextActorId = nextActorId + uint64(1);
outputQueue = parallel.pool.PollableDataQueue;
future = parfeval(backgroundPool, @radio.live.fileProducerWorker, 0, ...
    config, outputQueue, actorId);
actor = struct( ...
    'actorId', actorId, ...
    'future', future, ...
    'outputQueue', outputQueue, ...
    'inputQueue', [], ...
    'ready', false, ...
    'stopped', false, ...
    'failed', false, ...
    'terminal', false, ...
    'spectrumDroppedChunks', uint64(0), ...
    'pendingCommands', {cell(0, 1)}, ...
    'productionLagSec', 0, ...
    'errorReason', '');
end
