function actor = fileProducerAttachSpectrum(actor, spectrumActor)
%FILEPRODUCERATTACHSPECTRUM Direct future IQ to the PSD consumer queue.
if isempty(spectrumActor) || ~spectrumActor.ready || ...
        isempty(spectrumActor.inputQueue)
    error('radio:live:fileProducerAttachSpectrum:NotReady', ...
        'The spectrum actor must be ready before direct attachment.');
end
message = struct( ...
    'type', 'attach_spectrum', ...
    'sinkQueue', spectrumActor.inputQueue, ...
    'sinkActorId', spectrumActor.actorId, ...
    'maxQueueChunks', spectrumActor.maxQueueChunks);
actor = radio.live.fileProducerSendCommand(actor, message);
end
