function actor = fileProducerStart(config)
%FILEPRODUCERSTART Start a paced, background file-IQ producer.
required = {'path', 'sampleRateHz', 'centerFrequencyHz', 'iqDType', ...
    'headerBytes', 'chunkDurationSec', 'replayMode', 'maxLoops', ...
    'epochSilenceSec', 'playoutDelaySec', 'maxQueueChunks'};
missing = required(~isfield(config, required));
if ~isempty(missing)
    error('radio:live:fileProducerStart:Config', ...
        'Producer config is missing field: %s', missing{1});
end
persistent nextActorId
if isempty(nextActorId), nextActorId = uint64(1); end
actorId = nextActorId;
nextActorId = nextActorId + uint64(1);
outputQueue = parallel.pool.PollableDataQueue;
future = parfeval(backgroundPool, @radio.live.fileProducerWorker, 0, ...
    config, outputQueue, actorId);
actor = struct( ...
    'actorId', actorId, ...
    'future', future, ...
    'outputQueue', outputQueue, ...
    'inputQueue', [], ...
    'ready', false, ...
    'stopped', false, ...
    'failed', false, ...
    'terminal', false, ...
    'directFanout', logical(fieldOr(config, 'directFanout', false)), ...
    'spectrumAttached', false, ...
    'decoderArmed', false, ...
    'sharedRingEnabled', isfield(config, 'sharedRing') && ...
        ~isempty(config.sharedRing), ...
    'sharedRing', fieldOr(config, 'sharedRing', []), ...
    'ringWriteSequence', uint64(0), ...
    'spectrumDroppedChunks', uint64(0), ...
    'pendingCommands', {cell(0, 1)}, ...
    'globalNextSample', uint64(0), ...
    'completedLoops', uint64(0), ...
    'productionLagSec', 0, ...
    'maxProductionLagSec', 0, ...
    'errorReason', '', ...
    'startToken', tic);
end

function value = fieldOr(s, name, fallback)
if isfield(s, name), value = s.(name); else, value = fallback; end
end
