function [session, message] = parallelSessionAttach(session, offsetsHz)
%PARALLELSESSIONATTACH Attach fused DDC and scanners at the current live edge.
if isempty(session) || session.closed || session.source.terminal
    error('radio:live:parallelSessionAttach:Source', ...
        'A live preview source is required before starting decode.');
end
if decoderActive(session)
    error('radio:live:parallelSessionAttach:Active', ...
        'Clear the active decoder before starting another decode.');
end
offsetsHz = double(offsetsHz(:));
validateattributes(offsetsHz, {'numeric'}, ...
    {'vector','real','finite','nonempty'});
if numel(offsetsHz) > session.config.maxCarrierPaths
    error('radio:live:parallelSessionAttach:CarrierCount', ...
        'At most %d carrier paths are supported.', ...
        session.config.maxCarrierPaths);
end
if numel(unique(offsetsHz)) ~= numel(offsetsHz)
    error('radio:live:parallelSessionAttach:DuplicateCarrier', ...
        'Selected carrier offsets must be unique.');
end

ringSnapshot = radio.live.sharedIqRingSnapshot(session.ring);
session.decode.requestedSample = ringSnapshot.sourceSampleEnd;
session.decode.readySample = ringSnapshot.sourceSampleEnd;
session.decode.offsetsHz = offsetsHz;
session.decode.resultQueue = cell(0, 1);
session.decode.resultHead = 1;
session.decode.resultSamples = uint64(0);
session.pdus = struct([]);

session.actors.ddc = radio.live.ddcActorRetarget( ...
    session.actors.ddc, offsetsHz, ...
    session.metadata.centerFrequencyHz);
session.actors.ddc = radio.live.ddcActorAttachRing( ...
    session.actors.ddc, session.ring, ringSnapshot.nextSequence, ...
    ringSnapshot.sourceSampleEnd);

hooks = session.config.testHooks;
runtime = session.config.runtime;
scanner = radio.tuned.multiStreamScannerInit( ...
    session.metadata.sampleRateHz, offsetsHz, ...
    'InputCenterFrequencyHz', session.metadata.centerFrequencyHz, ...
    'Config', session.tunedConfig, ...
    'StreamConfig', session.config.streamConfig, ...
    'ProtocolNames', session.config.protocolNames, ...
    'NumWorkers', session.config.numWorkers, ...
    'TaskFcn', hooks.taskFcn, ...
    'TaskContext', hooks.taskContext, ...
    'LockedDecodeFcn', hooks.lockedDecodeFcn, ...
    'Deduplicate', session.config.deduplicate, ...
    'PrewarmDdc', false, ...
    'WarmParallelPool', false, ...
    'ProbeMaxInFlightPerChannel', ...
        runtime.probeMaxInFlightPerChannel, ...
    'EarlyProbeConfirm', runtime.earlyProbeConfirm, ...
    'EarlyProbeConfirmMinConfidence', ...
        runtime.earlyProbeConfirmMinConfidence, ...
    'CandidateGateEnabled', runtime.candidateGateEnabled, ...
    'UseFusedDdc', true, ...
    'ExternalBaseband', true);
scanner.timerToken = tic;
for channelIndex = 1:scanner.channelCount
    scanner.channels{channelIndex}.timerToken = tic;
end
session.decode.scanner = scanner;
session.mode = 'RUNNING';
message = sprintf( ...
    'Decoder attached to %d carrier(s) at logical %.3f s.', ...
    numel(offsetsHz), double(ringSnapshot.sourceSampleEnd) / ...
    session.metadata.sampleRateHz);
end

function tf = decoderActive(session)
tf = ~isempty(session.decode.scanner) && ...
    ~session.decode.scanner.finalized;
end
