function out = parallelSessionSnapshot(session)
%PARALLELSESSIONSNAPSHOT Return stable diagnostics without actor internals.
if isempty(session)
    out = emptySnapshot();
    return;
end
scanner = scannerSummary(session.decode.scanner);
pendingSamples = session.decode.resultSamples;
ddcReady = false;
ddcProcessedSamples = uint64(0);
ddcMeanComputeSec = 0;
ddcMaxComputeSec = 0;
ddcRingAttached = false;
ddcRingDrained = false;
if ~isempty(session.actors.ddc)
    actor = session.actors.ddc;
    pendingSamples = pendingSamples + actor.pendingInputSamples;
    ddcReady = actor.ready && ~actor.failed && ~actor.stopped;
    ddcProcessedSamples = actor.processedInputSamples;
    if actor.computeCount > 0
        ddcMeanComputeSec = actor.totalComputeSec / ...
            double(actor.computeCount);
    end
    ddcMaxComputeSec = actor.maxComputeSec;
    ddcRingAttached = actor.ringAttached;
    ddcRingDrained = actor.ringDrained;
end
spectrumDroppedChunks = uint64(0);
if ~isempty(session.actors.producer)
    spectrumDroppedChunks = ...
        session.actors.producer.spectrumDroppedChunks;
end
metrics = session.metrics;
out = struct( ...
    'mode', session.mode, ...
    'scanner', scanner, ...
    'pdus', session.pdus, ...
    'spectrum', session.spectrum, ...
    'sourceNextSample', session.source.globalNextSample, ...
    'sourceTerminal', session.source.terminal, ...
    'decoderPipelineQueueSamples', pendingSamples, ...
    'decoderPipelineQueueSec', double(pendingSamples) / ...
        session.metadata.sampleRateHz, ...
    'spectrumDroppedChunks', spectrumDroppedChunks, ...
    'ddcReady', ddcReady, ...
    'ddcProcessedSamples', ddcProcessedSamples, ...
    'ddcMeanComputeSec', ddcMeanComputeSec, ...
    'ddcMaxComputeSec', ddcMaxComputeSec, ...
    'ddcRingAttached', ddcRingAttached, ...
    'ddcRingDrained', ddcRingDrained, ...
    'decoderRequestedSample', session.decode.requestedSample, ...
    'decoderReadySample', session.decode.readySample, ...
    'inputLagSec', metrics.inputLagSec, ...
    'maxInputLagSec', metrics.maxInputLagSec, ...
    'maxProducerLagSec', metrics.maxProducerLagSec, ...
    'maxDdcInputQueueSec', metrics.maxDdcInputQueueSec, ...
    'maxDdcResultQueueSec', metrics.maxDdcResultQueueSec, ...
    'maxDecoderPipelineQueueSec', ...
        metrics.maxDecoderPipelineQueueSec, ...
    'meanCoordinatorSec', metrics.coordinatorTotalSec / ...
        max(1, double(metrics.coordinatorCount)), ...
    'maxCoordinatorSec', metrics.coordinatorMaxSec);
end

function out = scannerSummary(scanner)
if isempty(scanner)
    out = [];
    return;
end
protocols = cell(scanner.channelCount, 1);
states = cell(scanner.channelCount, 1);
for channelIndex = 1:scanner.channelCount
    channel = scanner.channels{channelIndex};
    protocols{channelIndex} = channel.lastSelectedProtocol;
    states{channelIndex} = channel.coordinator.state;
end
decoderCounts = max(1, double(scanner.decoderCompletionCount));
out = struct( ...
    'channelCount', scanner.channelCount, ...
    'selectedProtocols', {protocols}, ...
    'states', {states}, ...
    'feedCount', scanner.feedCount, ...
    'inputSampleCount', scanner.inputSampleCount, ...
    'meanFeedElapsedSec', scanner.totalFeedElapsedSec / ...
        max(1, double(scanner.feedCount)), ...
    'maxFeedElapsedSec', scanner.maxFeedElapsedSec, ...
    'maxFeedBreakdown', scanner.maxFeedBreakdown, ...
    'meanDdcElapsedSec', scanner.totalDdcElapsedSec / ...
        max(1, double(scanner.feedCount)), ...
    'maxDdcElapsedSec', scanner.maxDdcElapsedSec, ...
    'decoderCompletionCount', scanner.decoderCompletionCount, ...
    'meanDecoderComputeSec', ...
        scanner.totalDecoderComputeSec ./ decoderCounts, ...
    'maxDecoderComputeSec', scanner.maxDecoderComputeSec, ...
    'meanDecoderDispatchSec', ...
        scanner.totalDecoderDispatchSec ./ decoderCounts, ...
    'maxDecoderDispatchSec', scanner.maxDecoderDispatchSec, ...
    'finalized', scanner.finalized);
end

function out = emptySnapshot()
out = struct( ...
    'mode', 'IDLE', 'scanner', [], 'pdus', struct([]), ...
    'spectrum', [], 'sourceNextSample', uint64(0), ...
    'sourceTerminal', false, ...
    'decoderPipelineQueueSamples', uint64(0), ...
    'decoderPipelineQueueSec', 0, ...
    'spectrumDroppedChunks', uint64(0), ...
    'ddcReady', false, 'ddcProcessedSamples', uint64(0), ...
    'ddcMeanComputeSec', 0, 'ddcMaxComputeSec', 0, ...
    'ddcRingAttached', false, 'ddcRingDrained', false, ...
    'decoderRequestedSample', uint64(0), ...
    'decoderReadySample', [], ...
    'inputLagSec', 0, 'maxInputLagSec', 0, ...
    'maxProducerLagSec', 0, 'maxDdcInputQueueSec', 0, ...
    'maxDdcResultQueueSec', 0, ...
    'maxDecoderPipelineQueueSec', 0, ...
    'meanCoordinatorSec', 0, 'maxCoordinatorSec', 0);
end
