function [session, messages] = parallelSessionStart(metadata, cfg)
%PARALLELSESSIONSTART Create the single supported live parallel pipeline.
validateConfig(metadata, cfg);
session = emptySession(metadata, cfg);
messages = cell(0, 1);
requestedWorkers = double(cfg.numWorkers) + 1;

try
    token = tic;
    [pool, poolInfo] = radio.stream.acquireParallelPool( ...
        'NumWorkers', requestedWorkers);
    if isempty(pool) || ~poolInfo.available
        error('radio:live:parallelSessionStart:PoolUnavailable', ...
            'A process pool with %d workers is required: %s', ...
            requestedWorkers, poolInfo.reason);
    end
    if pool.NumWorkers < requestedWorkers
        error('radio:live:parallelSessionStart:PoolTooSmall', ...
            ['The running process pool has %d workers; this frontend ', ...
             'requires %d (%d protocol workers plus one DDC worker).'], ...
            pool.NumWorkers, requestedWorkers, cfg.numWorkers);
    end

    if cfg.runtime.prewarmProtocols && isempty(cfg.testHooks.taskFcn)
        warm = radio.stream.prewarmProtocolWorkers( ...
            cfg.protocolNames, 'Pool', pool, ...
            'NumWorkers', pool.NumWorkers);
        if ~warm.success
            error('radio:live:parallelSessionStart:ProtocolPrewarm', ...
                'Protocol worker prewarm failed: %s', warm.errorReason);
        end
        clientWarm = radio.stream.prewarmClientRuntime( ...
            pool, cfg.protocolNames);
        if ~clientWarm.success
            error('radio:live:parallelSessionStart:ClientPrewarm', ...
                'Client runtime prewarm failed: %s', ...
                clientWarm.errorReason);
        end
        messages{end+1, 1} = sprintf( ...
            'Protocol runtime warmed on %d workers in %.3f s.', ...
            pool.NumWorkers, warm.elapsedSec);
    end

    [tunedConfig, rateReport] = radio.tuned.resolveInputConfig( ...
        metadata.sampleRateHz, cfg.tunedConfig);
    session.tunedConfig = tunedConfig;
    session.rateReport = rateReport;

    chunkSamples = max(1, round(cfg.runtime.inputChunkDurationSec * ...
        metadata.sampleRateHz));
    session.ring = radio.live.sharedIqRingCreate( ...
        metadata.sampleRateHz, chunkSamples, ...
        'CenterFrequencyHz', metadata.centerFrequencyHz, ...
        'CapacitySec', cfg.runtime.ringCapacitySec);

    session.actors.spectrum = radio.live.spectrumActorStart( ...
        metadata.sampleRateHz, metadata.centerFrequencyHz, ...
        'Config', cfg.spectrumConfig, ...
        'MaxQueueChunks', cfg.runtime.spectrumQueueLimitChunks);
    session = awaitSpectrum(session, 5);

    ddcSpec = struct( ...
        'inputSampleRateHz', metadata.sampleRateHz, ...
        'frequencyOffsetsHz', 0, ...
        'config', tunedConfig, ...
        'inputCenterFrequencyHz', metadata.centerFrequencyHz, ...
        'capacity', cfg.maxCarrierPaths, ...
        'prewarm', logical(cfg.runtime.prewarmDdc));
    session.actors.ddc = radio.live.ddcActorStart( ...
        pool, ddcSpec, ...
        'MaxQueueSec', cfg.runtime.decoderQueueLimitSec);
    session = awaitDdc(session, 30);

    producerConfig = struct( ...
        'path', metadata.path, ...
        'sampleRateHz', metadata.sampleRateHz, ...
        'centerFrequencyHz', metadata.centerFrequencyHz, ...
        'iqDType', cfg.iqDType, ...
        'headerBytes', metadata.headerBytes, ...
        'chunkDurationSec', cfg.runtime.inputChunkDurationSec, ...
        'replayMode', cfg.replayMode, ...
        'maxLoops', cfg.maxLoops, ...
        'epochSilenceSec', cfg.epochSilenceSec, ...
        'playoutDelaySec', cfg.runtime.playoutDelaySec, ...
        'sharedRing', session.ring);
    session.actors.producer = ...
        radio.live.fileProducerStart(producerConfig);
    session.actors.producer = radio.live.fileProducerAttachSpectrum( ...
        session.actors.producer, session.actors.spectrum);

    spectrumState = radio.scope.spectrumInit( ...
        metadata.sampleRateHz, metadata.centerFrequencyHz, ...
        'Config', cfg.spectrumConfig);
    session.spectrum = radio.scope.spectrumSnapshot( ...
        spectrumState, 'IncludeWaterfall', false);
    session.mode = 'PREVIEW';
    session.startedToken = tic;
    messages{end+1, 1} = sprintf( ...
        'Parallel preview runtime ready in %.3f s; DDC %.0f kS/s (/%d).', ...
        toc(token), rateReport.outputSampleRateHz / 1e3, ...
        rateReport.decimationFactor);
catch ME
    radio.live.parallelSessionClose(session);
    rethrow(ME);
end
end

function session = awaitSpectrum(session, timeoutSec)
token = tic;
while ~session.actors.spectrum.ready && ...
        ~session.actors.spectrum.failed && toc(token) < timeoutSec
    [session.actors.spectrum, snapshot] = ...
        radio.live.spectrumActorPoll(session.actors.spectrum);
    if ~isempty(snapshot), session.spectrum = snapshot; end
    if ~session.actors.spectrum.ready, pause(0.001); end
end
if ~session.actors.spectrum.ready
    error('radio:live:parallelSessionStart:SpectrumStartup', ...
        'Spectrum actor failed to start: %s', ...
        session.actors.spectrum.errorReason);
end
end

function session = awaitDdc(session, timeoutSec)
token = tic;
while ~session.actors.ddc.ready && ~session.actors.ddc.failed && ...
        toc(token) < timeoutSec
    [session.actors.ddc, ~] = ...
        radio.live.ddcActorPoll(session.actors.ddc);
    if ~session.actors.ddc.ready, pause(0.005); end
end
if ~session.actors.ddc.ready
    error('radio:live:parallelSessionStart:DdcStartup', ...
        'DDC actor failed to start: %s', ...
        session.actors.ddc.errorReason);
end
end

function session = emptySession(metadata, cfg)
session = struct( ...
    'mode', 'PREPARING', ...
    'metadata', metadata, ...
    'config', cfg, ...
    'tunedConfig', [], ...
    'rateReport', [], ...
    'actors', struct('producer', [], 'spectrum', [], 'ddc', []), ...
    'ring', [], ...
    'source', struct('globalNextSample', uint64(0), ...
        'completedLoops', uint64(0), 'terminal', false), ...
    'decode', struct('scanner', [], 'offsetsHz', zeros(0, 1), ...
        'resultQueue', {cell(0, 1)}, 'resultHead', 1, ...
        'resultSamples', uint64(0), ...
        'requestedSample', uint64(0), 'readySample', []), ...
    'spectrum', [], ...
    'pdus', struct([]), ...
    'producerRunning', false, ...
    'producerTerminal', false, ...
    'startedToken', [], ...
    'closed', false, ...
    'metrics', emptyMetrics());
end

function metrics = emptyMetrics()
metrics = struct( ...
    'inputLagSec', 0, ...
    'maxInputLagSec', 0, ...
    'maxProducerLagSec', 0, ...
    'maxDdcInputQueueSec', 0, ...
    'maxDdcResultQueueSec', 0, ...
    'maxDecoderPipelineQueueSec', 0, ...
    'coordinatorCount', uint64(0), ...
    'coordinatorTotalSec', 0, ...
    'coordinatorMaxSec', 0);
end

function validateConfig(metadata, cfg)
requiredMetadata = {'path','sampleRateHz','centerFrequencyHz','headerBytes'};
if ~isstruct(metadata) || ~all(isfield(metadata, requiredMetadata))
    error('radio:live:parallelSessionStart:Metadata', ...
        'Capture metadata is incomplete.');
end
validateattributes(cfg.numWorkers, {'numeric'}, ...
    {'scalar','real','finite','integer','positive'});
validateattributes(cfg.maxCarrierPaths, {'numeric'}, ...
    {'scalar','real','finite','integer','positive'});
validateattributes(cfg.runtime.inputChunkDurationSec, {'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(cfg.runtime.playoutDelaySec, {'numeric'}, ...
    {'scalar','real','finite','nonnegative'});
validateattributes(cfg.runtime.ringCapacitySec, {'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(cfg.runtime.decoderQueueLimitSec, {'numeric'}, ...
    {'scalar','real','finite','positive'});
if cfg.runtime.drainMaxBudgetSec < cfg.runtime.drainBudgetSec
    error('radio:live:parallelSessionStart:DrainBudget', ...
        'drainMaxBudgetSec must not be below drainBudgetSec.');
end
end
