function cfg = parallelSessionDefaultConfig()
%PARALLELSESSIONDEFAULTCONFIG Runtime defaults for the parallel live UI.
cfg = struct( ...
    'inputChunkDurationSec', 0.020, ...
    'playoutDelaySec', 0.10, ...
    'maxEventsPerPoll', 16, ...
    'ringCapacitySec', 2.0, ...
    'spectrumQueueLimitChunks', 12, ...
    'decoderQueueLimitSec', 15.0, ...
    'drainChunksPerPoll', 8, ...
    'drainBudgetSec', 0.030, ...
    'drainMaxBudgetSec', 0.080, ...
    'prewarmDdc', true, ...
    'prewarmProtocols', true, ...
    'probeMaxInFlightPerChannel', [], ...
    'earlyProbeConfirm', true, ...
    'earlyProbeConfirmMinConfidence', 0.99, ...
    'candidateGateEnabled', true);
end
