function [session, message] = parallelSessionClear(session)
%PARALLELSESSIONCLEAR Detach decoding while preview continues uninterrupted.
if isempty(session) || session.closed || session.source.terminal
    error('radio:live:parallelSessionClear:Source', ...
        'The live preview source is not active.');
end
session.actors.ddc = radio.live.ddcActorReset(session.actors.ddc);
if ~isempty(session.decode.scanner) && ~session.decode.scanner.finalized
    [session.decode.scanner, ~] = ...
        radio.tuned.multiStreamScannerCancel( ...
            session.decode.scanner, ...
            'Reason', 'carrier_selection_cleared');
end

token = tic;
while session.actors.ddc.resetPending && ...
        ~session.actors.ddc.failed && toc(token) < 5
    [session.actors.ddc, ~] = ...
        radio.live.ddcActorPoll(session.actors.ddc, 'MaxEvents', inf);
    if session.actors.ddc.resetPending, pause(0.001); end
end
if session.actors.ddc.resetPending || session.actors.ddc.failed
    actor = session.actors.ddc;
    error('radio:live:parallelSessionClear:DdcReset', ...
        ['The reusable DDC actor did not reset ', ...
         '(future=%s, output=%d, input=%d, ring=%d, pending=%d): %s'], ...
        char(actor.future.State), actor.outputQueue.QueueLength, ...
        actor.inputQueue.QueueLength, actor.ringAttached, ...
        actor.pendingInputSamples, actor.errorReason);
end

session.decode.scanner = [];
session.decode.offsetsHz = zeros(0, 1);
session.decode.resultQueue = cell(0, 1);
session.decode.resultHead = 1;
session.decode.resultSamples = uint64(0);
session.decode.requestedSample = uint64(0);
session.decode.readySample = [];
session.pdus = struct([]);
session.mode = 'PREVIEW';
message = sprintf( ...
    ['Decoder detached at logical %.3f s; spectrum replay ', ...
     'continues without rewind.'], ...
    double(session.source.globalNextSample) / ...
    session.metadata.sampleRateHz);
end
