function mapping = sharedIqRingOpen(descriptor, writable)
%SHAREDIQRINGOPEN Open and validate one cross-process IQ ring mapping.
if nargin < 2, writable = false; end
required = {'path', 'magic', 'version', 'capacityChunks', ...
    'chunkSamples', 'sampleRateHz', 'centerFrequencyHz'};
missing = required(~isfield(descriptor, required));
if ~isempty(missing)
    error('radio:live:sharedIqRingOpen:Descriptor', ...
        'Shared-ring descriptor is missing field: %s', missing{1});
end
if exist(descriptor.path, 'file') ~= 2
    error('radio:live:sharedIqRingOpen:Missing', ...
        'Shared IQ ring no longer exists: %s', descriptor.path);
end
[format, ~] = radio.live.sharedIqRingLayout(descriptor);
mapping = memmapfile(descriptor.path, ...
    'Writable', logical(writable), 'Format', format, 'Repeat', 1);
if mapping.Data.magic ~= uint64(descriptor.magic) || ...
        mapping.Data.version ~= uint32(descriptor.version) || ...
        mapping.Data.capacityChunks ~= uint32(descriptor.capacityChunks) || ...
        mapping.Data.chunkSamples ~= uint32(descriptor.chunkSamples)
    error('radio:live:sharedIqRingOpen:Layout', ...
        'Shared IQ ring header does not match its descriptor.');
end
end
