function [format, byteCount] = sharedIqRingLayout(descriptor)
%SHAREDIQRINGLAYOUT Define the on-disk layout shared by live IQ actors.
capacity = double(descriptor.capacityChunks);
chunkSamples = double(descriptor.chunkSamples);
validateattributes(capacity, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'});
validateattributes(chunkSamples, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'});

format = { ...
    'uint64', [1 1], 'magic'; ...
    'uint32', [1 1], 'version'; ...
    'uint32', [1 1], 'capacityChunks'; ...
    'uint32', [1 1], 'chunkSamples'; ...
    'uint32', [1 1], 'reserved'; ...
    'uint64', [1 1], 'writeSequence'; ...
    'uint64', [1 1], 'sourceSampleEnd'; ...
    'uint32', [1 1], 'terminal'; ...
    'uint32', [1 1], 'writerStopped'; ...
    'uint64', [1 1], 'consumerSequence'; ...
    'uint64', [1 1], 'overrunCount'; ...
    'uint64', [capacity 1], 'beginSequence'; ...
    'uint64', [capacity 1], 'endSequence'; ...
    'uint64', [capacity 1], 'sourceSampleStart'; ...
    'uint64', [capacity 1], 'sourceSampleEndBySlot'; ...
    'uint64', [capacity 1], 'chunkSequenceNumber'; ...
    'uint64', [capacity 1], 'timestampStartNs'; ...
    'uint64', [capacity 1], 'droppedSourceSamples'; ...
    'uint32', [capacity 1], 'sampleCount'; ...
    'uint32', [capacity 1], 'flags'; ...
    'single', [capacity 1], 'scale'; ...
    'int16', [2 * chunkSamples capacity], 'iqRealImag'};

% Header: 64 bytes.  Per slot: seven uint64 values, two uint32
% values, one single scale, and interleaved CI16 IQ.
byteCount = 64 + capacity * (68 + 4 * chunkSamples);
end
