function snapshot = sharedIqRingSnapshot(descriptor)
%SHAREDIQRINGSNAPSHOT Read a stable live-edge/control-plane snapshot.
mapping = radio.live.sharedIqRingOpen(descriptor, false);
for attempt = 1:4
    first = uint64(mapping.Data.writeSequence);
    sourceEnd = uint64(mapping.Data.sourceSampleEnd);
    terminal = logical(mapping.Data.terminal);
    consumer = uint64(mapping.Data.consumerSequence);
    second = uint64(mapping.Data.writeSequence);
    if first == second, break; end
end
snapshot = struct( ...
    'writeSequence', second, ...
    'nextSequence', second + uint64(1), ...
    'sourceSampleEnd', sourceEnd, ...
    'consumerSequence', consumer, ...
    'terminal', terminal, ...
    'capacityChunks', uint64(descriptor.capacityChunks), ...
    'capacitySec', double(descriptor.capacitySec));
end
