function spectrumActorWorker( ...
        sampleRateHz, centerFrequencyHz, config, outputQueue, actorId)
%SPECTRUMACTORWORKER Own spectrum state on a background thread.
try
    state = radio.scope.spectrumInit(sampleRateHz, centerFrequencyHz, ...
        'Config', config);
    inputQueue = parallel.pool.PollableDataQueue;
    send(outputQueue, struct('type', 'ready', ...
        'actorId', uint64(actorId), 'inputQueue', inputQueue));
    while true
        message = poll(inputQueue, 0.05);
        if isempty(message), continue; end
        if ~isstruct(message) || ~isfield(message, 'type') || ...
                message.actorId ~= actorId
            continue;
        end
        switch char(message.type)
            case 'stop'
                send(outputQueue, struct('type', 'stopped', ...
                    'actorId', uint64(actorId)));
                return;
            case 'chunk'
                chunk = radio.stream.lockedDecoderActorUnpackChunk( ...
                    message.chunk, message.payload);
                [state, output] = radio.scope.spectrumFeed(state, chunk);
                if output.updated
                    snapshot = radio.scope.spectrumSnapshot( ...
                        state, 'IncludeWaterfall', false);
                    send(outputQueue, struct( ...
                        'type', 'snapshot', ...
                        'actorId', uint64(actorId), ...
                        'sourceSampleEnd', chunk.sourceSampleEnd, ...
                        'snapshot', snapshot));
                end
        end
    end
catch ME
    send(outputQueue, struct('type', 'error', ...
        'actorId', uint64(actorId), ...
        'errorReason', sprintf('%s: %s', ME.identifier, ME.message)));
end
end
