function actor = spectrumActorStart(sampleRateHz, centerFrequencyHz, varargin)
%SPECTRUMACTORSTART Start a best-effort background PSD consumer.
p = inputParser;
p.addParameter('Config', radio.scope.defaultConfig());
p.addParameter('MaxQueueChunks', 12);
p.parse(varargin{:});
persistent nextActorId
if isempty(nextActorId), nextActorId = uint64(1); end
actorId = nextActorId;
nextActorId = nextActorId + uint64(1);
outputQueue = parallel.pool.PollableDataQueue;
future = parfeval(backgroundPool, @radio.live.spectrumActorWorker, 0, ...
    double(sampleRateHz), double(centerFrequencyHz), p.Results.Config, ...
    outputQueue, actorId);
actor = struct( ...
    'actorId', actorId, ...
    'future', future, ...
    'outputQueue', outputQueue, ...
    'inputQueue', [], ...
    'ready', false, ...
    'stopped', false, ...
    'failed', false, ...
    'pendingMessages', {cell(0, 1)}, ...
    'maxQueueChunks', double(p.Results.MaxQueueChunks), ...
    'droppedChunkCount', uint64(0), ...
    'needsDiscontinuity', false, ...
    'lastInputSampleEnd', uint64(0), ...
    'lastSnapshotSampleEnd', uint64(0), ...
    'errorReason', '');
end
