function tracker = candidateTrackerInit(varargin)
%CANDIDATETRACKERINIT Initialize frequency-track lifecycle state.
p = inputParser;
p.addParameter('Config', radio.wideband.defaultConfig());
p.parse(varargin{:});
tracker = struct( ...
    'config', p.Results.Config.tracker, ...
    'tracks', radio.wideband.emptyTrack(), ...
    'nextTrackId', uint64(1), ...
    'continuityGeneration', uint64(0));
tracker.tracks = tracker.tracks([]);
end
