function state = channelizerInit(sampleRateHz, varargin)
%CHANNELIZERINIT Initialize a continuous 2x-oversampled WOLA/PFB.
p = inputParser;
p.addParameter('Config', radio.wideband.defaultConfig());
p.parse(varargin{:});

cfg = p.Results.Config;
radio.wideband.validateConfig(cfg, sampleRateHz);
nChannels = double(cfg.channelizer.numChannels);
hopSamples = nChannels / double(cfg.channelizer.oversampleFactor);
tapsPerChannel = double(cfg.channelizer.tapsPerChannel);
prototype = designPrototype(nChannels, tapsPerChannel, ...
    cfg.channelizer.prototypeCutoffBins);

state = struct( ...
    'sampleRateHz', double(sampleRateHz), ...
    'numChannels', nChannels, ...
    'oversampleFactor', double(cfg.channelizer.oversampleFactor), ...
    'hopSamples', hopSamples, ...
    'tapsPerChannel', tapsPerChannel, ...
    'frameBlockSize', double(cfg.channelizer.frameBlockSize), ...
    'prototype', prototype, ...
    'filterLength', numel(prototype), ...
    'groupDelaySamples', (numel(prototype) - 1) / 2, ...
    'subbandSampleRateHz', double(sampleRateHz) / hopSamples, ...
    'binCenterOffsetHz', signedBins(nChannels) .* ...
        (double(sampleRateHz) / nChannels), ...
    'pendingIq', complex(zeros(0, 1, 'single')), ...
    'pendingSourceStart', uint64(0), ...
    'inputEndSample', uint64(0), ...
    'nextOutputSample', uint64(0), ...
    'continuityGeneration', uint64(0), ...
    'initialized', false);
end

function h = designPrototype(nChannels, tapsPerChannel, cutoffBins)
lengthSamples = nChannels * tapsPerChannel;
n = (0:lengthSamples-1).' - (lengthSamples - 1) / 2;
cutoff = double(cutoffBins) / nChannels;
ideal = 2 * cutoff .* sinc(2 * cutoff .* n);
if lengthSamples == 1
    window = 1;
else
    index = (0:lengthSamples-1).';
    window = 0.42 - 0.5 .* cos(2*pi*index/(lengthSamples-1)) + ...
        0.08 .* cos(4*pi*index/(lengthSamples-1));
end
h = ideal .* window;
h = single(h ./ sum(h));
end

function bins = signedBins(nChannels)
bins = (-nChannels/2:nChannels/2-1).';
end
