function state = channelExtractorInit(track, batch, varargin)
%CHANNELEXTRACTORINIT Initialize fine DDC and channel low-pass state.
p = inputParser;
p.addParameter('Config', radio.wideband.defaultConfig());
p.parse(varargin{:});
cfg = p.Results.Config.extractor;

bin = double(track.coarseBin);
if bin < 1 || bin > size(batch.iq, 1)
    error('radio:wideband:channelExtractorInit:CoarseBin', ...
        'Track coarse bin is outside the channelizer output.');
end
coefficients = designLowpass( ...
    cfg.lowpassCutoffHz, batch.sampleRateHz, cfg.lowpassTaps);
state = struct( ...
    'trackId', uint64(track.trackId), ...
    'channelId', uint64(track.channelId), ...
    'coarseBin', uint32(track.coarseBin), ...
    'coarseCenterOffsetHz', double(batch.binCenterOffsetHz(bin)), ...
    'sampleRateHz', double(batch.sampleRateHz), ...
    'ncoPhaseRad', 0.0, ...
    'filterCoefficients', coefficients, ...
    'filterState', complex(zeros(numel(coefficients) - 1, 1, 'single')), ...
    'lastOutputSampleEnd', uint64(batch.outputSampleStart), ...
    'sequenceNumber', uint64(0), ...
    'mappingOutputSampleStart', uint64(batch.outputSampleStart), ...
    'mappingWidebandSourceSample', firstSourceSample(batch), ...
    'widebandSamplesPerOutput', double(batch.widebandSampleRateHz / ...
        batch.sampleRateHz), ...
    'continuityGeneration', uint64(batch.continuityGeneration));
end

function coefficients = designLowpass(cutoffHz, sampleRateHz, tapCount)
center = (tapCount - 1) / 2;
n = (0:tapCount-1).' - center;
normalizedCutoff = cutoffHz / sampleRateHz;
ideal = 2 * normalizedCutoff .* sinc(2 * normalizedCutoff .* n);
index = (0:tapCount-1).';
window = 0.54 - 0.46 .* cos(2*pi*index/(tapCount-1));
coefficients = single(ideal .* window);
coefficients = coefficients ./ sum(coefficients);
end

function sample = firstSourceSample(batch)
if isempty(batch.frameSourceSamples)
    sample = 0.0;
else
    sample = double(batch.frameSourceSamples(1));
end
end
