function [state, batch] = channelizerFeed(state, chunk)
%CHANNELIZERFEED Transform a continuous wideband IqChunk into subband IQ.
radio.stream.validateIqChunk(chunk);
if chunk.sampleRateHz ~= state.sampleRateHz
    error('radio:wideband:channelizerFeed:SampleRate', ...
        'Chunk and channelizer sample rates differ.');
end

hasGap = state.initialized && chunk.sourceSampleStart ~= state.inputEndSample;
reset = chunk.discontinuity || chunk.droppedSourceSamples > 0 || hasGap;
if ~state.initialized || reset
    state.pendingIq = complex(zeros(0, 1, 'single'));
    state.pendingSourceStart = chunk.sourceSampleStart;
    state.nextOutputSample = uint64(0);
    if state.initialized
        state.continuityGeneration = state.continuityGeneration + uint64(1);
    end
    state.initialized = true;
end

state.pendingIq = [state.pendingIq; single(chunk.iq(:))];
state.inputEndSample = chunk.sourceSampleEnd;
available = numel(state.pendingIq);
if available < state.filterLength
    batch = emptyBatch(state, chunk, reset);
    return;
end

frameCount = floor((available - state.filterLength) / ...
    state.hopSamples) + 1;
subbands = complex(zeros(state.numChannels, frameCount, 'single'));
frameStarts = state.pendingSourceStart + uint64( ...
    (0:frameCount-1) .* state.hopSamples);
signed = (-state.numChannels/2:state.numChannels/2-1).';

for blockStart = 1:state.frameBlockSize:frameCount
    blockEnd = min(frameCount, blockStart + state.frameBlockSize - 1);
    blockFrames = blockStart:blockEnd;
    firstSamples = (blockFrames - 1) .* state.hopSamples + 1;
    indices = (0:state.filterLength-1).' + firstSamples;
    samples = state.pendingIq(indices);
    weighted = samples .* state.prototype;
    folded = reshape(weighted, state.numChannels, ...
        state.tapsPerChannel, numel(blockFrames));
    folded = reshape(sum(folded, 2), ...
        state.numChannels, numel(blockFrames));
    spectrum = fftshift(fft(folded, state.numChannels, 1), 1);
    phaseSamples = mod(double(frameStarts(blockFrames)), ...
        state.numChannels);
    phaseCorrection = exp(-1i .* 2 .* pi .* signed .* ...
        phaseSamples ./ state.numChannels);
    subbands(:, blockFrames) = single(spectrum .* phaseCorrection);
end

consumed = frameCount * state.hopSamples;
state.pendingIq = state.pendingIq(consumed+1:end);
state.pendingSourceStart = state.pendingSourceStart + uint64(consumed);
outputStart = state.nextOutputSample;
state.nextOutputSample = state.nextOutputSample + uint64(frameCount);

batch = struct( ...
    'iq', subbands, ...
    'sampleRateHz', state.subbandSampleRateHz, ...
    'outputSampleStart', outputStart, ...
    'outputSampleEnd', outputStart + uint64(frameCount), ...
    'frameSourceSamples', double(frameStarts) + state.groupDelaySamples, ...
    'binCenterOffsetHz', state.binCenterOffsetHz, ...
    'widebandCenterFrequencyHz', double(chunk.centerFrequencyHz), ...
    'widebandSampleRateHz', state.sampleRateHz, ...
    'groupDelaySamples', state.groupDelaySamples, ...
    'continuityGeneration', state.continuityGeneration, ...
    'discontinuity', logical(reset), ...
    'droppedSourceSamples', uint64(chunk.droppedSourceSamples));
end

function batch = emptyBatch(state, chunk, reset)
batch = struct( ...
    'iq', complex(zeros(state.numChannels, 0, 'single')), ...
    'sampleRateHz', state.subbandSampleRateHz, ...
    'outputSampleStart', state.nextOutputSample, ...
    'outputSampleEnd', state.nextOutputSample, ...
    'frameSourceSamples', zeros(1, 0), ...
    'binCenterOffsetHz', state.binCenterOffsetHz, ...
    'widebandCenterFrequencyHz', double(chunk.centerFrequencyHz), ...
    'widebandSampleRateHz', state.sampleRateHz, ...
    'groupDelaySamples', state.groupDelaySamples, ...
    'continuityGeneration', state.continuityGeneration, ...
    'discontinuity', logical(reset), ...
    'droppedSourceSamples', uint64(chunk.droppedSourceSamples));
end
