function channel = emptyChannel()
%EMPTYCHANNEL Return the shared per-frequency runtime schema.
channel = struct( ...
    'trackId', uint64(0), ...
    'extractor', [], ...
    'coordinator', [], ...
    'lastTrack', radio.wideband.emptyTrack(), ...
    'lastOutput', [], ...
    'pduCount', uint64(0));
end
