function track = emptyTrack()
%EMPTYTRACK Return the shared wideband candidate-track schema.
track = struct( ...
    'trackId', uint64(0), ...
    'channelId', uint64(0), ...
    'state', '', ...
    'isConfirmed', false, ...
    'frequencyOffsetHz', 0.0, ...
    'centerFrequencyHz', 0.0, ...
    'coarseBin', uint32(0), ...
    'coarseCenterOffsetHz', 0.0, ...
    'powerDb', -inf, ...
    'noiseFloorDb', -inf, ...
    'snrDb', 0.0, ...
    'firstSeenWidebandSample', uint64(0), ...
    'lastSeenWidebandSample', uint64(0), ...
    'firstOutputSample', uint64(0), ...
    'lastSeenOutputSample', uint64(0), ...
    'continuousOnSec', 0.0, ...
    'missingDurationSec', 0.0, ...
    'hitCount', uint64(0), ...
    'continuityGeneration', uint64(0));
end
