function scanner = scannerInit(sampleRateHz, centerFrequencyHz, varargin)
%SCANNERINIT Initialize streaming wideband discovery and protocol decode.
p = inputParser;
p.addParameter('Config', radio.wideband.defaultConfig());
p.addParameter('ProtocolNames', {});
p.addParameter('NumWorkers', 5);
p.addParameter('TaskFcn', []);
p.addParameter('TaskContext', struct());
p.addParameter('LockedDecodeFcn', []);
p.parse(varargin{:});

cfg = p.Results.Config;
radio.wideband.validateConfig(cfg, sampleRateHz);
scanner = struct( ...
    'sampleRateHz', double(sampleRateHz), ...
    'centerFrequencyHz', double(centerFrequencyHz), ...
    'config', cfg, ...
    'channelizer', radio.wideband.channelizerInit( ...
        sampleRateHz, 'Config', cfg), ...
    'tracker', radio.wideband.candidateTrackerInit('Config', cfg), ...
    'channels', radio.wideband.emptyChannel(), ...
    'pdus', struct([]), ...
    'candidateEvents', struct([]), ...
    'closedEpochs', repmat(radio.stream.newEpoch(0, 0, 0, 0), 0, 1), ...
    'feedCount', uint64(0), ...
    'options', struct( ...
        'protocolNames', {p.Results.ProtocolNames}, ...
        'numWorkers', p.Results.NumWorkers, ...
        'taskFcn', p.Results.TaskFcn, ...
        'taskContext', p.Results.TaskContext, ...
        'lockedDecodeFcn', p.Results.LockedDecodeFcn));
scanner.channels = scanner.channels([]);
end
