function [scanner, output] = scannerFeed(scanner, chunk)
%SCANNERFEED Advance wideband channelization, tracking, and protocol races.
radio.stream.validateIqChunk(chunk);
if chunk.sampleRateHz ~= scanner.sampleRateHz
    error('radio:wideband:scannerFeed:SampleRate', ...
        'Chunk and wideband scanner sample rates differ.');
end
if chunk.centerFrequencyHz ~= scanner.centerFrequencyHz
    error('radio:wideband:scannerFeed:CenterFrequency', ...
        'Retuning requires a discontinuity and a new scanner instance.');
end

[scanner.channelizer, batch] = radio.wideband.channelizerFeed( ...
    scanner.channelizer, chunk);
scanner.feedCount = scanner.feedCount + uint64(1);
if isempty(batch.iq)
    output = makeOutput(batch, struct([]), struct(), struct([]), ...
        struct([]), scanner);
    return;
end

[detections, detectorReport] = radio.wideband.detectCandidates( ...
    batch, 'Config', scanner.config, ...
    'ExistingTracks', scanner.tracker.tracks);
[scanner.tracker, trackerUpdate] = ...
    radio.wideband.candidateTrackerFeed( ...
    scanner.tracker, detections, batch);
scanner.candidateEvents = appendStruct( ...
    scanner.candidateEvents, trackerUpdate.events);

routeTracks = [trackerUpdate.tracks; trackerUpdate.closedTracks];
channelOutputs = cell(numel(routeTracks), 1);
newPdus = struct([]);
closedEpochs = repmat(radio.stream.newEpoch(0, 0, 0, 0), 0, 1);
for trackIndex = 1:numel(routeTracks)
    track = routeTracks(trackIndex);
    [scanner, channelIndex] = ensureChannel(scanner, track, batch);
    channel = scanner.channels(channelIndex);
    [channel.extractor, narrowChunk] = ...
        radio.wideband.channelExtractorFeed( ...
        channel.extractor, track, batch);
    [channel.coordinator, channelOutput] = ...
        radio.stream.raceCoordinatorFeed( ...
        channel.coordinator, narrowChunk);
    channel.lastTrack = track;
    channel.lastOutput = channelOutput;
    emitted = emittedPdus(channelOutput);
    emitted = stampWidebandPdus(emitted, channel.extractor, track);
    channel.pduCount = channel.pduCount + uint64(numel(emitted));
    scanner.channels(channelIndex) = channel;
    scanner.pdus = appendStruct(scanner.pdus, emitted);
    newPdus = appendStruct(newPdus, emitted);
    scanner.closedEpochs = appendStruct( ...
        scanner.closedEpochs, channelOutput.closedEpochs);
    closedEpochs = appendStruct(closedEpochs, channelOutput.closedEpochs);
    channelOutputs{trackIndex} = struct( ...
        'track', track, ...
        'narrowChunk', narrowChunk, ...
        'coordinator', channelOutput);
end

closedIds = [trackerUpdate.closedTracks.trackId];
if ~isempty(closedIds)
    keep = ~ismember([scanner.channels.trackId], closedIds);
    scanner.channels = scanner.channels(keep);
end

output = makeOutput(batch, detections, detectorReport, ...
    trackerUpdate, channelOutputs, scanner);
output.newPdus = newPdus;
output.closedEpochs = closedEpochs;
end

function [scanner, index] = ensureChannel(scanner, track, batch)
index = find([scanner.channels.trackId] == track.trackId, 1);
if ~isempty(index)
    return;
end
channel = radio.wideband.emptyChannel();
channel.trackId = track.trackId;
channel.extractor = radio.wideband.channelExtractorInit( ...
    track, batch, 'Config', scanner.config);
streamConfig = scanner.config.stream;
if isfinite(track.noiseFloorDb)
    streamConfig.activity.initialNoiseFloorDb = track.noiseFloorDb;
end
channel.coordinator = radio.stream.raceCoordinatorInit( ...
    batch.sampleRateHz, ...
    'Config', streamConfig, ...
    'ChannelId', track.channelId, ...
    'CenterFrequencyHz', track.centerFrequencyHz, ...
    'ProtocolNames', scanner.options.protocolNames, ...
    'Mode', scanner.options.mode, ...
    'NumWorkers', scanner.options.numWorkers, ...
    'PoolType', scanner.options.poolType, ...
    'TaskFcn', scanner.options.taskFcn, ...
    'TaskContext', scanner.options.taskContext, ...
    'LockedDecodeFcn', scanner.options.lockedDecodeFcn);
channel.lastTrack = track;
scanner.channels(end+1, 1) = channel;
index = numel(scanner.channels);
end

function pdus = emittedPdus(output)
pdus = struct([]);
eventTypes = {output.events.type};
if any(strcmp(eventTypes, 'CATCHUP_COMPLETE')) && ...
        ~isempty(output.lastCatchup)
    pdus = appendStruct(pdus, output.lastCatchup.pdus);
end
if ~isempty(output.decoder) && isfield(output.decoder, 'newPdus')
    pdus = appendStruct(pdus, output.decoder.newPdus);
end
end

function pdus = stampWidebandPdus(pdus, extractor, track)
for index = 1:numel(pdus)
    channelSample = radio.getNestedField( ...
        pdus(index), 'extra.stream.source_sample', ...
        extractor.mappingOutputSampleStart);
    relative = double(channelSample) - ...
        double(extractor.mappingOutputSampleStart);
    widebandSample = extractor.mappingWidebandSourceSample + ...
        relative * extractor.widebandSamplesPerOutput;
    info = struct( ...
        'track_id', uint64(track.trackId), ...
        'rf_center_frequency_hz', double(track.centerFrequencyHz), ...
        'frequency_offset_hz', double(track.frequencyOffsetHz), ...
        'coarse_bin', uint32(extractor.coarseBin), ...
        'coarse_center_offset_hz', extractor.coarseCenterOffsetHz, ...
        'source_sample', uint64(max(0, round(widebandSample))), ...
        'source_sample_exact', double(widebandSample));
    if ~isfield(pdus(index), 'extra') || ~isstruct(pdus(index).extra)
        pdus(index).extra = struct();
    end
    pdus(index).extra.wideband = info;
end
end

function value = appendStruct(value, items)
if isempty(items), return; end
if isempty(value)
    value = items(:);
else
    value = [value(:); items(:)];
end
end

function output = makeOutput(batch, detections, detector, tracker, ...
        channels, scanner)
output = struct( ...
    'batch', batch, ...
    'detections', detections, ...
    'detector', detector, ...
    'tracker', tracker, ...
    'channels', {channels}, ...
    'activeTrackCount', numel(scanner.tracker.tracks), ...
    'activeChannelCount', numel(scanner.channels), ...
    'newPdus', struct([]), ...
    'closedEpochs', repmat(radio.stream.newEpoch(0, 0, 0, 0), 0, 1));
end
