function [pdus, report] = scanFile(path, varargin)
%SCANFILE Replay a wideband IQ file through the streaming PFB scanner.
p = inputParser;
p.addParameter('SampleRate', []);
p.addParameter('IqDType', 'int16');
p.addParameter('CenterFrequencyHz', 0);
p.addParameter('Config', radio.wideband.defaultConfig());
p.addParameter('ProtocolNames', {});
p.addParameter('NumWorkers', 5);
p.addParameter('TaskFcn', []);
p.addParameter('TaskContext', struct());
p.addParameter('LockedDecodeFcn', []);
p.addParameter('ShowProgress', false);
p.parse(varargin{:});

cfg = p.Results.Config;
source = radio.stream.fileSourceInit(path, ...
    'SampleRateHz', p.Results.SampleRate, ...
    'ChunkDurationSec', cfg.chunkDurationSec, ...
    'DType', p.Results.IqDType, ...
    'CenterFrequencyHz', p.Results.CenterFrequencyHz);
scanner = radio.wideband.scannerInit( ...
    source.sampleRateHz, p.Results.CenterFrequencyHz, ...
    'Config', cfg, ...
    'ProtocolNames', p.Results.ProtocolNames, ...
    'NumWorkers', p.Results.NumWorkers, ...
    'TaskFcn', p.Results.TaskFcn, ...
    'TaskContext', p.Results.TaskContext, ...
    'LockedDecodeFcn', p.Results.LockedDecodeFcn);

timerToken = tic;
nextProgress = 0.1;
try
    done = false;
    while ~done
        [source, chunk, done] = radio.stream.fileSourceRead(source);
        if isempty(chunk), break; end
        [scanner, ~] = radio.wideband.scannerFeed(scanner, chunk);
        if p.Results.ShowProgress && source.totalSamples > 0
            fraction = double(source.nextSample) / double(source.totalSamples);
            if fraction >= nextProgress || done
                fprintf(['Wideband replay: %5.1f%%  tracks=%d  ', ...
                    'channels=%d  pdus=%d\n'], ...
                    100 * fraction, numel(scanner.tracker.tracks), ...
                    numel(scanner.channels), numel(scanner.pdus));
                nextProgress = nextProgress + 0.1;
            end
        end
    end
    inputSampleCount = source.nextSample;
    scanner = flushScanner(scanner, source.nextSample, ...
        source.nextSequenceNumber, source.sampleRateHz, ...
        p.Results.CenterFrequencyHz, cfg);
    source = radio.stream.fileSourceClose(source);
catch ME
    source = radio.stream.fileSourceClose(source); %#ok<NASGU>
    rethrow(ME);
end

pdus = radio.normalizePdus(scanner.pdus);
report = buildReport(scanner, source.sampleRateHz, ...
    p.Results.CenterFrequencyHz, inputSampleCount, toc(timerToken));
end

function scanner = flushScanner(scanner, firstSample, firstSequence, ...
        sampleRateHz, centerFrequencyHz, cfg)
flushSec = max(cfg.tracker.offHangSec, ...
    cfg.stream.activity.offHangSec) + 2 * cfg.chunkDurationSec + ...
    scanner.channelizer.filterLength / sampleRateHz;
remaining = max(1, ceil(flushSec * sampleRateHz));
chunkSamples = max(1, round(cfg.chunkDurationSec * sampleRateHz));
sample = uint64(firstSample);
sequence = uint64(firstSequence);
while remaining > 0
    count = min(remaining, chunkSamples);
    chunk = radio.stream.makeIqChunk( ...
        complex(zeros(count, 1, 'single')), sampleRateHz, sample, ...
        'SequenceNumber', sequence, ...
        'CenterFrequencyHz', centerFrequencyHz);
    [scanner, ~] = radio.wideband.scannerFeed(scanner, chunk);
    sample = sample + uint64(count);
    sequence = sequence + uint64(1);
    remaining = remaining - count;
end
end

function report = buildReport(scanner, sampleRateHz, centerFrequencyHz, ...
        inputSampleCount, elapsedSec)
events = scanner.candidateEvents;
startedMask = false(size(events));
activatedMask = false(size(events));
if ~isempty(events)
    startedMask = strcmp({events.type}, 'TRACK_STARTED');
    activatedMask = strcmp({events.type}, 'TRACK_ACTIVATED');
end
started = events(startedMask);
activated = events(activatedMask);
startedIds = uint64([]);
activatedIds = uint64([]);
frequenciesHz = zeros(1, 0);
if ~isempty(started)
    startedIds = [started.trackId];
end
if ~isempty(activated)
    activatedIds = [activated.trackId];
    frequenciesHz = centerFrequencyHz + [activated.frequencyOffsetHz];
end
epochs = scanner.closedEpochs;
confirmedMask = false(size(epochs));
if ~isempty(epochs)
    confirmedMask = strcmp({epochs.outcome}, 'confirmed');
end
protocols = {};
if any(confirmedMask)
    protocols = unique({epochs(confirmedMask).protocol}, 'stable');
end
if any(confirmedMask) || ~isempty(scanner.pdus)
    outcome = 'confirmed';
elseif ~isempty(activated)
    outcome = 'unclassified';
elseif ~isempty(started)
    outcome = 'candidate_only';
else
    outcome = 'no_signal';
end
selectedProtocol = '';
if numel(protocols) == 1
    selectedProtocol = protocols{1};
end
durationSec = double(inputSampleCount) / sampleRateHz;
report = struct( ...
    'outcome', outcome, ...
    'executionMode', 'wideband-streaming', ...
    'selectedProtocol', selectedProtocol, ...
    'protocolsDetected', {protocols}, ...
    'sampleRateHz', double(sampleRateHz), ...
    'centerFrequencyHz', double(centerFrequencyHz), ...
    'inputSampleCount', uint64(inputSampleCount), ...
    'inputDurationSec', durationSec, ...
    'elapsedSec', double(elapsedSec), ...
    'realTimeFactor', double(elapsedSec) / max(durationSec, eps), ...
    'candidateTrackCount', numel(unique(startedIds)), ...
    'activatedTrackCount', numel(unique(activatedIds)), ...
    'detectedFrequenciesHz', unique(frequenciesHz), ...
    'remainingTrackCount', numel(scanner.tracker.tracks), ...
    'remainingChannelCount', numel(scanner.channels), ...
    'epochCount', numel(epochs), ...
    'confirmedEpochCount', sum(confirmedMask), ...
    'epochs', epochs, ...
    'candidateEvents', events, ...
    'pduCount', numel(scanner.pdus), ...
    'channelizer', struct( ...
        'numChannels', scanner.channelizer.numChannels, ...
        'oversampleFactor', scanner.channelizer.oversampleFactor, ...
        'channelSpacingHz', sampleRateHz / ...
            scanner.channelizer.numChannels, ...
        'subbandSampleRateHz', ...
            scanner.channelizer.subbandSampleRateHz, ...
        'tapsPerChannel', scanner.channelizer.tapsPerChannel));
end
