function [pdus, report] = scanIq(iq, sampleRateHz, varargin)
%SCANIQ Replay a finite wideband IQ vector through the streaming scanner.
p = inputParser;
p.addParameter('CenterFrequencyHz', 0);
p.addParameter('Config', radio.wideband.defaultConfig());
p.addParameter('ProtocolNames', {});
p.addParameter('NumWorkers', 5);
p.addParameter('TaskFcn', []);
p.addParameter('TaskContext', struct());
p.addParameter('LockedDecodeFcn', []);
p.addParameter('Flush', true);
p.parse(varargin{:});

iq = iq(:);
cfg = p.Results.Config;
scanner = radio.wideband.scannerInit( ...
    sampleRateHz, p.Results.CenterFrequencyHz, ...
    'Config', cfg, ...
    'ProtocolNames', p.Results.ProtocolNames, ...
    'NumWorkers', p.Results.NumWorkers, ...
    'TaskFcn', p.Results.TaskFcn, ...
    'TaskContext', p.Results.TaskContext, ...
    'LockedDecodeFcn', p.Results.LockedDecodeFcn);

chunkSamples = max(1, round(cfg.chunkDurationSec * sampleRateHz));
source = iq;
if p.Results.Flush
    flushSec = max(cfg.tracker.offHangSec, ...
        cfg.stream.activity.offHangSec) + 2 * cfg.chunkDurationSec;
    source = [source; complex(zeros(ceil(flushSec * sampleRateHz), 1, ...
        'like', iq))];
end
eventCount = 0;
detectedFrequencyHz = zeros(0, 1);
for first = 1:chunkSamples:numel(source)
    last = min(numel(source), first + chunkSamples - 1);
    chunk = radio.stream.makeIqChunk( ...
        source(first:last), sampleRateHz, uint64(first - 1), ...
        'SequenceNumber', uint64(floor((first - 1) / chunkSamples)), ...
        'CenterFrequencyHz', p.Results.CenterFrequencyHz);
    [scanner, output] = radio.wideband.scannerFeed(scanner, chunk);
    if isstruct(output.tracker) && isfield(output.tracker, 'events')
        eventCount = eventCount + numel(output.tracker.events);
    end
    if ~isempty(output.detections)
        detectedFrequencyHz = [detectedFrequencyHz; ...
            [output.detections.centerFrequencyHz].']; %#ok<AGROW>
    end
end

pdus = scanner.pdus;
report = struct( ...
    'sampleRateHz', double(sampleRateHz), ...
    'centerFrequencyHz', double(p.Results.CenterFrequencyHz), ...
    'inputSampleCount', uint64(numel(iq)), ...
    'chunkDurationSec', cfg.chunkDurationSec, ...
    'feedCount', scanner.feedCount, ...
    'candidateEventCount', eventCount, ...
    'detectedFrequencyHz', unique(detectedFrequencyHz), ...
    'remainingTrackCount', numel(scanner.tracker.tracks), ...
    'remainingChannelCount', numel(scanner.channels), ...
    'closedEpochs', scanner.closedEpochs, ...
    'pduCount', numel(pdus), ...
    'scanner', scanner);
end
