function validateConfig(cfg, sampleRateHz)
%VALIDATECONFIG Validate cross-layer wideband scanner settings.
required = {'channelizer', 'detector', 'tracker', 'extractor', 'stream'};
missing = required(~isfield(cfg, required));
if ~isempty(missing)
    error('radio:wideband:validateConfig:MissingField', ...
        'Wideband config is missing field: %s', missing{1});
end
validateattributes(sampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, 'sampleRateHz');

c = cfg.channelizer;
validateattributes(c.numChannels, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, mfilename, 'numChannels');
if c.numChannels < 4 || mod(c.numChannels, 2) ~= 0
    error('radio:wideband:validateConfig:NumChannels', ...
        'numChannels must be an even integer of at least four.');
end
if c.oversampleFactor ~= 2
    error('radio:wideband:validateConfig:OversampleFactor', ...
        'The first streaming implementation supports only 2x WOLA.');
end
validateattributes(c.tapsPerChannel, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, mfilename, 'tapsPerChannel');
validateattributes(c.frameBlockSize, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, mfilename, 'frameBlockSize');
validateattributes(c.prototypeCutoffBins, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 0, '<', 1}, ...
    mfilename, 'prototypeCutoffBins');

subbandRateHz = sampleRateHz * c.oversampleFactor / c.numChannels;
if cfg.extractor.lowpassCutoffHz >= subbandRateHz / 2
    error('radio:wideband:validateConfig:ExtractorCutoff', ...
        ['extractor.lowpassCutoffHz must be below half the ', ...
        'oversampled subband rate (%.3f Hz).'], subbandRateHz / 2);
end
if mod(cfg.extractor.lowpassTaps, 2) ~= 1 || ...
        cfg.extractor.lowpassTaps < 3
    error('radio:wideband:validateConfig:ExtractorTaps', ...
        'extractor.lowpassTaps must be an odd integer of at least three.');
end
if cfg.tracker.offHangSec < cfg.tracker.minOnSec
    error('radio:wideband:validateConfig:TrackerTiming', ...
        'tracker.offHangSec must not be shorter than tracker.minOnSec.');
end
if cfg.tracker.offHangSec < cfg.stream.activity.offHangSec
    error('radio:wideband:validateConfig:ReleaseBeforeEpochClose', ...
        ['tracker.offHangSec must be at least as long as the narrowband ', ...
        'stream activity offHangSec.']);
end
end
