%% TETRA pi/4-DQPSK symbol synchronization and hard-decision debug
% Run this script from the MATLAB project root or click Run in MATLAB.

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(projectRoot);
startup;

TARGET_FILE = '/home/lzkj/lzkj_workspace/python_docs/DMR_demo/data/tetra_dmo_20240413_430050000_baseband.wav';
OUTPUT_DIR = fullfile(projectRoot, 'outputs', 'tetra_symbol_debug', 'interactive_latest');

result = tetra.symbolDebug(TARGET_FILE, ...
    'OutputDir', OUTPUT_DIR, ...
    'CreateFigures', true, ...
    'ShowFigures', true, ...
    'SaveFigures', false, ...
    'ActivePrePadSec', 0.020, ...
    'ActivePostPadSec', 2.200, ...
    'ActiveMaxSec', 2.500);

fprintf('\n=== TETRA symbol debug ===\n');
fprintf('Input: %s\n', result.path);
fprintf('Output: %s\n', result.outputDir);
fprintf('Input Fs: %.0f Hz, target Fs: %.0f Hz\n', ...
    result.inputSampleRateHz, result.targetSampleRateHz);
fprintf('Active window: %.3f s to %.3f s (%s)\n', ...
    result.activeInfo.startSec, result.activeInfo.endSec, result.activeInfo.mode);
fprintf('Coarse FO: %.1f Hz, first residual correction: %.1f Hz, final residual: %.1f Hz\n', ...
    result.coarseFrequencyOffsetHz, result.residualCorrectionHz, result.finalResidualHz);
fprintf('Timing phase: %.2f samples, timing median error: %.4f rad\n', ...
    result.timingPhaseSamples, result.timingErrorRad);
fprintf('Decision variant: %s, symbols: %d, bits: %d\n', ...
    result.decisionVariant, result.symbolCount, result.bitCount);
fprintf('Training candidates: %d, good hits: %d\n', ...
    result.training.candidateCount, result.training.goodCount);
for k = 1:numel(result.training.items)
    item = result.training.items(k);
    fprintf('  %-10s errors=%2d/%2d frac=%.3f offset=%g\n', ...
        item.name, item.bestErrors, item.length, item.errorFraction, item.bestOffset);
end
fprintf('DMO bursts: %d confirmed / %d complete candidates, DSB=%d, DNB=%d, payload blocks=%d, MAC blocks=%d\n', ...
    result.slots.confirmedCount, result.slots.completeCount, ...
    result.slots.dsbCount, result.slots.dnbCount, result.slots.payloadBlockCount, ...
    result.slots.macBlockCount);
fprintf('Layer-2 control: SCH/S=%d, SCH/H=%d, DMAC-SYNC=%d, DCC=%d, STCH=%d, SCH/F=%d, MAC PDU=%d, timing assigned=%d\n', ...
    result.slots.schSDecodedCount, result.slots.schHDecodedCount, ...
    result.slots.dmacSyncDecodedCount, result.slots.dccContextCount, ...
    result.slots.stchDecodedCount, result.slots.schFDecodedCount, ...
    result.slots.macPduDecodedCount, result.slots.timingAssignedCount);
for k = 1:min(numel(result.slots.bursts), 8)
    slot = result.slots.bursts(k);
    timing = '';
    if slot.schSOk
        timing = sprintf(' FN=%g TN=%g', slot.frameNumber, slot.slotNumber);
    end
    fprintf('  %-3s %-9s slot=%5d:%-5d%s fieldErr=%2d/%3d BKN1=%3d BKN2=%3d\n', ...
        slot.burstType, slot.trainingName, slot.slotStartBit, slot.slotEndBit, ...
        timing, ...
        slot.totalErrors, slot.totalCheckedBits, ...
        slot.bkn1EndBit - slot.bkn1StartBit + 1, ...
        slot.bkn2EndBit - slot.bkn2StartBit + 1);
end
for k = 1:min(numel(result.slots.payloadBlocks), 6)
    block = result.slots.payloadBlocks(k);
    fprintf('  payload %-3s %-9s %-4s abs=%5d:%-5d len=%3d channel=%s\n', ...
        block.burstType, block.trainingName, block.blockName, ...
        block.absoluteStartBit, block.absoluteEndBit, block.length, ...
        block.logicalChannelHint);
end
