function block = baseChannelBlock(channel, decoded, codec, received, computed, tail)
%BASECHANNELBLOCK Construct common NXDN channel-decoder diagnostics.
block = struct('channel', channel, 'decoded_bits', decoded(:).', ...
    'codec', codec, 'crc_received', received, 'crc_computed', computed, ...
    'crc_ok', received == computed, 'tail_bits', tail(:).', ...
    'tail_ok', ~any(tail), 'ok', false);
end
