function line = formatPdu(pdu, foStr)
%FORMATPDU Format one NXDN PDU.
if nargin < 2, foStr = ''; end
typ = char(radio.getField(pdu, 'type', ''));
ran = radio.getNestedField(pdu, 'extra.ran', []);
if isempty(ran), ranText = ''; else, ranText = sprintf(' RAN=%d', ran); end
if strcmp(typ, 'NXDN_CALL')
    line = sprintf('[%-18s] PROTO=NXDN CALL=%s SRC=%s DST=%s%s DUR=%ss ALIAS=%s%s', ...
        typ, char(radio.getField(pdu, 'flco', '')), valueText(radio.getField(pdu, 'src', 0)), ...
        valueText(radio.getField(pdu, 'dst', 0)), ranText, ...
        valueText(radio.getNestedField(pdu, 'extra.duration_s', 0)), ...
        char(radio.getNestedField(pdu, 'extra.alias', '')), foStr);
    return;
end
line = sprintf('[%-18s] PROTO=NXDN CH=%s%s SRC=%s DST=%s MSG=%s DATA=%s%s', ...
    typ, char(radio.getNestedField(pdu, 'extra.functional_channel', '')), ranText, ...
    valueText(radio.getField(pdu, 'src', 0)), valueText(radio.getField(pdu, 'dst', 0)), ...
    char(radio.getField(pdu, 'flco', '')), ...
    char(radio.getNestedField(pdu, 'extra.payload_hex', '')), foStr);
end

function text = valueText(value)
if isnumeric(value), text = num2str(value); else, text = char(string(value)); end
end
