function state = frameDecoderInit(cfg, varargin)
%FRAMEDECODERINIT Initialize persistent NXDN96 frame/link-layer state.
if nargin < 1 || isempty(cfg), cfg = nxdn.config(); end
p = inputParser;
p.addParameter('RetainDiagnostics', false);
p.parse(varargin{:});

frameTemplate = struct( ...
    'fs_start', 0, 'sync_score', 0, 'mean_decision_error', 0, ...
    'lich_ok', false, 'lich', 0, 'rf_channel_type', '', ...
    'functional_channel', '', 'direction', '', 'voice_present', false, ...
    'supported', false, 'sacch_ok', false, 'facch1_count', 0, ...
    'facch1_ok_count', 0, 'data_ok', false, 'valid', false);
blockTemplate = struct( ...
    'channel', '', 'fs_start', 0, 'half_index', 0, 'ok', false, ...
    'crc_ok', false, 'tail_ok', false, 'ran', [], 'metric', inf, ...
    'payload_hex', '');

state = struct( ...
    'cfg', cfg, ...
    'retainDiagnostics', logical(p.Results.RetainDiagnostics), ...
    'frameTemplate', frameTemplate, ...
    'blockTemplate', blockTemplate, ...
    'frames', repmat(frameTemplate, 0, 1), ...
    'blocks', repmat(blockTemplate, 0, 1), ...
    'sacchState', nxdn.sacchAssemblerInit(), ...
    'session', nxdn.sessionInit(), ...
    'lastRan', [], ...
    'lichValues', zeros(0, 1), ...
    'candidateCount', uint64(0), ...
    'frameCount', uint64(0), ...
    'validFrameCount', uint64(0), ...
    'lichOkCount', uint64(0), ...
    'channelBlockCount', uint64(0), ...
    'validChannelBlockCount', uint64(0), ...
    'validSyncScoreSum', 0, ...
    'sacchAssemblyCount', uint64(0), ...
    'pduCount', uint64(0), ...
    'finalized', false);
end
