function name = messageTypeName(value)
%MESSAGETYPENAME Return the standard NXDN Layer-3 message mnemonic.
names = { ...
    0, 'CALL_RESP'; 1, 'VCALL'; 2, 'VCALL_REC_REQ'; 3, 'VCALL_IV'; ...
    4, 'VCALL_ASSGN'; 5, 'VCALL_ASSGN_DUP'; 6, 'CALL_CONN_RESP'; ...
    7, 'TX_REL_EX'; 8, 'TX_REL'; 9, 'DCALL_HEADER'; 10, 'DCALL_REC_REQ'; ...
    11, 'DCALL_DATA'; 12, 'DCALL_ACK'; 13, 'DCALL_ASSGN_DUP'; ...
    14, 'DCALL_ASSGN'; 15, 'HEAD_DLY'; 16, 'IDLE'; 17, 'DISC'; ...
    23, 'DST_ID_INFO'; 24, 'SITE_INFO'; 25, 'SRV_INFO'; ...
    26, 'CCH_INFO'; 27, 'ADJ_SITE_INFO'; 28, 'FAIL_STAT_INFO'; ...
    32, 'REG_RESP'; 34, 'REG_C_RESP'; 35, 'REG_COMM'; 36, 'GRP_REG_RESP'; ...
    40, 'AUTH_INQ_REQ'; 41, 'AUTH_INQ_RESP'; 42, 'AUTH_INQ_REQ2'; ...
    43, 'AUTH_INQ_RESP2'; 48, 'STAT_INQ_REQ'; 49, 'STAT_INQ_RESP'; ...
    50, 'STAT_REQ'; 51, 'STAT_RESP'; 52, 'REM_CON_REQ'; ...
    53, 'REM_CON_RESP'; 54, 'REM_CON_E_REQ'; 55, 'REM_CON_E_RESP'; ...
    56, 'SDCALL_REQ_HEADER'; 57, 'SDCALL_REQ_DATA'; 58, 'SDCALL_IV'; ...
    59, 'SDCALL_RESP'; 63, 'PROP_FORM'};
name = 'UNKNOWN';
for k = 1:size(names, 1)
    if value == names{k, 1}
        name = names{k, 2};
        return;
    end
end
end
