function [session, callPdu] = sessionFinalize(session, cfg)
%SESSIONFINALIZE Emit an open NXDN call at end of input.
if nargin < 2 || isempty(cfg), cfg = nxdn.config(); end
callPdu = [];
if ~session.active, return; end
dummyExtra = struct('payload_hex', '');
dummy = struct('extra', dummyExtra);
first = session.first_sample;
last = session.last_sample;
if isempty(first), first = 0; end
if isempty(last), last = first; end
extra = struct('call_type', session.call_type, 'ran', session.ran, ...
    'start_sample', session.first_sample, 'end_sample', session.last_sample, ...
    'duration_s', round(max(0, double(last-first)/cfg.targetSampleRateHz), 3), ...
    'message_count', session.message_count, 'alias', session.alias, ...
    'closed_by', 'end_of_input', 'last_payload_hex', ...
    radio.getNestedField(dummy, 'extra.payload_hex', ''));
callPdu = struct('protocol', 'NXDN', 'type', 'NXDN_CALL', 'src', session.src, ...
    'dst', session.dst, 'ts', 0, 'flco', upper(session.call_type), 'fid', '', ...
    'extra', extra, 'raw_bits', false(0, 1));
session = nxdn.sessionInit();
end
