function spec = spec()
%SPEC NXDN ProtocolSpec adapter for unified scanner integration.
cfg = nxdn.config();
spec = struct('name', 'NXDN', 'aliases', {{'nxdn', 'nxdn96'}}, ...
    'config', cfg, ...
    'frontendFcn', @nxdn.frontend, 'decodeFcn', @nxdn.decode, ...
    'postprocessFcn', @nxdn.postprocess, 'dedupFcn', @nxdn.dedupKey, ...
    'formatterFcn', @nxdn.formatPdu, ...
    'targetSampleRateHz', cfg.targetSampleRateHz, 'scanIqFcn', []);
end
