function spec = spec()
%SPEC Dormant ProtocolSpec adapter for later scanner integration.
cfg = nxdn.config();
spec = struct('name', 'NXDN', 'aliases', {{'nxdn', 'nxdn96'}}, ...
    'config', cfg, 'frontendKey', 'nxdn_4fsk', ...
    'frontendFcn', @nxdn.frontend, 'decodeFcn', @nxdn.decode, ...
    'postprocessFcn', @nxdn.postprocess, 'dedupFcn', @nxdn.dedupKey, ...
    'formatterFcn', @nxdn.formatPdu, 'scanMode', 'narrowband_4fsk', ...
    'targetSampleRateHz', cfg.targetSampleRateHz, 'scanIqFcn', [], ...
    'supportsBlindSearch', true, 'supportsFrequencyOffsets', true, ...
    'defaultBasebandScan', true, 'defaultFreqListScan', true, ...
    'defaultBlindSearch', true);
end
