function state = streamInit(inputSampleRateHz, cfg, varargin)
%STREAMINIT Initialize a causal, persistent NXDN96 IQ decoder.
if nargin < 2 || isempty(cfg), cfg = nxdn.config(); end
p = inputParser;
p.addParameter('SourceSampleStart', []);
p.addParameter('RetainDiagnostics', false);
p.parse(varargin{:});
validateattributes(inputSampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
if exist('fir1', 'file') ~= 2
    error('nxdn:streamInit:MissingToolbox', ...
        'fir1 is required for the streaming NXDN frontend.');
end

inputRate = double(inputSampleRateHz);
targetRate = double(cfg.targetSampleRateHz);
[up, down] = rationalRate(inputRate, targetRate);
converter = [];
converterDelaySec = 0;
rateMode = 'none';
rateNumerator = 1;
rateZi = complex(zeros(0, 1));
rateBranches = cell(0, 1);
if up ~= down
    if up <= 128
        % Tuned paths such as 120 -> 48 kS/s (2/5) and 125 -> 48 kS/s
        % (48/125) use a pure MATLAB polyphase FIR.  This avoids both an
        % explicit upsampled vector and the process-only System object.
        halfLength = 10 * max(up, down);
        rateNumerator = up .* fir1(2 * halfLength, ...
            1 / max(up, down), kaiser(2 * halfLength + 1, 5));
        rateBranches = cell(up, 1);
        for phase = 1:up
            rateBranches{phase} = rateNumerator(phase:up:end).';
        end
        converterDelaySec = halfLength / (inputRate * up);
        rateMode = 'polyphase_fir';
    else
        if exist('dsp.FIRRateConverter', 'class') ~= 8
            error('nxdn:streamInit:MissingRateConverter', ...
                'dsp.FIRRateConverter is required for streaming resampling.');
        end
        converter = dsp.FIRRateConverter(up, down, ...
            'AllowArbitraryInputLength', true);
        [converterDelaySec, ~] = outputDelay(converter, FsIn=inputRate);
        rateMode = 'system_object';
    end
end

b = fir1(cfg.frontendTaps - 1, ...
    cfg.frontendCutoffHz / (targetRate / 2));
frontendDelaySamples = (numel(b) - 1) / 2;
pipelineDelaySamples = converterDelaySec * targetRate + ...
    frontendDelaySamples;
dcAlpha = 1 - exp(-1 / max(1, ...
    cfg.streamDcTimeConstantSec * targetRate));
sourceStart = p.Results.SourceSampleStart;
if ~isempty(sourceStart), sourceStart = uint64(sourceStart); end

state = struct( ...
    'cfg', cfg, ...
    'inputSampleRateHz', inputRate, ...
    'targetSampleRateHz', targetRate, ...
    'rateUp', double(up), ...
    'rateDown', double(down), ...
    'rateMode', rateMode, ...
    'rateConverter', converter, ...
    'rateNumerator', rateNumerator(:).', ...
    'rateZi', rateZi, ...
    'rateBranches', {rateBranches}, ...
    'rateInputBuffer', complex(zeros(0, 1)), ...
    'rateInputBufferStart', 0, ...
    'rateInputSamplesReceived', 0, ...
    'rateNextOutputIndex', 0, ...
    'rateMaxBranchLength', max(1, ceil(numel(rateNumerator) / up)), ...
    'rateConverterDelaySec', double(converterDelaySec), ...
    'frontendNumerator', b(:).', ...
    'frontendZi', complex(zeros(numel(b) - 1, 1)), ...
    'previousFilteredIq', complex(zeros(0, 1)), ...
    'dcAlpha', double(dcAlpha), ...
    'dcZi', 0, ...
    'dcEstimateLevels', 0, ...
    'pipelineDelaySamples', double(pipelineDelaySamples), ...
    'sourceOriginSample', sourceStart, ...
    'expectedSourceSample', sourceStart, ...
    'demodBuffer', zeros(0, 1), ...
    'demodBufferStart', uint64(1), ...
    'nextSearchSample', uint64(1), ...
    'demodSamplesProduced', uint64(0), ...
    'inputSamplesReceived', uint64(0), ...
    'resampledSamplesProduced', uint64(0), ...
    'feedCount', uint64(0), ...
    'maxDemodBufferSamples', uint64(0), ...
    'frameState', nxdn.frameDecoderInit(cfg, ...
        'RetainDiagnostics', p.Results.RetainDiagnostics), ...
    'finalized', false);
end

function [up, down] = rationalRate(inputRate, targetRate)
roundedInput = round(inputRate);
roundedTarget = round(targetRate);
if abs(inputRate - roundedInput) > 1e-6 || ...
        abs(targetRate - roundedTarget) > 1e-6
    error('nxdn:streamInit:NonIntegerRate', ...
        'Streaming NXDN currently requires integer sample rates.');
end
divisor = gcd(roundedInput, roundedTarget);
up = roundedTarget / divisor;
down = roundedInput / divisor;
end
