function [state, output] = streamFlush(state)
%STREAMFLUSH Drain causal frontend latency and finalize NXDN session state.
if state.finalized
    output = emptyOutput(state);
    return;
end
if isempty(state.sourceOriginSample)
    state.finalized = true;
    output = emptyOutput(state);
    return;
end

paddingCount = max(1, ceil((state.cfg.streamFlushPaddingSec + ...
    state.rateConverterDelaySec) * state.inputSampleRateHz));
padding = radio.stream.makeIqChunk( ...
    complex(zeros(paddingCount, 1)), state.inputSampleRateHz, ...
    state.expectedSourceSample, 'SequenceNumber', state.feedCount);
[state, drained] = nxdn.streamDecodeChunk(state, padding);
[state.frameState, finalPdus] = ...
    nxdn.frameDecoderFinalize(state.frameState);
finalSamples = pduSourceSamples(state, finalPdus);
pdus = appendPdus(drained.pdus, finalPdus);
sourceSamples = [drained.sourceSamples; finalSamples];
state.finalized = true;
report = nxdn.frameDecoderReport(state.frameState);
output = struct( ...
    'pdus', nxdn.postprocess(pdus), ...
    'sourceSamples', sourceSamples, ...
    'diagnostics', report, ...
    'frequencyOffsetHz', drained.frequencyOffsetHz, ...
    'timingState', drained.timingState, ...
    'nativeStreaming', true, ...
    'inputSampleCount', paddingCount, ...
    'resampledSampleCount', drained.resampledSampleCount, ...
    'demodulatedSampleCount', drained.demodulatedSampleCount, ...
    'elapsedSec', drained.elapsedSec);
end

function output = emptyOutput(state)
output = struct( ...
    'pdus', struct([]), ...
    'sourceSamples', zeros(0, 1, 'uint64'), ...
    'diagnostics', nxdn.frameDecoderReport(state.frameState), ...
    'frequencyOffsetHz', NaN, ...
    'timingState', struct(), ...
    'nativeStreaming', true, ...
    'inputSampleCount', 0, ...
    'resampledSampleCount', 0, ...
    'demodulatedSampleCount', 0, ...
    'elapsedSec', 0);
end

function samples = pduSourceSamples(state, pdus)
samples = zeros(numel(pdus), 1, 'uint64');
for k = 1:numel(pdus)
    targetSample = radio.getNestedField(pdus(k), 'extra.fs_start', []);
    if isempty(targetSample)
        targetSample = radio.getNestedField( ...
            pdus(k), 'extra.start_sample', 0);
    end
    targetOffset = max(0, double(targetSample) - 1);
    inputOffset = round(targetOffset * ...
        state.inputSampleRateHz / state.targetSampleRateHz);
    samples(k) = state.sourceOriginSample + uint64(max(0, inputOffset));
end
end

function out = appendPdus(arr, items)
if isempty(items)
    out = arr;
elseif isempty(arr)
    out = items;
else
    out = arr;
    out(end+1:end+numel(items)) = items;
end
end
