function source = fileLoopSourceInit(path, varargin)
%FILELOOPSOURCEINIT Initialize a finite or repeating pull-based IQ source.
p = inputParser;
p.addParameter('SampleRate', []);
p.addParameter('CenterFrequencyHz', []);
p.addParameter('IqDType', 'int16');
p.addParameter('HeaderBytes', []);
p.addParameter('ChunkDurationSec', 0.010);
p.addParameter('ChunkSamples', []);
p.addParameter('ReplayMode', 'once');
p.addParameter('MaxLoops', []);
p.addParameter('EpochSilenceSec', 0.400);
p.addParameter('ChannelId', 1);
p.parse(varargin{:});

metadata = radio.tuned.captureInfo(path, ...
    'SampleRate', p.Results.SampleRate, ...
    'CenterFrequencyHz', p.Results.CenterFrequencyHz, ...
    'IqDType', p.Results.IqDType, ...
    'HeaderBytes', p.Results.HeaderBytes);
mode = normalizeMode(p.Results.ReplayMode);
maxLoops = p.Results.MaxLoops;
if isempty(maxLoops)
    if strcmp(mode, 'once')
        maxLoops = 1;
    else
        maxLoops = inf;
    end
end
if ~(isscalar(maxLoops) && isreal(maxLoops) && maxLoops > 0 && ...
        (isinf(maxLoops) || (isfinite(maxLoops) && maxLoops == fix(maxLoops))))
    error('radio:replay:fileLoopSourceInit:MaxLoops', ...
        'MaxLoops must be a positive integer or Inf.');
end
if strcmp(mode, 'once') && maxLoops ~= 1
    error('radio:replay:fileLoopSourceInit:OnceLoops', ...
        'ReplayMode=once requires MaxLoops=1.');
end
validateattributes(p.Results.EpochSilenceSec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
if strcmp(mode, 'epoch-repeat') && p.Results.EpochSilenceSec <= 0
    error('radio:replay:fileLoopSourceInit:EpochSilence', ...
        'EpochSilenceSec must be positive in epoch-repeat mode.');
end

chunkSamples = p.Results.ChunkSamples;
if isempty(chunkSamples)
    validateattributes(p.Results.ChunkDurationSec, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
    chunkSamples = max(1, round( ...
        metadata.sampleRateHz * p.Results.ChunkDurationSec));
else
    validateattributes(chunkSamples, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive', 'integer'});
end

options = struct( ...
    'sampleRateHz', metadata.sampleRateHz, ...
    'centerFrequencyHz', metadata.centerFrequencyHz, ...
    'iqDType', char(p.Results.IqDType), ...
    'headerBytes', metadata.headerBytes, ...
    'chunkSamples', double(chunkSamples), ...
    'channelId', p.Results.ChannelId);
fileSource = openFileSource(char(path), options);
source = struct( ...
    'path', char(path), ...
    'metadata', metadata, ...
    'options', options, ...
    'fileSource', fileSource, ...
    'replayMode', mode, ...
    'maxLoops', double(maxLoops), ...
    'epochSilenceSec', double(p.Results.EpochSilenceSec), ...
    'epochSilenceSamples', uint64(ceil( ...
        p.Results.EpochSilenceSec * metadata.sampleRateHz)), ...
    'silenceSamplesRemaining', uint64(0), ...
    'globalNextSample', uint64(0), ...
    'nextSequenceNumber', uint64(0), ...
    'currentLoop', uint64(1), ...
    'completedLoops', uint64(0), ...
    'atLoopStart', true, ...
    'pendingLoopDiscontinuity', false, ...
    'terminal', false, ...
    'closed', false, ...
    'syntheticContinuousReplay', strcmp(mode, 'continuous-test'));
end

function fileSource = openFileSource(path, options)
fileSource = radio.stream.fileSourceInit(path, ...
    'SampleRateHz', options.sampleRateHz, ...
    'ChunkSamples', options.chunkSamples, ...
    'DType', options.iqDType, ...
    'HeaderBytes', options.headerBytes, ...
    'ChannelId', options.channelId, ...
    'CenterFrequencyHz', options.centerFrequencyHz);
end

function mode = normalizeMode(value)
mode = lower(strrep(char(value), '_', '-'));
switch mode
    case {'once', 'single'}
        mode = 'once';
    case {'continuous-test', 'continuous', 'loop'}
        mode = 'continuous-test';
    case {'epoch-repeat', 'epoch', 'independent-epochs'}
        mode = 'epoch-repeat';
    otherwise
        error('radio:replay:fileLoopSourceInit:ReplayMode', ...
            'ReplayMode must be once, continuous-test, or epoch-repeat.');
end
end
