function frame = frameInfoFromNid(nid)
%FRAMEINFOFROMNID Return P25 frame metadata.
defs = containers.Map('KeyType', 'double', 'ValueType', 'any');
defs(0) = {'P25_HDU', 'header', false, false, false, false};
defs(3) = {'P25_TDU', 'terminator', false, false, true, false};
defs(5) = {'P25_LDU1', 'voice', true, false, false, true};
defs(7) = {'P25_TSBK', 'trunking_control', false, true, false, false};
defs(10) = {'P25_LDU2', 'voice', true, false, false, false};
defs(12) = {'P25_PDU', 'packet_data', false, true, false, false};
defs(15) = {'P25_TDULC', 'terminator', false, false, true, true};
if isKey(defs, nid.duid)
    item = defs(nid.duid);
else
    item = {sprintf('P25_UNKNOWN_0x%X', nid.duid), 'unknown', false, false, false, false};
end
frame = struct( ...
    'nac', nid.nac, ...
    'duid', nid.duid, ...
    'duid_name', nid.duid_name, ...
    'pdu_type', item{1}, ...
    'category', item{2}, ...
    'is_voice', item{3}, ...
    'is_control', item{4}, ...
    'is_terminator', item{5}, ...
    'has_link_control', item{6});
end

