function state = frameDecoderInit(cfg)
%FRAMEDECODERINIT Initialize persistent P25 frame/session state.
if nargin < 1 || isempty(cfg), cfg = p25.config(); end
state = struct( ...
    'cfg', cfg, ...
    'session', p25.sessionInit(), ...
    'pendingInvalidRecords', struct([]), ...
    'hasValidBch', false, ...
    'candidateCount', uint64(0), ...
    'frameCount', uint64(0), ...
    'validFrameCount', uint64(0), ...
    'pduCount', uint64(0), ...
    'finalized', false);
end
