function report = frameDecoderReport(state)
%FRAMEDECODERREPORT Summarize persistent P25 frame state.
report = struct( ...
    'candidateCount', double(state.candidateCount), ...
    'frameCount', double(state.frameCount), ...
    'validFrameCount', double(state.validFrameCount), ...
    'pendingInvalidFrameCount', numel(state.pendingInvalidRecords), ...
    'pduCount', double(state.pduCount), ...
    'hasValidBch', logical(state.hasValidBch), ...
    'finalized', logical(state.finalized));
end
