function spec = spec()
%SPEC P25 ProtocolSpec-compatible adapter.
spec = struct( ...
    'name', 'P25', ...
    'aliases', {{'p25'}}, ...
    'config', p25.config(), ...
    'frontendFcn', @p25.frontend, ...
    'decodeFcn', @p25.decode, ...
    'postprocessFcn', @p25.postprocess, ...
    'dedupFcn', @p25.dedupKey, ...
    'formatterFcn', @p25.formatPdu, ...
    'targetSampleRateHz', 48000.0, ...
    'scanIqFcn', []);
end
