function state = streamInit(inputSampleRateHz, cfg, varargin)
%STREAMINIT Initialize a causal, persistent P25 Phase-1 IQ decoder.
if nargin < 2 || isempty(cfg), cfg = p25.config(); end
p = inputParser;
p.addParameter('SourceSampleStart', []);
p.parse(varargin{:});
validateattributes(inputSampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
if exist('fir1', 'file') ~= 2
    error('p25:streamInit:MissingToolbox', ...
        'fir1 is required for the streaming P25 frontend.');
end

inputRate = double(inputSampleRateHz);
targetRate = double(cfg.targetSampleRateHz);
[up, down] = rationalRate(inputRate, targetRate);
converter = [];
converterDelaySec = 0;
rateMode = 'none';
if up ~= down
    if exist('dsp.FIRRateConverter', 'class') ~= 8
        error('p25:streamInit:MissingRateConverter', ...
            'dsp.FIRRateConverter is required for streaming resampling.');
    end
    converter = dsp.FIRRateConverter(up, down, ...
        'AllowArbitraryInputLength', true);
    [converterDelaySec, ~] = outputDelay(converter, FsIn=inputRate);
    rateMode = 'system_object';
end

b = fir1(cfg.frontendTaps - 1, ...
    cfg.frontendCutoffHz / (targetRate / 2));
frontendDelaySamples = (numel(b) - 1) / 2;
pipelineDelaySamples = converterDelaySec * targetRate + ...
    frontendDelaySamples;
dcAlpha = 1 - exp(-1 / max(1, ...
    cfg.streamDcTimeConstantSec * targetRate));
sourceStart = p.Results.SourceSampleStart;
if ~isempty(sourceStart), sourceStart = uint64(sourceStart); end

state = struct( ...
    'cfg', cfg, ...
    'inputSampleRateHz', inputRate, ...
    'targetSampleRateHz', targetRate, ...
    'rateUp', double(up), ...
    'rateDown', double(down), ...
    'rateMode', rateMode, ...
    'rateConverter', converter, ...
    'rateConverterDelaySec', double(converterDelaySec), ...
    'coarseFrequencyOffsetHz', NaN, ...
    'coarseEstimateMinSamples', max(cfg.frontendMinSamples, ...
        round(cfg.streamFrequencyEstimateSec * targetRate)), ...
    'coarseBuffer', complex(zeros(0, 1)), ...
    'mixedSamplesProcessed', uint64(0), ...
    'frontendNumerator', b(:).', ...
    'frontendZi', complex(zeros(numel(b) - 1, 1)), ...
    'previousFilteredIq', complex(zeros(0, 1)), ...
    'dcAlpha', double(dcAlpha), ...
    'dcZi', 0, ...
    'dcEstimateLevels', 0, ...
    'pipelineDelaySamples', double(pipelineDelaySamples), ...
    'sourceOriginSample', sourceStart, ...
    'expectedSourceSample', sourceStart, ...
    'demodBuffer', zeros(0, 1), ...
    'demodBufferStart', uint64(0), ...
    'nextSearchSample', uint64(0), ...
    'demodSamplesProduced', uint64(0), ...
    'inputSamplesReceived', uint64(0), ...
    'resampledSamplesProduced', uint64(0), ...
    'feedCount', uint64(0), ...
    'maxDemodBufferSamples', uint64(0), ...
    'frameState', p25.frameDecoderInit(cfg), ...
    'finalized', false);
end

function [up, down] = rationalRate(inputRate, targetRate)
roundedInput = round(inputRate);
roundedTarget = round(targetRate);
if abs(inputRate - roundedInput) > 1e-6 || ...
        abs(targetRate - roundedTarget) > 1e-6
    error('p25:streamInit:NonIntegerRate', ...
        'Streaming P25 currently requires integer sample rates.');
end
divisor = gcd(roundedInput, roundedTarget);
up = roundedTarget / divisor;
down = roundedInput / divisor;
end
