function detector = activityDetectorInit(sampleRateHz, varargin)
%ACTIVITYDETECTORINIT Initialize the low-cost channel activity detector.
p = inputParser;
p.addParameter('Config', radio.stream.defaultConfig().activity);
p.parse(varargin{:});
cfg = p.Results.Config;

required = {'initialNoiseFloorDb', 'onMarginDb', 'offMarginDb', ...
    'minOnSec', 'offHangSec', 'noiseUpdateAlpha', 'minPowerDb'};
missing = required(~isfield(cfg, required));
if ~isempty(missing)
    error('radio:stream:activityDetectorInit:Config', ...
        'Activity configuration is missing field: %s', missing{1});
end
% Preserve compatibility with configurations saved before the adaptive
% estimator was introduced.  New estimator controls are optional additions;
% the established activity timing and hysteresis fields remain unchanged.
adaptiveDefaults = radio.stream.defaultConfig().activity;
optional = {'spectralNoiseEnabled', 'noiseFftLength', ...
    'noiseMaxSegments', 'noiseMinSamples'};
for k = 1:numel(optional)
    name = optional{k};
    if ~isfield(cfg, name)
        cfg.(name) = adaptiveDefaults.(name);
    end
end
if cfg.offMarginDb >= cfg.onMarginDb
    error('radio:stream:activityDetectorInit:Hysteresis', ...
        'offMarginDb must be lower than onMarginDb.');
end
validateattributes(sampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, 'sampleRateHz');
validateattributes(cfg.initialNoiseFloorDb, {'numeric'}, ...
    {'scalar', 'real'}, mfilename, 'initialNoiseFloorDb');
if ~(isnan(cfg.initialNoiseFloorDb) || isfinite(cfg.initialNoiseFloorDb))
    error('radio:stream:activityDetectorInit:InitialNoiseFloor', ...
        'initialNoiseFloorDb must be finite or NaN for automatic bootstrap.');
end
validateattributes(cfg.noiseUpdateAlpha, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0, '<=', 1}, ...
    mfilename, 'noiseUpdateAlpha');
validateattributes(cfg.spectralNoiseEnabled, {'logical', 'numeric'}, ...
    {'scalar'}, mfilename, 'spectralNoiseEnabled');
cfg.spectralNoiseEnabled = logical(cfg.spectralNoiseEnabled);
validateattributes(cfg.noiseFftLength, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', '>=', 16}, ...
    mfilename, 'noiseFftLength');
validateattributes(cfg.noiseMaxSegments, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'}, ...
    mfilename, 'noiseMaxSegments');
validateattributes(cfg.noiseMinSamples, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', '>=', 16}, ...
    mfilename, 'noiseMinSamples');

hasInitialNoiseFloor = isfinite(cfg.initialNoiseFloorDb);
initialNoiseFloorDb = double(cfg.initialNoiseFloorDb);
if ~hasInitialNoiseFloor
    initialNoiseFloorDb = double(cfg.minPowerDb);
end

detector = struct( ...
    'sampleRateHz', double(sampleRateHz), ...
    'config', cfg, ...
    'phase', 'inactive', ...
    'isActive', false, ...
    'noiseFloorDb', initialNoiseFloorDb, ...
    'noiseFloorInitialized', hasInitialNoiseFloor, ...
    'hasExternalNoisePrior', hasInitialNoiseFloor, ...
    'lastInstantaneousNoiseFloorDb', NaN, ...
    'lastSnrDb', 0.0, ...
    'lastPowerDb', double(cfg.minPowerDb), ...
    'onDurationSec', 0.0, ...
    'offDurationSec', 0.0, ...
    'candidateStartSample', uint64(0), ...
    'lastSampleEnd', uint64(0));
end
