function detector = activityDetectorInit(sampleRateHz, varargin)
%ACTIVITYDETECTORINIT Initialize the low-cost channel activity detector.
p = inputParser;
p.addParameter('Config', radio.stream.defaultConfig().activity);
p.parse(varargin{:});
cfg = p.Results.Config;

required = {'initialNoiseFloorDb', 'onMarginDb', 'offMarginDb', ...
    'minOnSec', 'offHangSec', 'noiseUpdateAlpha', 'minPowerDb'};
missing = required(~isfield(cfg, required));
if ~isempty(missing)
    error('radio:stream:activityDetectorInit:Config', ...
        'Activity configuration is missing field: %s', missing{1});
end
if cfg.offMarginDb >= cfg.onMarginDb
    error('radio:stream:activityDetectorInit:Hysteresis', ...
        'offMarginDb must be lower than onMarginDb.');
end

detector = struct( ...
    'sampleRateHz', double(sampleRateHz), ...
    'config', cfg, ...
    'phase', 'inactive', ...
    'isActive', false, ...
    'noiseFloorDb', double(cfg.initialNoiseFloorDb), ...
    'lastPowerDb', double(cfg.minPowerDb), ...
    'onDurationSec', 0.0, ...
    'offDurationSec', 0.0, ...
    'candidateStartSample', uint64(0), ...
    'lastSampleEnd', uint64(0));
end
