function controller = channelControllerInit(sampleRateHz, varargin)
%CHANNELCONTROLLERINIT Create the single-known-frequency stream controller.
p = inputParser;
p.addParameter('Config', radio.stream.defaultConfig());
p.addParameter('ChannelId', 1);
p.addParameter('CenterFrequencyHz', 0);
p.addParameter('NextEpochId', uint64(1));
p.addParameter('InitialGeneration', uint64(0));
p.parse(varargin{:});
cfg = p.Results.Config;

controller = struct( ...
    'state', 'NO_SIGNAL', ...
    'sampleRateHz', double(sampleRateHz), ...
    'channelId', p.Results.ChannelId, ...
    'centerFrequencyHz', double(p.Results.CenterFrequencyHz), ...
    'config', cfg, ...
    'ringBuffer', radio.stream.ringBufferInit( ...
        sampleRateHz, cfg.ringBufferSec, ...
        'ChannelId', p.Results.ChannelId, ...
        'CenterFrequencyHz', p.Results.CenterFrequencyHz), ...
    'activityDetector', radio.stream.activityDetectorInit( ...
        sampleRateHz, 'Config', cfg.activity), ...
    'currentEpoch', [], ...
    'lastClosedEpoch', [], ...
    'nextEpochId', uint64(p.Results.NextEpochId), ...
    'generation', uint64(p.Results.InitialGeneration), ...
    'transitionCount', uint64(0), ...
    'lastSampleEnd', uint64(0));
end
