function [state, result] = executeProbeTaskPacked( ...
        state, packedSnapshot, payload, probe, taskFcn, taskContext)
%EXECUTEPROBETASKPACKED Restore compact CI16 transport before probing.
snapshot = radio.stream.lockedDecoderActorUnpackChunk( ...
    packedSnapshot, payload);
[state, result] = radio.stream.executeProbeTask( ...
    state, snapshot, probe, taskFcn, taskContext);
end
