function state = incrementalDecoderInit(protocol, sampleRateHz, varargin)
%INCREMENTALDECODERINIT Initialize a bounded-history streaming adapter.
p = inputParser;
p.addParameter('DecodeFcn', []);
p.addParameter('HistorySec', []);
p.addParameter('MinAdvanceSec', []);
p.addParameter('MaxAdvanceSec', []);
p.parse(varargin{:});
protocol = radio.normalizeProtocolNames({protocol});
protocol = protocol{1};

[historySec, minAdvanceSec, maxAdvanceSec] = defaults(protocol);
if ~isempty(p.Results.HistorySec), historySec = p.Results.HistorySec; end
if ~isempty(p.Results.MinAdvanceSec)
    minAdvanceSec = p.Results.MinAdvanceSec;
end
if ~isempty(p.Results.MaxAdvanceSec)
    maxAdvanceSec = p.Results.MaxAdvanceSec;
end
validateattributes(sampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(historySec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(minAdvanceSec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(maxAdvanceSec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
if minAdvanceSec > maxAdvanceSec
    error('radio:stream:incrementalDecoderInit:AdvanceRange', ...
        'MinAdvanceSec cannot exceed MaxAdvanceSec.');
end

state = struct( ...
    'protocol', protocol, ...
    'sampleRateHz', double(sampleRateHz), ...
    'historySec', double(historySec), ...
    'historyCapacitySamples', max(1, ceil(historySec * sampleRateHz)), ...
    'minAdvanceSec', double(minAdvanceSec), ...
    'maxAdvanceSec', double(maxAdvanceSec), ...
    'historyIq', complex(zeros(0, 1, 'single')), ...
    'historyStartSample', uint64(0), ...
    'nextExpectedSample', [], ...
    'feedCount', uint64(0), ...
    'resetCount', uint64(0), ...
    'inputSampleCount', uint64(0), ...
    'decodeFcn', p.Results.DecodeFcn, ...
    'nativeStreaming', any(strcmp(protocol, ...
        {'DMR', 'P25', 'dPMR', 'NXDN', 'TETRA'})) && ...
        isempty(p.Results.DecodeFcn), ...
    'nativeProtocol', protocol, ...
    'nativeState', [], ...
    'nativeSeed', [], ...
    'lastDiagnostics', struct(), ...
    'lastFrequencyOffsetHz', NaN, ...
    'lastTimingState', struct());
end

function [historySec, minAdvanceSec, maxAdvanceSec] = defaults(protocol)
switch protocol
    case 'DMR'
        historySec = 1.50;
        minAdvanceSec = 0.25;
    case 'P25'
        historySec = 1.00;
        minAdvanceSec = 0.20;
    case 'dPMR'
        historySec = 1.50;
        minAdvanceSec = 0.25;
    case 'NXDN'
        % The native NXDN state machine needs only enough seed to recover
        % one four-frame SACCH superframe plus causal filter/sync state.
        % Keeping the former one-second compatibility window would add a
        % large one-time actor transfer without improving continuity.
        historySec = 0.25;
        minAdvanceSec = 0.20;
    case 'TETRA'
        historySec = 1.00;
        minAdvanceSec = 0.25;
    otherwise
        error('radio:stream:incrementalDecoderInit:Protocol', ...
            'Unsupported protocol: %s', protocol);
end
maxAdvanceSec = historySec;
end
