function handle = lockedDecoderStart(state, buffer, varargin)
%LOCKEDDECODERSTART Start one ordered locked-protocol decode pass.
p = inputParser;
p.addParameter('NumWorkers', 5);
p.parse(varargin{:});

handle = struct( ...
    'epochId', uint64(state.epochId), ...
    'generation', uint64(state.generation), ...
    'protocol', state.protocol, ...
    'mode', '', ...
    'future', [], ...
    'actor', [], ...
    'completed', false, ...
    'canceled', false, ...
    'decoderState', [], ...
    'output', [], ...
    'errorReason', '', ...
    'submitElapsedSec', 0, ...
    'pollElapsedSec', 0, ...
    'fetchElapsedSec', 0, ...
    'timerToken', tic, ...
    'elapsedSec', 0);

input = radio.stream.lockedDecoderPrepareInput(state, buffer);

% Keep the native NXDN causal state in one background worker at 120 kS/s;
% the process workers remain available for protocol races.
if nativeNxdnThreadEligible(state) && ...
        state.sampleRateHz == 120000 && isempty(state.actor)
    handle.mode = 'background_worker';
    submitToken = tic;
    handle.future = parfeval(backgroundPool, ...
        @radio.stream.lockedDecoderProcessChunk, 2, state, input);
    handle.submitElapsedSec = toc(submitToken);
    return;
end

[pool, info] = radio.stream.acquireParallelPool( ...
    'NumWorkers', p.Results.NumWorkers);
if isempty(pool)
    error('radio:stream:lockedDecoderStart:PoolUnavailable', ...
        'Parallel pool is unavailable: %s', info.reason);
end

handle.mode = 'parallel';
if radio.stream.lockedDecoderActorEligible(state)
    submitToken = tic;
    if isempty(state.actor)
        handle.actor = radio.stream.lockedDecoderActorStart( ...
            pool, state, input);
    else
        handle.actor = radio.stream.lockedDecoderActorSubmit( ...
            state.actor, input);
    end
    handle.submitElapsedSec = toc(submitToken);
    handle.mode = 'persistent_worker';
    handle.future = handle.actor.future;
    return;
end
submitToken = tic;
handle.future = parfeval(pool, @radio.stream.lockedDecoderProcessChunk, 2, ...
    state, input);
handle.submitElapsedSec = toc(submitToken);
end

function tf = nativeNxdnThreadEligible(state)
tf = strcmp(state.protocol, 'NXDN') && isempty(state.decodeFcn) && ...
    isfield(state, 'incremental') && ...
    isfield(state.incremental, 'nativeStreaming') && ...
    state.incremental.nativeStreaming && isfield(state, 'actor');
end
