function tf = lockedDecoderActorEligible(state)
%LOCKEDDECODERACTORELIGIBLE True for built-in process-actor decoders.
supported = {'DMR', 'P25', 'dPMR', 'NXDN', 'TETRA'};
tf = isstruct(state) && isfield(state, 'decodeFcn') && ...
    isempty(state.decodeFcn) && isfield(state, 'incremental') && ...
    isfield(state, 'actor') && isfield(state, 'protocol') && ...
    any(strcmp(state.protocol, supported));
end
