function [state, output] = lockedDecoderProcess(state, buffer)
%LOCKEDDECODERPROCESS Decode a bounded overlap window and emit unseen PDUs.
if buffer.sampleRateHz ~= state.sampleRateHz
    error('radio:stream:lockedDecoderProcess:SampleRate', ...
        'Decoder state and ring-buffer sample rates differ.');
end
if buffer.endSample <= state.lastProcessedEndSample
    output = emptyOutput(state, buffer.endSample, 'no_new_samples');
    return;
end

lookbackSamples = uint64(ceil(state.lookbackSec * state.sampleRateHz));
if buffer.endSample >= lookbackSamples
    desiredStart = buffer.endSample - lookbackSamples;
else
    desiredStart = uint64(0);
end
startSample = max(buffer.startSample, desiredStart);
snapshot = radio.stream.ringBufferRange(buffer, startSample, buffer.endSample);
timer = tic;
try
    if isempty(state.decodeFcn)
        [pdus, diagnostics, frequencyOffsetHz, timingState] = ...
            radio.stream.decodeProtocolWindow(state.protocol, snapshot);
    else
        [pdus, diagnostics, frequencyOffsetHz, timingState] = ...
            state.decodeFcn(state.protocol, snapshot);
    end
    pdus = radio.stream.stampStreamPdus( ...
        pdus, state.protocol, snapshot, state.epochId);
    verdict = radio.stream.evaluateProbeEvidence( ...
        state.protocol, pdus, diagnostics);
    [state, newPdus] = filterUnseen(state, pdus, startSample);
    errorReason = '';
catch ME
    pdus = struct([]);
    newPdus = struct([]);
    diagnostics = struct();
    frequencyOffsetHz = NaN;
    timingState = struct();
    verdict = struct('status', 'error', 'confidence', 0, ...
        'evidenceClass', '', 'evidence', struct(), ...
        'reason', sprintf('%s: %s', ME.identifier, ME.message));
    errorReason = verdict.reason;
end

state.decodeCount = state.decodeCount + uint64(1);
state.lastProcessedEndSample = buffer.endSample;
if strcmp(verdict.status, 'confirmed')
    state.consecutiveNoEvidence = 0;
    state.lastStrongEvidenceSample = buffer.endSample;
    state.status = 'healthy';
elseif strcmp(verdict.status, 'error')
    state.consecutiveNoEvidence = state.consecutiveNoEvidence + 1;
    state.status = 'error';
else
    state.consecutiveNoEvidence = state.consecutiveNoEvidence + 1;
    if state.consecutiveNoEvidence >= state.lostWindows
        state.status = 'lost';
    elseif state.consecutiveNoEvidence >= state.suspectWindows
        state.status = 'suspect';
    else
        state.status = 'no_evidence';
    end
end

output = struct( ...
    'protocol', state.protocol, ...
    'epochId', state.epochId, ...
    'generation', state.generation, ...
    'status', state.status, ...
    'windowStartSample', startSample, ...
    'windowEndSample', buffer.endSample, ...
    'newPdus', newPdus, ...
    'newPduCount', numel(newPdus), ...
    'windowPduCount', numel(pdus), ...
    'health', verdict, ...
    'consecutiveNoEvidence', state.consecutiveNoEvidence, ...
    'frequencyOffsetHz', frequencyOffsetHz, ...
    'timingState', timingState, ...
    'diagnostics', diagnostics, ...
    'elapsedSec', toc(timer), ...
    'errorReason', errorReason);
end

function [state, newPdus] = filterUnseen(state, pdus, retainedStartSample)
persistentMask = state.seenSamples == intmax('uint64');
keepMask = persistentMask | state.seenSamples >= retainedStartSample;
state.seenSamples = state.seenSamples(keepMask);
state.seenKeys = state.seenKeys(keepMask);
newPdus = struct([]);
for k = 1:numel(pdus)
    [key, isPersistent] = radio.stream.streamPduKey(pdus(k), state.sampleRateHz);
    if any(strcmp(state.seenKeys, key))
        continue;
    end
    state.seenKeys{end+1, 1} = key;
    if isPersistent
        state.seenSamples(end+1, 1) = intmax('uint64');
    else
        state.seenSamples(end+1, 1) = radio.getNestedField( ...
            pdus(k), 'extra.stream.source_sample', uint64(0));
    end
    if isempty(newPdus)
        newPdus = pdus(k);
    else
        newPdus(end+1) = pdus(k); %#ok<AGROW>
    end
end
end

function output = emptyOutput(state, endSample, reason)
output = struct( ...
    'protocol', state.protocol, ...
    'epochId', state.epochId, ...
    'generation', state.generation, ...
    'status', state.status, ...
    'windowStartSample', endSample, ...
    'windowEndSample', endSample, ...
    'newPdus', struct([]), ...
    'newPduCount', 0, ...
    'windowPduCount', 0, ...
    'health', struct(), ...
    'consecutiveNoEvidence', state.consecutiveNoEvidence, ...
    'frequencyOffsetHz', NaN, ...
    'timingState', struct(), ...
    'diagnostics', struct(), ...
    'elapsedSec', 0, ...
    'errorReason', reason);
end
