function handle = lockedDecoderStart(state, buffer, varargin)
%LOCKEDDECODERSTART Start one ordered locked-protocol decode pass.
p = inputParser;
p.addParameter('Mode', 'auto');
p.addParameter('NumWorkers', 5);
p.addParameter('PoolType', 'auto');
p.parse(varargin{:});

handle = struct( ...
    'epochId', uint64(state.epochId), ...
    'generation', uint64(state.generation), ...
    'protocol', state.protocol, ...
    'mode', '', ...
    'future', [], ...
    'completed', false, ...
    'canceled', false, ...
    'decoderState', [], ...
    'output', [], ...
    'errorReason', '', ...
    'fallbackReason', '', ...
    'timerToken', tic, ...
    'elapsedSec', 0);

mode = lower(char(p.Results.Mode));
if strcmp(mode, 'serial')
    handle.mode = 'serial';
    [handle.decoderState, handle.output] = ...
        radio.stream.lockedDecoderProcess(state, buffer);
    handle.completed = true;
    handle.elapsedSec = toc(handle.timerToken);
    return;
end
if ~any(strcmp(mode, {'auto', 'parallel'}))
    error('radio:stream:lockedDecoderStart:Mode', ...
        'Mode must be auto, parallel, or serial.');
end

[pool, info] = radio.stream.acquireParallelPool( ...
    'NumWorkers', p.Results.NumWorkers, 'PoolType', p.Results.PoolType);
if isempty(pool)
    handle.mode = 'serial_fallback';
    handle.fallbackReason = info.reason;
    [handle.decoderState, handle.output] = ...
        radio.stream.lockedDecoderProcess(state, buffer);
    handle.completed = true;
    handle.elapsedSec = toc(handle.timerToken);
    return;
end

handle.mode = 'parallel';
handle.future = parfeval(pool, @radio.stream.lockedDecoderProcess, 2, ...
    state, buffer);
end
