function [state, output] = lockedDecoderProcessChunk(state, input)
%LOCKEDDECODERPROCESSCHUNK Decode compact incremental input on one worker.
if input.overrunSamples > 0
    state.consecutiveNoEvidence = state.consecutiveNoEvidence + 1;
    state.status = 'error';
    output = emptyOutput(state, input.availableEndSample, ...
        'locked_decoder_input_overrun');
    output.overrunSamples = input.overrunSamples;
    return;
end
if isempty(input.chunk)
    output = emptyOutput(state, input.availableEndSample, 'no_new_samples');
    return;
end

timer = tic;
try
    [state.incremental, decoded] = ...
        radio.stream.incrementalDecoderFeed( ...
            state.incremental, input.chunk);
    snapshot = decoded.snapshot;
    if isfield(decoded, 'nativeStreaming') && decoded.nativeStreaming
        pdus = radio.stream.stampStreamPdusAtSamples( ...
            decoded.pdus, state.protocol, decoded.sourceSamples, ...
            snapshot, state.epochId);
    else
        pdus = radio.stream.stampStreamPdus( ...
            decoded.pdus, state.protocol, snapshot, state.epochId);
    end
    verdict = radio.stream.evaluateProbeEvidence( ...
        state.protocol, pdus, decoded.diagnostics);
    [state, newPdus] = radio.stream.lockedDecoderFilterUnseen( ...
        state, pdus, snapshot.sourceSampleStart);
    diagnostics = decoded.diagnostics;
    frequencyOffsetHz = decoded.frequencyOffsetHz;
    timingState = decoded.timingState;
    startSample = snapshot.sourceSampleStart;
    historySampleCount = decoded.historySampleCount;
    errorReason = '';
catch ME
    pdus = struct([]);
    newPdus = struct([]);
    diagnostics = struct();
    frequencyOffsetHz = NaN;
    timingState = struct();
    startSample = input.chunk.sourceSampleStart;
    historySampleCount = numel(state.incremental.historyIq);
    verdict = struct('status', 'error', 'confidence', 0, ...
        'evidenceClass', '', 'evidence', struct(), ...
        'reason', sprintf('%s: %s', ME.identifier, ME.message));
    errorReason = verdict.reason;
end

state.decodeCount = state.decodeCount + uint64(1);
state.lastProcessedEndSample = input.targetEndSample;
if strcmp(verdict.status, 'confirmed')
    state.consecutiveNoEvidence = 0;
    state.lastStrongEvidenceSample = input.targetEndSample;
    state.status = 'healthy';
elseif strcmp(verdict.status, 'error')
    state.consecutiveNoEvidence = state.consecutiveNoEvidence + 1;
    state.status = 'error';
else
    state.consecutiveNoEvidence = state.consecutiveNoEvidence + 1;
    if state.consecutiveNoEvidence >= state.lostWindows
        state.status = 'lost';
    elseif state.consecutiveNoEvidence >= state.suspectWindows
        state.status = 'suspect';
    else
        state.status = 'no_evidence';
    end
end

output = struct( ...
    'protocol', state.protocol, ...
    'epochId', state.epochId, ...
    'generation', state.generation, ...
    'status', state.status, ...
    'windowStartSample', startSample, ...
    'windowEndSample', input.targetEndSample, ...
    'inputStartSample', input.chunk.sourceSampleStart, ...
    'inputEndSample', input.chunk.sourceSampleEnd, ...
    'availableEndSample', input.availableEndSample, ...
    'backlogSamples', input.availableEndSample - input.targetEndSample, ...
    'overrunSamples', uint64(0), ...
    'newPdus', newPdus, ...
    'newPduCount', numel(newPdus), ...
    'windowPduCount', numel(pdus), ...
    'health', verdict, ...
    'consecutiveNoEvidence', state.consecutiveNoEvidence, ...
    'frequencyOffsetHz', frequencyOffsetHz, ...
    'timingState', timingState, ...
    'diagnostics', diagnostics, ...
    'incremental', true, ...
    'newInputSampleCount', numel(input.chunk.iq), ...
    'historySampleCount', historySampleCount, ...
    'elapsedSec', toc(timer), ...
    'errorReason', errorReason);
end

function output = emptyOutput(state, endSample, reason)
output = struct( ...
    'protocol', state.protocol, ...
    'epochId', state.epochId, ...
    'generation', state.generation, ...
    'status', state.status, ...
    'windowStartSample', endSample, ...
    'windowEndSample', endSample, ...
    'inputStartSample', endSample, ...
    'inputEndSample', endSample, ...
    'availableEndSample', endSample, ...
    'backlogSamples', uint64(0), ...
    'overrunSamples', uint64(0), ...
    'newPdus', struct([]), ...
    'newPduCount', 0, ...
    'windowPduCount', 0, ...
    'health', struct(), ...
    'consecutiveNoEvidence', state.consecutiveNoEvidence, ...
    'frequencyOffsetHz', NaN, ...
    'timingState', struct(), ...
    'diagnostics', struct(), ...
    'incremental', true, ...
    'newInputSampleCount', 0, ...
    'historySampleCount', numel(state.incremental.historyIq), ...
    'elapsedSec', 0, ...
    'errorReason', reason);
end
