function state = lockedDecoderInit(protocol, epoch, sampleRateHz, varargin)
%LOCKEDDECODERINIT Initialize continuous locked-protocol output state.
p = inputParser;
p.addParameter('InitialPdus', struct([]));
p.addParameter('LastProcessedEndSample', uint64(epoch.candidateStartSample));
p.addParameter('DecodeFcn', []);
p.addParameter('SuspectWindows', 3);
p.addParameter('LostWindows', 6);
p.parse(varargin{:});
protocol = radio.normalizeProtocolNames({protocol});
protocol = protocol{1};
probe = radio.stream.probeRegistry({protocol});

state = struct( ...
    'protocol', protocol, ...
    'epochId', uint64(epoch.epochId), ...
    'generation', uint64(epoch.generation), ...
    'sampleRateHz', double(sampleRateHz), ...
    'lookbackSec', double(probe.maxWindowSec), ...
    'lastProcessedEndSample', uint64(p.Results.LastProcessedEndSample), ...
    'lastStrongEvidenceSample', uint64(0), ...
    'decodeCount', uint64(0), ...
    'consecutiveNoEvidence', 0, ...
    'suspectWindows', double(p.Results.SuspectWindows), ...
    'lostWindows', double(p.Results.LostWindows), ...
    'seenKeys', {cell(0, 1)}, ...
    'seenSamples', zeros(0, 1, 'uint64'), ...
    'decodeFcn', p.Results.DecodeFcn, ...
    'status', 'initialized');

pdus = radio.normalizePdus(p.Results.InitialPdus);
for k = 1:numel(pdus)
    [key, isPersistent] = radio.stream.streamPduKey(pdus(k), sampleRateHz);
    state.seenKeys{end+1, 1} = key;
    if isPersistent
        state.seenSamples(end+1, 1) = intmax('uint64');
    else
        state.seenSamples(end+1, 1) = radio.getNestedField( ...
            pdus(k), 'extra.stream.source_sample', uint64(0));
    end
end
end
