function actor = lockedDecoderActorStart(pool, state, input)
%LOCKEDDECODERACTORSTART Start one long-lived ordered decoder worker.
if isempty(pool)
    error('radio:stream:lockedDecoderActorStart:Pool', ...
        'A process pool is required for a persistent decoder actor.');
end
persistent nextActorId
if isempty(nextActorId), nextActorId = uint64(1); end
actorId = nextActorId;
nextActorId = nextActorId + uint64(1);
outputQueue = parallel.pool.PollableDataQueue;
if isfield(state, 'actor'), state.actor = []; end
seedPayload = [];
if isfield(state, 'incremental') && ...
        isfield(state.incremental, 'nativeSeed') && ...
        isstruct(state.incremental.nativeSeed)
    [state.incremental.nativeSeed, seedPayload] = ...
        radio.stream.lockedDecoderActorPackChunk( ...
            state.incremental.nativeSeed);
end
[packedInput, inputPayload] = ...
    radio.stream.lockedDecoderActorPackInput(input);
packedInput.actorIq = inputPayload;
if ~isempty(seedPayload), packedInput.actorSeedIq = seedPayload; end
future = parfeval(pool, @radio.stream.lockedDecoderActorWorker, 0, ...
    state, outputQueue, actorId);
actor = struct( ...
    'actorId', actorId, ...
    'future', future, ...
    'outputQueue', outputQueue, ...
    'inputQueue', [], ...
    'ready', false, ...
    'stopped', false, ...
    'failed', false, ...
    'requestId', uint64(1), ...
    'requestInFlight', true, ...
    'requestSent', false, ...
    'pendingInput', packedInput, ...
    'workerTaskId', 0, ...
    'errorReason', '', ...
    'startToken', tic);
end
