function chunk = makeIqChunk(iq, sampleRateHz, sourceSampleStart, varargin)
%MAKEIQCHUNK Construct one streaming IQ block on an absolute timeline.
% Sample positions are zero-based. sourceSampleEnd is end-exclusive.
p = inputParser;
p.addParameter('ChannelId', 1);
p.addParameter('SequenceNumber', uint64(0));
p.addParameter('TimestampStartNs', []);
p.addParameter('CenterFrequencyHz', 0);
p.addParameter('Discontinuity', false);
p.addParameter('DroppedSourceSamples', uint64(0));
p.parse(varargin{:});

validateattributes(sampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, 'sampleRateHz');
validateattributes(sourceSampleStart, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative', 'integer'}, ...
    mfilename, 'sourceSampleStart');
if ~isvector(iq) && ~isempty(iq)
    error('radio:stream:makeIqChunk:IqShape', 'IQ data must be a vector.');
end

sourceSampleStart = uint64(sourceSampleStart);
sampleCount = uint64(numel(iq));
timestampStartNs = p.Results.TimestampStartNs;
if isempty(timestampStartNs)
    timestampStartNs = uint64(round(1e9 * double(sourceSampleStart) / ...
        double(sampleRateHz)));
end

chunk = struct( ...
    'channelId', p.Results.ChannelId, ...
    'sequenceNumber', uint64(p.Results.SequenceNumber), ...
    'sourceSampleStart', sourceSampleStart, ...
    'sourceSampleEnd', sourceSampleStart + sampleCount, ...
    'timestampStartNs', uint64(timestampStartNs), ...
    'centerFrequencyHz', double(p.Results.CenterFrequencyHz), ...
    'sampleRateHz', double(sampleRateHz), ...
    'iq', iq(:), ...
    'discontinuity', logical(p.Results.Discontinuity), ...
    'droppedSourceSamples', uint64(p.Results.DroppedSourceSamples));

radio.stream.validateIqChunk(chunk);
end
