function result = makeProbeResult(state, status, snapshot, varargin)
%MAKEPROBERESULT Construct a uniform protocol identification result.
p = inputParser;
p.addParameter('Confidence', 0.0);
p.addParameter('EvidenceClass', '');
p.addParameter('Evidence', struct());
p.addParameter('ConsumedSamples', uint64(numel(snapshot.iq)));
p.addParameter('FrequencyOffsetHz', 0.0);
p.addParameter('TimingState', struct());
p.addParameter('DecoderCheckpoint', struct());
p.addParameter('ElapsedSec', 0.0);
p.addParameter('Reason', '');
p.addParameter('PduCount', 0);
p.addParameter('Pdus', struct([]));
p.parse(varargin{:});

result = struct( ...
    'epochId', uint64(state.epochId), ...
    'generation', uint64(state.generation), ...
    'protocol', state.protocol, ...
    'status', char(status), ...
    'confidence', double(p.Results.Confidence), ...
    'evidenceClass', char(p.Results.EvidenceClass), ...
    'evidence', p.Results.Evidence, ...
    'windowStartSample', uint64(snapshot.sourceSampleStart), ...
    'windowEndSample', uint64(snapshot.sourceSampleEnd), ...
    'consumedSamples', uint64(p.Results.ConsumedSamples), ...
    'frequencyOffsetHz', double(p.Results.FrequencyOffsetHz), ...
    'timingState', p.Results.TimingState, ...
    'decoderCheckpoint', p.Results.DecoderCheckpoint, ...
    'elapsedSec', double(p.Results.ElapsedSec), ...
    'reason', char(p.Results.Reason), ...
    'pduCount', double(p.Results.PduCount), ...
    'pdus', p.Results.Pdus);
end
