function epoch = newEpoch(channelId, epochId, generation, candidateStartSample)
%NEWEPOCH Create a protocol epoch before a protocol has been confirmed.
epoch = struct( ...
    'channelId', channelId, ...
    'epochId', uint64(epochId), ...
    'generation', uint64(generation), ...
    'state', 'CLASSIFYING', ...
    'protocol', '', ...
    'candidateStartSample', uint64(candidateStartSample), ...
    'decodeStartSample', uint64(candidateStartSample), ...
    'lockSample', uint64(0), ...
    'lastGoodSample', uint64(0), ...
    'endSample', uint64(0), ...
    'confidence', 0.0, ...
    'crcPassRatio', 0.0, ...
    'meanSyncScore', 0.0, ...
    'frequencyOffsetHz', 0.0, ...
    'frequencyDriftHzPerSec', 0.0, ...
    'timingDrift', 0.0, ...
    'consecutiveInvalidFrames', 0, ...
    'status', 'classifying', ...
    'outcome', 'classifying', ...
    'closeReason', '', ...
    'ambiguousInterval', uint64(zeros(0, 2)), ...
    'classificationStartSample', uint64(0), ...
    'classificationEndSample', uint64(0), ...
    'classificationElapsedSec', 0.0, ...
    'decodeElapsedSec', 0.0, ...
    'executionMode', '', ...
    'fallbackReason', '', ...
    'pduStartIndex', uint64(0), ...
    'pduEndIndex', uint64(0), ...
    'pduCount', 0, ...
    'classificationReport', []);
end
