function epoch = newEpoch(channelId, epochId, generation, candidateStartSample)
%NEWEPOCH Create a protocol epoch before a protocol has been confirmed.
epoch = struct( ...
    'channelId', channelId, ...
    'epochId', uint64(epochId), ...
    'generation', uint64(generation), ...
    'state', 'CLASSIFYING', ...
    'protocol', '', ...
    'candidateStartSample', uint64(candidateStartSample), ...
    'endSample', uint64(0), ...
    'crcPassRatio', 0.0, ...
    'meanSyncScore', 0.0, ...
    'frequencyOffsetHz', 0.0, ...
    'frequencyDriftHzPerSec', 0.0, ...
    'timingDrift', 0.0, ...
    'consecutiveInvalidFrames', 0, ...
    'status', 'classifying', ...
    'closeReason', '');
end
