function [handle, status] = parallelProbeRacePoll(handle)
%PARALLELPROBERACEPOLL Collect completed futures without blocking acquisition.
if handle.completed
    status = handle.race;
    return;
end
for k = 1:numel(handle.futures)
    if ~handle.submitted(k) || handle.collected(k)
        continue;
    end
    future = handle.futures{k};
    if ~strcmp(char(future.State), 'finished')
        continue;
    end
    try
        [newState, result] = fetchOutputs(future);
        accepted = result.epochId == handle.epochId && ...
            result.generation == handle.generation && ...
            newState.epochId == handle.epochId && ...
            newState.generation == handle.generation && ...
            strcmp(result.protocol, handle.registry(k).name) && ...
            strcmp(newState.protocol, handle.registry(k).name);
        if accepted
            handle.states(k) = newState;
            handle.results(k) = result;
        else
            handle.staleResultCount = handle.staleResultCount + 1;
            handle.results(k) = radio.stream.makeProbeResult( ...
                handle.states(k), 'error', handle.snapshot, ...
                'Reason', 'stale_or_mismatched_worker_result_ignored');
        end
    catch ME
        handle.taskErrorCount = handle.taskErrorCount + 1;
        handle.results(k) = radio.stream.makeProbeResult( ...
            handle.states(k), 'error', handle.snapshot, ...
            'Reason', sprintf('%s: %s', ME.identifier, ME.message));
    end
    handle.collected(k) = true;
end

if all(handle.collected)
    handle.completed = true;
    handle.elapsedSec = toc(handle.timerToken);
    handle.race = radio.stream.summarizeProbeResults( ...
        handle.results, handle.epochId, handle.generation);
    handle.race.executionMode = handle.executionMode;
    handle.race.elapsedSec = handle.elapsedSec;
    handle.race.staleResultCount = handle.staleResultCount;
    handle.race.taskErrorCount = handle.taskErrorCount;
    handle.race.canceled = handle.canceled;
    handle.race.fallbackReason = handle.fallbackReason;
    status = handle.race;
else
    status = progressStatus(handle, false);
end
end

function status = progressStatus(handle, timedOut)
status = struct( ...
    'epochId', handle.epochId, ...
    'generation', handle.generation, ...
    'outcome', 'running', ...
    'winner', [], ...
    'confirmedProtocols', {{}}, ...
    'results', handle.results, ...
    'executionMode', handle.executionMode, ...
    'elapsedSec', toc(handle.timerToken), ...
    'staleResultCount', handle.staleResultCount, ...
    'taskErrorCount', handle.taskErrorCount, ...
    'canceled', handle.canceled, ...
    'timedOut', timedOut, ...
    'submittedCount', nnz(handle.submitted), ...
    'collectedCount', nnz(handle.collected));
end
