function state = probeStateInit(probe, epochId, generation, candidateStartSample)
%PROBESTATEINIT Create scheduler state for one protocol probe.
state = struct( ...
    'protocol', probe.name, ...
    'epochId', uint64(epochId), ...
    'generation', uint64(generation), ...
    'candidateStartSample', uint64(candidateStartSample), ...
    'status', 'pending', ...
    'attemptCount', uint32(0), ...
    'lastAttemptedEndSample', uint64(candidateStartSample), ...
    'nextWindowSec', double(probe.initialWindowSec), ...
    'lastResult', []);
end
