function probes = probeRegistry(protocolNames)
%PROBEREGISTRY Return protocol probe timing and dispatch metadata.
probes = [ ...
    makeProbe('DMR',   0.30, 1.50, 48000), ...
    makeProbe('P25',   0.10, 1.00, 48000), ...
    makeProbe('dPMR',  0.32, 1.50, 48000), ...
    makeProbe('NXDN',  0.16, 1.00, 48000), ...
    makeProbe('TETRA', 0.50, 6.00, 72000)];

if nargin < 1 || isempty(protocolNames)
    return;
end
normalized = radio.normalizeProtocolNames(protocolNames);
probes = probes(ismember({probes.name}, normalized));
end

function probe = makeProbe(name, initialWindowSec, maxWindowSec, targetSampleRateHz)
probe = struct( ...
    'name', name, ...
    'initialWindowSec', initialWindowSec, ...
    'maxWindowSec', maxWindowSec, ...
    'targetSampleRateHz', targetSampleRateHz, ...
    'windowGrowthFactor', 2.0);
end
