function coordinator = raceCoordinatorInit(sampleRateHz, varargin)
%RACECOORDINATORINIT Join activity, protocol race, and winner catch-up.
p = inputParser;
p.addParameter('Config', radio.stream.defaultConfig());
p.addParameter('ChannelId', 1);
p.addParameter('CenterFrequencyHz', 0);
p.addParameter('ProtocolNames', {});
p.addParameter('Mode', 'auto');
p.addParameter('NumWorkers', 5);
p.addParameter('PoolType', 'auto');
p.addParameter('TaskFcn', []);
p.addParameter('TaskContext', struct());
p.addParameter('LockedDecodeFcn', []);
p.addParameter('Deduplicate', true);
p.parse(varargin{:});

registry = radio.stream.probeRegistry(p.Results.ProtocolNames);
coordinator = struct( ...
    'state', 'NO_SIGNAL', ...
    'channelController', radio.stream.channelControllerInit( ...
        sampleRateHz, 'Config', p.Results.Config, ...
        'ChannelId', p.Results.ChannelId, ...
        'CenterFrequencyHz', p.Results.CenterFrequencyHz), ...
    'registry', registry, ...
    'probeStates', [], ...
    'activeRace', [], ...
    'activeCatchup', [], ...
    'activeDecode', [], ...
    'lastRace', [], ...
    'lastCatchup', [], ...
    'decoderState', [], ...
    'lastDecoderOutput', [], ...
    'closedEpochs', repmat(radio.stream.newEpoch( ...
        p.Results.ChannelId, 0, 0, 0), 0, 1), ...
    'lastReportedClosedEpochId', uint64(0), ...
    'previousProtocol', '', ...
    'selectedProtocol', '', ...
    'currentEpochId', uint64(0), ...
    'currentGeneration', uint64(0), ...
    'reclassificationStartSample', uint64(0), ...
    'catchupPassCount', 0, ...
    'options', struct( ...
        'mode', char(p.Results.Mode), ...
        'numWorkers', p.Results.NumWorkers, ...
        'poolType', char(p.Results.PoolType), ...
        'taskFcn', p.Results.TaskFcn, ...
        'taskContext', p.Results.TaskContext, ...
        'lockedDecodeFcn', p.Results.LockedDecodeFcn, ...
        'deduplicate', logical(p.Results.Deduplicate), ...
        'lockedSuspectWindows', p.Results.Config.lockedSuspectWindows, ...
        'lockedLostWindows', p.Results.Config.lockedLostWindows, ...
        'preTriggerSec', p.Results.Config.preTriggerSec));
end
