function coordinator = raceCoordinatorInit(sampleRateHz, varargin)
%RACECOORDINATORINIT Join activity, protocol race, and winner catch-up.
p = inputParser;
p.addParameter('Config', radio.stream.defaultConfig());
p.addParameter('ChannelId', 1);
p.addParameter('CenterFrequencyHz', 0);
p.addParameter('ProtocolNames', {});
p.addParameter('NumWorkers', 5);
p.addParameter('TaskFcn', []);
p.addParameter('TaskContext', struct());
p.addParameter('LockedDecodeFcn', []);
p.addParameter('Deduplicate', true);
p.addParameter('ProbeMaxInFlight', []);
p.addParameter('EarlyProbeConfirm', false);
p.addParameter('EarlyProbeConfirmMinConfidence', 0.99);
p.addParameter('CandidateGateEnabled', false);
p.addParameter('CandidateGateStableDecisions', 2);
p.parse(varargin{:});

probeMaxInFlight = p.Results.ProbeMaxInFlight;
if isempty(probeMaxInFlight)
    probeMaxInFlight = p.Results.NumWorkers;
end
validateattributes(probeMaxInFlight, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'}, mfilename, ...
    'ProbeMaxInFlight');
validateattributes(p.Results.CandidateGateStableDecisions, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'}, mfilename, ...
    'CandidateGateStableDecisions');

registry = radio.stream.probeRegistry(p.Results.ProtocolNames);
coordinator = struct( ...
    'state', 'NO_SIGNAL', ...
    'channelController', radio.stream.channelControllerInit( ...
        sampleRateHz, 'Config', p.Results.Config, ...
        'ChannelId', p.Results.ChannelId, ...
        'CenterFrequencyHz', p.Results.CenterFrequencyHz), ...
    'registry', registry, ...
    'probeStates', [], ...
    'activeRace', [], ...
    'activeCatchup', [], ...
    'activeDecode', [], ...
    'lastRace', [], ...
    'lastCandidateGate', [], ...
    'candidateFamily', '', ...
    'candidateFamilyProposal', '', ...
    'candidateFamilyProposalCount', 0, ...
    'lastCatchup', [], ...
    'decoderState', [], ...
    'lastDecoderOutput', [], ...
    'deferLockedDecode', false, ...
    'deferProbeStart', false, ...
    'closedEpochs', repmat(radio.stream.newEpoch( ...
        p.Results.ChannelId, 0, 0, 0), 0, 1), ...
    'lastReportedClosedEpochId', uint64(0), ...
    'previousProtocol', '', ...
    'selectedProtocol', '', ...
    'currentEpochId', uint64(0), ...
    'currentGeneration', uint64(0), ...
    'reclassificationStartSample', uint64(0), ...
    'catchupPassCount', 0, ...
    'options', struct( ...
        'numWorkers', p.Results.NumWorkers, ...
        'taskFcn', p.Results.TaskFcn, ...
        'taskContext', p.Results.TaskContext, ...
        'lockedDecodeFcn', p.Results.LockedDecodeFcn, ...
        'deduplicate', logical(p.Results.Deduplicate), ...
        'probeMaxInFlight', double(probeMaxInFlight), ...
        'earlyProbeConfirm', logical(p.Results.EarlyProbeConfirm), ...
        'earlyProbeConfirmMinConfidence', ...
            double(p.Results.EarlyProbeConfirmMinConfidence), ...
        'candidateGateEnabled', logical(p.Results.CandidateGateEnabled), ...
        'candidateGateStableDecisions', ...
            double(p.Results.CandidateGateStableDecisions), ...
        'lockedSuspectWindows', p.Results.Config.lockedSuspectWindows, ...
        'lockedLostWindows', p.Results.Config.lockedLostWindows, ...
        'preTriggerSec', p.Results.Config.preTriggerSec));
end
