function [coordinator, output] = raceCoordinatorFeed(coordinator, chunk)
%RACECOORDINATORFEED Advance known-frequency identification without IQ loss.
coordinator.lastDecoderOutput = [];
[coordinator.channelController, channelOutput] = ...
    radio.stream.channelControllerFeed(coordinator.channelController, chunk);
events = emptyEvents();

if channelOutput.bufferEvent.reset
    [coordinator, events] = cancelActive(coordinator, events, ...
        chunk.sourceSampleStart, 'input_discontinuity');
end

channelState = coordinator.channelController.state;
if strcmp(channelState, 'NO_SIGNAL')
    [coordinator, events] = cancelActive(coordinator, events, ...
        chunk.sourceSampleEnd, 'signal_ended');
    if ~strcmp(coordinator.state, 'NO_SIGNAL')
        events(end+1) = makeEvent('COORDINATOR_STATE', coordinator.state, ...
            'NO_SIGNAL', chunk.sourceSampleEnd, '', 'signal_ended'); %#ok<AGROW>
    end
    coordinator = clearEpoch(coordinator);
    output = makeOutput(coordinator, channelOutput, events, [], []);
    return;
end

if strcmp(channelState, 'ACTIVITY_PENDING')
    if strcmp(coordinator.state, 'NO_SIGNAL')
        events(end+1) = makeEvent('COORDINATOR_STATE', 'NO_SIGNAL', ...
            'ACTIVITY_PENDING', chunk.sourceSampleEnd, '', ...
            'activity_pending'); %#ok<AGROW>
        coordinator.state = 'ACTIVITY_PENDING';
    end
    output = makeOutput(coordinator, channelOutput, events, [], []);
    return;
end

epoch = coordinator.channelController.currentEpoch;
if isempty(epoch)
    error('radio:stream:raceCoordinatorFeed:Epoch', ...
        'CLASSIFYING channel state does not have an active epoch.');
end
if coordinator.currentEpochId ~= epoch.epochId || ...
        coordinator.currentGeneration ~= epoch.generation
    [coordinator, events] = cancelActive(coordinator, events, ...
        chunk.sourceSampleStart, 'new_epoch');
    oldState = coordinator.state;
    coordinator.state = 'CLASSIFYING';
    coordinator.currentEpochId = epoch.epochId;
    coordinator.currentGeneration = epoch.generation;
    coordinator.probeStates = [];
    coordinator.selectedProtocol = '';
    coordinator.lastRace = [];
    coordinator.lastCatchup = [];
    coordinator.decoderState = [];
    coordinator.catchupPassCount = 0;
    events(end+1) = makeEvent('COORDINATOR_STATE', oldState, ...
        'CLASSIFYING', chunk.sourceSampleEnd, '', 'epoch_started'); %#ok<AGROW>
end

raceStatus = [];
catchupStatus = [];
if ~isempty(coordinator.activeRace)
    [coordinator.activeRace, raceStatus] = ...
        radio.stream.parallelProbeRacePoll(coordinator.activeRace);
    if coordinator.activeRace.completed
        [coordinator, events] = finishRace( ...
            coordinator, events, raceStatus, chunk.sourceSampleEnd);
    end
end

if strcmp(coordinator.state, 'CLASSIFYING') && isempty(coordinator.activeRace)
    buffer = coordinator.channelController.ringBuffer;
    snapshotStart = max(buffer.startSample, epoch.candidateStartSample);
    if snapshotStart < buffer.endSample
        snapshot = radio.stream.ringBufferRange( ...
            buffer, snapshotStart, buffer.endSample);
        coordinator.activeRace = radio.stream.parallelProbeRaceStart( ...
            snapshot, coordinator.probeStates, ...
            'EpochId', epoch.epochId, ...
            'Generation', epoch.generation, ...
            'Registry', coordinator.registry, ...
            'Mode', coordinator.options.mode, ...
            'NumWorkers', coordinator.options.numWorkers, ...
            'PoolType', coordinator.options.poolType, ...
            'TaskFcn', coordinator.options.taskFcn, ...
            'TaskContext', coordinator.options.taskContext);
        if coordinator.activeRace.completed
            raceStatus = coordinator.activeRace.race;
            [coordinator, events] = finishRace( ...
                coordinator, events, raceStatus, chunk.sourceSampleEnd);
        end
    end
end

if strcmp(coordinator.state, 'CATCHING_UP') && ...
        ~isempty(coordinator.activeCatchup)
    [coordinator.activeCatchup, catchupStatus] = ...
        radio.stream.winnerCatchupPoll(coordinator.activeCatchup);
    if coordinator.activeCatchup.completed
        [coordinator, events] = finishCatchup( ...
            coordinator, events, catchupStatus, chunk.sourceSampleEnd);
    end
end

if strcmp(coordinator.state, 'LOCKED') && ~isempty(coordinator.decoderState) && ...
        chunk.sourceSampleEnd > coordinator.decoderState.lastProcessedEndSample
    [coordinator.decoderState, coordinator.lastDecoderOutput] = ...
        radio.stream.lockedDecoderProcess( ...
            coordinator.decoderState, coordinator.channelController.ringBuffer);
end

output = makeOutput( ...
    coordinator, channelOutput, events, raceStatus, catchupStatus);
end

function [coordinator, events] = finishRace( ...
        coordinator, events, race, eventSample)
coordinator.probeStates = coordinator.activeRace.states;
coordinator.lastRace = race;
coordinator.activeRace = [];
switch race.outcome
    case 'confirmed'
        oldState = coordinator.state;
        coordinator.selectedProtocol = race.winner.protocol;
        coordinator.state = 'CATCHING_UP';
        events(end+1) = makeEvent('PROTOCOL_CONFIRMED', oldState, ...
            'CATCHING_UP', eventSample, coordinator.selectedProtocol, ...
            race.winner.evidenceClass); %#ok<AGROW>
        coordinator = startCatchup(coordinator);
        if coordinator.activeCatchup.completed
            [coordinator.activeCatchup, status] = ...
                radio.stream.winnerCatchupPoll(coordinator.activeCatchup);
            [coordinator, events] = finishCatchup( ...
                coordinator, events, status, eventSample);
        end
    case 'ambiguous'
        coordinator.state = 'AMBIGUOUS';
        events(end+1) = makeEvent('PROTOCOL_AMBIGUOUS', 'CLASSIFYING', ...
            'AMBIGUOUS', eventSample, '', ...
            strjoin(race.confirmedProtocols, ',')); %#ok<AGROW>
    case 'rejected_all'
        coordinator.state = 'UNKNOWN';
        events(end+1) = makeEvent('PROTOCOL_UNKNOWN', 'CLASSIFYING', ...
            'UNKNOWN', eventSample, '', 'all_probes_rejected'); %#ok<AGROW>
    case 'error'
        coordinator.state = 'ERROR';
        events(end+1) = makeEvent('PROBE_ERROR', 'CLASSIFYING', ...
            'ERROR', eventSample, '', 'all_remaining_probes_failed'); %#ok<AGROW>
end
end

function coordinator = startCatchup(coordinator)
epoch = coordinator.channelController.currentEpoch;
coordinator.catchupPassCount = coordinator.catchupPassCount + 1;
coordinator.activeCatchup = radio.stream.winnerCatchupStart( ...
    coordinator.channelController.ringBuffer, epoch, ...
    coordinator.selectedProtocol, ...
    'Mode', coordinator.options.mode, ...
    'NumWorkers', coordinator.options.numWorkers, ...
    'PoolType', coordinator.options.poolType, ...
    'PreTriggerSec', coordinator.options.preTriggerSec);
end

function [coordinator, events] = finishCatchup( ...
        coordinator, events, status, eventSample)
coordinator.activeCatchup = [];
if ~strcmp(status.state, 'completed') || isempty(status.result)
    coordinator.state = 'CATCHUP_ERROR';
    events(end+1) = makeEvent('CATCHUP_ERROR', 'CATCHING_UP', ...
        'CATCHUP_ERROR', eventSample, coordinator.selectedProtocol, ...
        status.errorReason); %#ok<AGROW>
    return;
end
coordinator.lastCatchup = status.result;
buffer = coordinator.channelController.ringBuffer;
if status.result.catchupEndSample < buffer.endSample
    coordinator = startCatchup(coordinator);
    events(end+1) = makeEvent('CATCHUP_RETRY', 'CATCHING_UP', ...
        'CATCHING_UP', eventSample, coordinator.selectedProtocol, ...
        'live_edge_advanced_during_decode'); %#ok<AGROW>
else
    coordinator.state = 'LOCKED';
    epoch = coordinator.channelController.currentEpoch;
    coordinator.decoderState = radio.stream.lockedDecoderInit( ...
        coordinator.selectedProtocol, epoch, buffer.sampleRateHz, ...
        'InitialPdus', status.result.pdus, ...
        'LastProcessedEndSample', status.result.catchupEndSample);
    events(end+1) = makeEvent('CATCHUP_COMPLETE', 'CATCHING_UP', ...
        'LOCKED', eventSample, coordinator.selectedProtocol, ...
        'caught_up_to_live_edge'); %#ok<AGROW>
end
end

function [coordinator, events] = cancelActive( ...
        coordinator, events, eventSample, reason)
if ~isempty(coordinator.activeRace)
    [coordinator.activeRace, ~] = ...
        radio.stream.parallelProbeRaceCancel( ...
            coordinator.activeRace, 'Reason', reason);
    coordinator.activeRace = [];
    events(end+1) = makeEvent('RACE_CANCELED', coordinator.state, ...
        coordinator.state, eventSample, '', reason); %#ok<AGROW>
end
if ~isempty(coordinator.activeCatchup)
    [coordinator.activeCatchup, ~] = ...
        radio.stream.winnerCatchupCancel(coordinator.activeCatchup);
    coordinator.activeCatchup = [];
    events(end+1) = makeEvent('CATCHUP_CANCELED', coordinator.state, ...
        coordinator.state, eventSample, coordinator.selectedProtocol, reason); %#ok<AGROW>
end
end

function coordinator = clearEpoch(coordinator)
coordinator.state = 'NO_SIGNAL';
coordinator.probeStates = [];
coordinator.activeRace = [];
coordinator.activeCatchup = [];
coordinator.selectedProtocol = '';
coordinator.decoderState = [];
coordinator.lastDecoderOutput = [];
coordinator.currentEpochId = uint64(0);
coordinator.currentGeneration = uint64(0);
coordinator.catchupPassCount = 0;
end

function output = makeOutput(coordinator, channel, events, race, catchup)
output = struct( ...
    'state', coordinator.state, ...
    'selectedProtocol', coordinator.selectedProtocol, ...
    'epochId', coordinator.currentEpochId, ...
    'generation', coordinator.currentGeneration, ...
    'channel', channel, ...
    'race', race, ...
    'catchup', catchup, ...
    'events', events, ...
    'lastRace', coordinator.lastRace, ...
    'lastCatchup', coordinator.lastCatchup, ...
    'decoder', coordinator.lastDecoderOutput);
end

function event = makeEvent(type, fromState, toState, sample, protocol, reason)
event = struct( ...
    'type', type, ...
    'fromState', fromState, ...
    'toState', toState, ...
    'sample', uint64(sample), ...
    'protocol', protocol, ...
    'reason', reason);
end

function events = emptyEvents()
events = struct('type', {}, 'fromState', {}, 'toState', {}, ...
    'sample', {}, 'protocol', {}, 'reason', {});
end
