function buffer = ringBufferInit(sampleRateHz, capacitySec, varargin)
%RINGBUFFERINIT Create a fixed-size complex-single IQ ring buffer.
p = inputParser;
p.addParameter('ChannelId', 1);
p.addParameter('CenterFrequencyHz', 0);
p.parse(varargin{:});

validateattributes(sampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(capacitySec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
capacitySamples = max(1, ceil(double(sampleRateHz) * double(capacitySec)));

buffer = struct( ...
    'data', complex(zeros(capacitySamples, 1, 'single')), ...
    'capacitySamples', capacitySamples, ...
    'sampleRateHz', double(sampleRateHz), ...
    'channelId', p.Results.ChannelId, ...
    'centerFrequencyHz', double(p.Results.CenterFrequencyHz), ...
    'writePosition', 1, ...
    'count', 0, ...
    'startSample', uint64(0), ...
    'endSample', uint64(0), ...
    'lastSequenceNumber', uint64(0), ...
    'continuityGeneration', uint64(0), ...
    'discontinuityCount', uint64(0), ...
    'droppedSourceSamples', uint64(0));
end
