function pdus = stampStreamPdusAtSamples( ...
        pdus, protocol, sourceSamples, snapshot, epochId)
%STAMPSTREAMPDUSATSAMPLES Add metadata using native absolute sample times.
pdus = radio.normalizePdus(pdus);
if isempty(pdus), return; end
sourceSamples = uint64(sourceSamples(:));
if numel(sourceSamples) ~= numel(pdus)
    error('radio:stream:stampStreamPdusAtSamples:Count', ...
        'Native source-sample count must match the PDU count.');
end
protocol = radio.normalizeProtocolNames({protocol});
protocol = protocol{1};
for k = 1:numel(pdus)
    sourceSample = sourceSamples(k);
    stream = struct( ...
        'epoch_id', uint64(epochId), ...
        'source_sample', sourceSample, ...
        'source_time_sec', double(sourceSample) / snapshot.sampleRateHz, ...
        'window_start_source_sample', snapshot.sourceSampleStart, ...
        'window_end_source_sample', snapshot.sourceSampleEnd, ...
        'position_basis', 'native_incremental_state', ...
        'protocol', protocol);
    pdus(k).extra.stream = stream;
end
end
