function [handle, status] = winnerCatchupCancel(handle)
%WINNERCATCHUPCANCEL Best-effort cancel of an obsolete catch-up generation.
if ~handle.completed && ~isempty(handle.future)
    try
        cancel(handle.future);
    catch
    end
end
handle.canceled = true;
handle.completed = true;
handle.elapsedSec = toc(handle.timerToken);
handle.result = [];
handle.errorReason = 'catchup_canceled';
status = struct( ...
    'state', 'canceled', ...
    'completed', true, ...
    'canceled', true, ...
    'mode', handle.mode, ...
    'elapsedSec', handle.elapsedSec, ...
    'errorReason', handle.errorReason, ...
    'result', []);
end
