function handle = winnerCatchupStart(buffer, epoch, protocol, varargin)
%WINNERCATCHUPSTART Start asynchronous winner backlog decode.
p = inputParser;
p.addParameter('NumWorkers', 5);
p.addParameter('PreTriggerSec', radio.stream.defaultConfig().preTriggerSec);
p.addParameter('Deduplicate', true);
p.addParameter('InitialPdus', struct([]));
p.parse(varargin{:});

protocol = radio.normalizeProtocolNames({protocol});
protocol = protocol{1};
handle = struct( ...
    'epochId', uint64(epoch.epochId), ...
    'generation', uint64(epoch.generation), ...
    'protocol', protocol, ...
    'mode', '', ...
    'future', [], ...
    'completed', false, ...
    'canceled', false, ...
    'result', [], ...
    'errorReason', '', ...
    'timerToken', tic, ...
    'elapsedSec', 0);

[pool, info] = radio.stream.acquireParallelPool( ...
    'NumWorkers', p.Results.NumWorkers);
if isempty(pool)
    error('radio:stream:winnerCatchupStart:PoolUnavailable', ...
        'Parallel pool is unavailable: %s', info.reason);
end

handle.mode = 'parallel';
[transferMetadata, packedSnapshot, payload] = compactTransferBuffer( ...
    buffer, epoch, p.Results.PreTriggerSec);
handle.future = parfeval(pool, @radio.stream.winnerCatchupPacked, 1, ...
    transferMetadata, packedSnapshot, payload, epoch, protocol, ...
    'PreTriggerSec', p.Results.PreTriggerSec, ...
    'Deduplicate', p.Results.Deduplicate, ...
    'InitialPdus', p.Results.InitialPdus);
end

function [metadata, packedSnapshot, payload] = compactTransferBuffer( ...
        buffer, epoch, preTriggerSec)
preTriggerSamples = uint64(round(preTriggerSec * buffer.sampleRateHz));
candidateStart = uint64(epoch.candidateStartSample);
if candidateStart >= preTriggerSamples
    desiredStart = candidateStart - preTriggerSamples;
else
    desiredStart = uint64(0);
end
startSample = max(buffer.startSample, desiredStart);
snapshot = radio.stream.ringBufferRange( ...
    buffer, startSample, buffer.endSample);
[packedSnapshot, payload] = ...
    radio.stream.lockedDecoderActorPackChunk(snapshot);
metadata = struct( ...
    'sampleRateHz', buffer.sampleRateHz, ...
    'channelId', buffer.channelId, ...
    'centerFrequencyHz', buffer.centerFrequencyHz, ...
    'capacitySamples', max(1, numel(snapshot.iq)));
end
