function result = winnerCatchupPacked( ...
        metadata, packedSnapshot, payload, epoch, protocol, varargin)
%WINNERCATCHUPPACKED Restore compact IQ transport and decode the backlog.
snapshot = radio.stream.lockedDecoderActorUnpackChunk( ...
    packedSnapshot, payload);
capacitySec = max(1 / metadata.sampleRateHz, ...
    double(metadata.capacitySamples) / metadata.sampleRateHz);
buffer = radio.stream.ringBufferInit( ...
    metadata.sampleRateHz, capacitySec, ...
    'ChannelId', metadata.channelId, ...
    'CenterFrequencyHz', metadata.centerFrequencyHz);
[buffer, ~] = radio.stream.ringBufferPush(buffer, snapshot);
result = radio.stream.winnerCatchup( ...
    buffer, epoch, protocol, varargin{:});
end
