function handle = winnerCatchupStart(buffer, epoch, protocol, varargin)
%WINNERCATCHUPSTART Start synchronous or asynchronous winner backlog decode.
p = inputParser;
p.addParameter('Mode', 'auto');
p.addParameter('NumWorkers', 5);
p.addParameter('PoolType', 'auto');
p.addParameter('PreTriggerSec', radio.stream.defaultConfig().preTriggerSec);
p.addParameter('Deduplicate', true);
p.addParameter('InitialPdus', struct([]));
p.parse(varargin{:});

protocol = radio.normalizeProtocolNames({protocol});
protocol = protocol{1};
handle = struct( ...
    'epochId', uint64(epoch.epochId), ...
    'generation', uint64(epoch.generation), ...
    'protocol', protocol, ...
    'mode', '', ...
    'future', [], ...
    'completed', false, ...
    'canceled', false, ...
    'result', [], ...
    'errorReason', '', ...
    'fallbackReason', '', ...
    'timerToken', tic, ...
    'elapsedSec', 0);

mode = lower(char(p.Results.Mode));
if strcmp(mode, 'serial')
    handle.mode = 'serial';
    handle.result = radio.stream.winnerCatchup(buffer, epoch, protocol, ...
        'PreTriggerSec', p.Results.PreTriggerSec, ...
        'Deduplicate', p.Results.Deduplicate, ...
        'InitialPdus', p.Results.InitialPdus);
    handle.completed = true;
    handle.elapsedSec = toc(handle.timerToken);
    return;
end
if ~any(strcmp(mode, {'auto', 'parallel'}))
    error('radio:stream:winnerCatchupStart:Mode', ...
        'Mode must be auto, parallel, or serial.');
end

[pool, info] = radio.stream.acquireParallelPool( ...
    'NumWorkers', p.Results.NumWorkers, 'PoolType', p.Results.PoolType);
if isempty(pool)
    handle.mode = 'serial_fallback';
    handle.fallbackReason = info.reason;
    handle.result = radio.stream.winnerCatchup(buffer, epoch, protocol, ...
        'PreTriggerSec', p.Results.PreTriggerSec, ...
        'Deduplicate', p.Results.Deduplicate, ...
        'InitialPdus', p.Results.InitialPdus);
    handle.completed = true;
    handle.elapsedSec = toc(handle.timerToken);
    return;
end

handle.mode = 'parallel';
[transferMetadata, packedSnapshot, payload] = compactTransferBuffer( ...
    buffer, epoch, p.Results.PreTriggerSec);
handle.future = parfeval(pool, @radio.stream.winnerCatchupPacked, 1, ...
    transferMetadata, packedSnapshot, payload, epoch, protocol, ...
    'PreTriggerSec', p.Results.PreTriggerSec, ...
    'Deduplicate', p.Results.Deduplicate, ...
    'InitialPdus', p.Results.InitialPdus);
end

function [metadata, packedSnapshot, payload] = compactTransferBuffer( ...
        buffer, epoch, preTriggerSec)
preTriggerSamples = uint64(round(preTriggerSec * buffer.sampleRateHz));
candidateStart = uint64(epoch.candidateStartSample);
if candidateStart >= preTriggerSamples
    desiredStart = candidateStart - preTriggerSamples;
else
    desiredStart = uint64(0);
end
startSample = max(buffer.startSample, desiredStart);
snapshot = radio.stream.ringBufferRange( ...
    buffer, startSample, buffer.endSample);
[packedSnapshot, payload] = ...
    radio.stream.lockedDecoderActorPackChunk(snapshot);
metadata = struct( ...
    'sampleRateHz', buffer.sampleRateHz, ...
    'channelId', buffer.channelId, ...
    'centerFrequencyHz', buffer.centerFrequencyHz, ...
    'capacitySamples', max(1, numel(snapshot.iq)));
end
