function handle = winnerCatchupStart(buffer, epoch, protocol, varargin)
%WINNERCATCHUPSTART Start synchronous or asynchronous winner backlog decode.
p = inputParser;
p.addParameter('Mode', 'auto');
p.addParameter('NumWorkers', 5);
p.addParameter('PoolType', 'auto');
p.addParameter('PreTriggerSec', radio.stream.defaultConfig().preTriggerSec);
p.parse(varargin{:});

protocol = radio.normalizeProtocolNames({protocol});
protocol = protocol{1};
handle = struct( ...
    'epochId', uint64(epoch.epochId), ...
    'generation', uint64(epoch.generation), ...
    'protocol', protocol, ...
    'mode', '', ...
    'future', [], ...
    'completed', false, ...
    'canceled', false, ...
    'result', [], ...
    'errorReason', '', ...
    'fallbackReason', '', ...
    'timerToken', tic, ...
    'elapsedSec', 0);

mode = lower(char(p.Results.Mode));
if strcmp(mode, 'serial')
    handle.mode = 'serial';
    handle.result = radio.stream.winnerCatchup(buffer, epoch, protocol, ...
        'PreTriggerSec', p.Results.PreTriggerSec);
    handle.completed = true;
    handle.elapsedSec = toc(handle.timerToken);
    return;
end
if ~any(strcmp(mode, {'auto', 'parallel'}))
    error('radio:stream:winnerCatchupStart:Mode', ...
        'Mode must be auto, parallel, or serial.');
end

[pool, info] = radio.stream.acquireParallelPool( ...
    'NumWorkers', p.Results.NumWorkers, 'PoolType', p.Results.PoolType);
if isempty(pool)
    handle.mode = 'serial_fallback';
    handle.fallbackReason = info.reason;
    handle.result = radio.stream.winnerCatchup(buffer, epoch, protocol, ...
        'PreTriggerSec', p.Results.PreTriggerSec);
    handle.completed = true;
    handle.elapsedSec = toc(handle.timerToken);
    return;
end

handle.mode = 'parallel';
handle.future = parfeval(pool, @radio.stream.winnerCatchup, 1, ...
    buffer, epoch, protocol, 'PreTriggerSec', p.Results.PreTriggerSec);
end
