function snapshot = spectrumSnapshot(state, varargin)
%SPECTRUMSNAPSHOT Return plotting arrays in chronological waterfall order.
p = inputParser;
p.addParameter('IncludeWaterfall', true);
p.parse(varargin{:});
if ~p.Results.IncludeWaterfall
    waterfall = zeros(0, numel(state.displayFrequencyHz), 'single');
    timesSec = zeros(0, 1);
else
rowCount = double(state.waterfallRowCount);
if rowCount == 0
    waterfall = zeros(0, numel(state.displayFrequencyHz), 'single');
    timesSec = zeros(0, 1);
elseif rowCount < state.config.maxWaterfallRows
    order = 1:rowCount;
    waterfall = state.waterfallCircular(order, :);
    timesSec = state.waterfallTimesSec(order);
else
    latest = double(state.waterfallWriteIndex);
    order = [latest+1:state.config.maxWaterfallRows, 1:latest];
    waterfall = state.waterfallCircular(order, :);
    timesSec = state.waterfallTimesSec(order);
end
end
snapshot = struct( ...
    'sampleRateHz', state.sampleRateHz, ...
    'centerFrequencyHz', state.centerFrequencyHz, ...
    'offsetHz', state.offsetHz, ...
    'frequencyHz', state.frequencyHz, ...
    'averagePsd', state.averagePsd, ...
    'maxHoldPsd', state.maxHoldPsd, ...
    'displayOffsetHz', state.displayOffsetHz, ...
    'displayFrequencyHz', state.displayFrequencyHz, ...
    'waterfallPsd', waterfall, ...
    'waterfallTimeSec', timesSec, ...
    'hasEstimate', state.hasEstimate, ...
    'updateCount', state.updateCount, ...
    'inputSampleCount', state.inputSampleCount, ...
    'segmentCount', state.segmentCount);
end
