function state = spectrumInit(sampleRateHz, centerFrequencyHz, varargin)
%SPECTRUMINIT Initialize incremental PSD, Max Hold, and waterfall state.
p = inputParser;
p.addParameter('Config', radio.scope.defaultConfig());
p.parse(varargin{:});
cfg = p.Results.Config;
validateattributes(sampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(centerFrequencyHz, {'numeric'}, ...
    {'scalar', 'real', 'finite'});
validateConfig(cfg);

nfft = double(cfg.nfft);
displayFactor = max(1, ceil(nfft / cfg.maxDisplayBins));
while mod(nfft, displayFactor) ~= 0
    displayFactor = displayFactor + 1;
end
displayBinCount = nfft / displayFactor;
indices = (0:nfft-1).';
window = 0.5 - 0.5 .* cos(2 .* pi .* indices ./ max(nfft - 1, 1));
normalization = sum(abs(window) .^ 2) * sampleRateHz;
offsetHz = (-nfft/2:nfft/2-1).' .* (sampleRateHz / nfft);
frequencyHz = centerFrequencyHz + offsetHz;
displayOffsetHz = mean(reshape(offsetHz, displayFactor, []), 1).';
displayFrequencyHz = centerFrequencyHz + displayOffsetHz;

state = struct( ...
    'config', cfg, ...
    'sampleRateHz', double(sampleRateHz), ...
    'centerFrequencyHz', double(centerFrequencyHz), ...
    'nfft', nfft, ...
    'window', window, ...
    'normalization', double(normalization), ...
    'offsetHz', offsetHz, ...
    'frequencyHz', frequencyHz, ...
    'displayFactor', double(displayFactor), ...
    'displayOffsetHz', displayOffsetHz, ...
    'displayFrequencyHz', displayFrequencyHz, ...
    'updateSamples', uint64(max(nfft, round( ...
        cfg.updateIntervalSec * sampleRateHz))), ...
    'fftRemainder', complex(zeros(0, 1)), ...
    'intervalPowerSum', zeros(nfft, 1), ...
    'intervalSegmentCount', uint64(0), ...
    'samplesSinceUpdate', uint64(0), ...
    'averagePsd', zeros(nfft, 1), ...
    'maxHoldPsd', zeros(nfft, 1), ...
    'hasEstimate', false, ...
    'waterfallCircular', zeros( ...
        cfg.maxWaterfallRows, displayBinCount, 'single'), ...
    'waterfallTimesSec', zeros(cfg.maxWaterfallRows, 1), ...
    'waterfallWriteIndex', uint32(0), ...
    'waterfallRowCount', uint32(0), ...
    'inputSampleCount', uint64(0), ...
    'segmentCount', uint64(0), ...
    'updateCount', uint64(0), ...
    'lastSourceSampleEnd', uint64(0), ...
    'lastDiscontinuity', false);
end

function validateConfig(cfg)
required = {'nfft', 'updateIntervalSec', 'averageAlpha', ...
    'maxWaterfallRows', 'maxDisplayBins'};
missing = required(~isfield(cfg, required));
if ~isempty(missing)
    error('radio:scope:spectrumInit:Config', ...
        'Spectrum configuration is missing field: %s', missing{1});
end
validateattributes(cfg.nfft, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'});
if cfg.nfft < 16 || mod(cfg.nfft, 2) ~= 0
    error('radio:scope:spectrumInit:Nfft', ...
        'nfft must be an even integer of at least 16.');
end
validateattributes(cfg.updateIntervalSec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(cfg.averageAlpha, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 0, '<=', 1});
validateattributes(cfg.maxWaterfallRows, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'});
validateattributes(cfg.maxDisplayBins, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'});
end
