function [pdus, diagnostics, frequencyOffsetHz, timingState] = ...
        fakeLockedDecoder(protocol, snapshot)
%FAKELOCKEDDECODER Emit deterministic DMR PDUs at absolute 100-sample ticks.
if ~strcmp(protocol, 'DMR')
    error('tests:fakeLockedDecoder:Protocol', 'Synthetic decoder expects DMR.');
end
first = ceil(double(snapshot.sourceSampleStart) / 100) * 100;
positions = first:100:double(snapshot.sourceSampleEnd) - 1;
pdus = struct([]);
for k = 1:numel(positions)
    localSourceSample = positions(k) - double(snapshot.sourceSampleStart);
    fsStart = round(localSourceSample * 48000 / snapshot.sampleRateHz);
    pdu = struct( ...
        'protocol', 'DMR', ...
        'type', 'LC_HEADER', ...
        'src', 1, ...
        'dst', 2, ...
        'ts', 0, ...
        'flco', 'GROUP_VOICE_CHANNEL_USER', ...
        'fid', '', ...
        'extra', struct( ...
            'fs_start', fsStart, ...
            'fec', struct('rs_12_9_4_ok', true)), ...
        'raw_bits', []);
    if isempty(pdus)
        pdus = pdu;
    else
        pdus(end+1) = pdu; %#ok<AGROW>
    end
end
diagnostics = struct();
frequencyOffsetHz = 0;
timingState = struct();
end
