function pdus = fakeEpochDecoder(~, ~, protocol)
%FAKEEPOCHDECODER Emit one identical transmitter PDU for every test Epoch.
pdus = struct( ...
    'protocol', protocol, ...
    'type', 'SYNTHETIC_CHANNEL_PDU', ...
    'src', 12345, ...
    'dst', 67890, ...
    'ts', 1, ...
    'flco', '', ...
    'fid', '', ...
    'extra', struct('fs_start', 0), ...
    'raw_bits', []);
end
