function report = runFiveSignal2p5MHzAcceptance(varargin)
%RUNFIVESIGNAL2P5MHZACCEPTANCE Validate the five-protocol 2.5 MHz fixture.
%
% This is an opt-in real-data acceptance test and is intentionally not part
% of tests.runAll.  It reads local captures, creates a large ignored IQ
% artifact, and can start a five-process parallel pool.
p = inputParser;
p.addParameter('OutputPath', fullfile(projectRoot(), 'signal_data', ...
    'synthesized_5sync_2.5MHz.rawiq'));
p.addParameter('Regenerate', true);
p.addParameter('VerifyKnownChannels', true);
p.addParameter('RunFrontend', true);
p.addParameter('FrontendTimeoutSec', 300);
p.addParameter('StrictFrontend', false);
p.addParameter('Verbose', true);
p.parse(varargin{:});
options = p.Results;

if options.Regenerate || exist(options.OutputPath, 'file') ~= 2
    manifest = synthesizeFiveSignal2p5MHz( ...
        'OutputPath', options.OutputPath, ...
        'Overwrite', true, ...
        'Verbose', options.Verbose);
else
    manifest = readManifest([char(options.OutputPath), '.json']);
end
validateFixtureFile(manifest);
spectrum = verifySpectrum(manifest);

channelResults = struct([]);
if options.VerifyKnownChannels
    channelResults = verifyKnownChannels(manifest, options.Verbose);
end

frontend = struct();
if options.RunFrontend
    frontend = verifyLiveFrontend(manifest, ...
        options.FrontendTimeoutSec, options.StrictFrontend, options.Verbose);
end

report = struct( ...
    'manifest', manifest, ...
    'spectrum', spectrum, ...
    'channelResults', channelResults, ...
    'frontend', frontend);
if options.Verbose
    fprintf('Five-signal 2.5 MHz acceptance completed.\n');
end
end

function validateFixtureFile(manifest)
assert(manifest.sampleRateHz == 2.5e6);
assert(numel(manifest.channels) == 5);
assert(isequal({manifest.channels.protocol}, ...
    {'DMR', 'P25', 'dPMR', 'NXDN', 'TETRA'}));
expectedBytes = 4 * double(manifest.sampleCount);
info = dir(manifest.outputPath);
assert(~isempty(info) && info.bytes == expectedBytes, ...
    'Generated CI16 file size does not match the manifest.');
assert(common.detectSampleRate(manifest.outputPath) == ...
    manifest.sampleRateHz);
starts = [manifest.channels.outputStartSec];
assert(max(starts) - min(starts) <= 0.1, ...
    'The five signal onsets are not near-synchronous.');
end

function result = verifySpectrum(manifest)
fs = manifest.sampleRateHz;
analysisStartSec = max([manifest.channels.outputStartSec]) + 0.10;
analysisDurationSec = 0.25;
iq = readCi16Segment(manifest.outputPath, fs, ...
    analysisStartSec, analysisDurationSec);
nfft = min(262144, 2 ^ floor(log2(numel(iq))));
values = iq(1:nfft);
n = (0:nfft-1).';
window = 0.5 - 0.5 .* cos(2 .* pi .* n ./ max(1, nfft - 1));
power = abs(fftshift(fft(values .* window, nfft))) .^ 2 ./ ...
    max(sum(window .^ 2), realmin);
frequencyHz = (-nfft/2:nfft/2-1).' .* fs ./ nfft;

offsets = [manifest.channels.frequencyOffsetHz];
noiseMask = true(size(frequencyHz));
for k = 1:numel(offsets)
    noiseMask = noiseMask & abs(frequencyHz - offsets(k)) > 70e3;
end
noisePower = median(power(noiseMask));
peakFrequencyHz = zeros(size(offsets));
peakMarginDb = zeros(size(offsets));
for k = 1:numel(offsets)
    local = abs(frequencyHz - offsets(k)) <= 120e3;
    [peakPower, localIndex] = max(power(local));
    localFrequency = frequencyHz(local);
    peakFrequencyHz(k) = localFrequency(localIndex);
    peakMarginDb(k) = 10 .* log10(max(peakPower, realmin) ./ ...
        max(noisePower, realmin));
    assert(abs(peakFrequencyHz(k) - offsets(k)) < 50e3, ...
        'No modulation peak was found near channel %d.', k);
    assert(peakMarginDb(k) > 15, ...
        'Channel %d is less than 15 dB above the wideband noise floor.', k);
end
result = struct( ...
    'analysisStartSec', analysisStartSec, ...
    'analysisDurationSec', analysisDurationSec, ...
    'peakFrequencyHz', peakFrequencyHz, ...
    'peakMarginDb', peakMarginDb, ...
    'noisePower', noisePower);
end

function results = verifyKnownChannels(manifest, verbose)
[tunedConfig, rateReport] = radio.tuned.resolveInputConfig( ...
    manifest.sampleRateHz, radio.tuned.defaultConfig());
assert(rateReport.decimationFactor == 20);
channels = manifest.channels;
results = repmat(struct( ...
    'channelId', 0, ...
    'protocol', '', ...
    'frequencyOffsetHz', 0, ...
    'outcome', '', ...
    'selectedProtocol', '', ...
    'epochCount', 0, ...
    'confirmedEpochCount', 0, ...
    'pduCount', 0, ...
    'elapsedSec', 0), numel(channels), 1);
for k = 1:numel(channels)
    token = tic;
    [pdus, scanReport] = radio.tuned.scanFile( ...
        manifest.outputPath, ...
        'FrequencyOffsetHz', channels(k).frequencyOffsetHz, ...
        'SampleRate', manifest.sampleRateHz, ...
        'CenterFrequencyHz', manifest.centerFrequencyHz, ...
        'Config', tunedConfig, ...
        'ProtocolNames', {channels(k).protocol}, ...
        'Mode', 'serial', ...
        'TimeoutSec', 300, ...
        'Deduplicate', false, ...
        'ShowProgress', false, ...
        'ChannelId', k);
    results(k) = struct( ...
        'channelId', k, ...
        'protocol', channels(k).protocol, ...
        'frequencyOffsetHz', channels(k).frequencyOffsetHz, ...
        'outcome', scanReport.outcome, ...
        'selectedProtocol', scanReport.selectedProtocol, ...
        'epochCount', scanReport.epochCount, ...
        'confirmedEpochCount', scanReport.confirmedEpochCount, ...
        'pduCount', numel(pdus), ...
        'elapsedSec', toc(token));
    assert(strcmp(results(k).outcome, 'confirmed'));
    assert(strcmp(results(k).selectedProtocol, channels(k).protocol));
    assert(results(k).confirmedEpochCount >= 1);
    assert(results(k).pduCount >= 1);
    if verbose
        fprintf('Verified ch%d %-5s: epochs=%d, PDUs=%d, %.3f s.\n', ...
            k, channels(k).protocol, results(k).epochCount, ...
            results(k).pduCount, results(k).elapsedSec);
    end
end
end

function result = verifyLiveFrontend(manifest, timeoutSec, strict, verbose)
app = radio_live_frontend( ...
    'Visible', 'off', ...
    'DefaultFile', manifest.outputPath, ...
    'SampleRate', manifest.sampleRateHz, ...
    'CenterFrequencyHz', manifest.centerFrequencyHz, ...
    'ReplayMode', 'once', ...
    'MaxLoops', 1, ...
    'ProtocolNames', {}, ...
    'ParallelMode', 'parallel', ...
    'NumWorkers', 5, ...
    'PoolType', 'processes', ...
    'Deduplicate', false, ...
    'PrintToCommandWindow', false);
cleanup = onCleanup(@() app.Close());

prepareToken = tic;
app.StartPreview('StartTimer', false);
prepareElapsedSec = toc(prepareToken);
for k = 1:numel(manifest.channels)
    app.AddOffsetHz(manifest.channels(k).frequencyOffsetHz, ...
        'Refine', false);
end
runToken = tic;
app.RunIdentification();
maxQueueSec = 0;
while toc(runToken) < timeoutSec
    pause(0.10);
    state = app.GetState();
    maxQueueSec = max(maxQueueSec, state.decoderQueueSec);
    if strcmp(state.mode, 'COMPLETED')
        break;
    end
end
runElapsedSec = toc(runToken);
state = app.GetState();
assert(strcmp(state.mode, 'COMPLETED'), ...
    'The live frontend did not complete before the acceptance timeout.');
assert(~isempty(state.scanner) && state.scanner.channelCount == 5);
expectedProtocols = reshape({manifest.channels.protocol}, [], 1);
winnersMatch = isequal(state.scanner.selectedProtocols, expectedProtocols);
if verbose
    fprintf('Parallel winners: %s (expected %s).\n', ...
        strjoin(replaceEmpty(state.scanner.selectedProtocols), '/'), ...
        strjoin(expectedProtocols, '/'));
end
assert(state.decoderQueueSec == 0, ...
    'The decoder queue did not drain during finalization.');
assert(state.maxInputLagSec < 0.25, ...
    'The 1x spectrum/input path exceeded the 250 ms lag budget.');

channelPduCounts = zeros(5, 1);
if ~isempty(state.pdus)
    channelIds = arrayfun(@(item) double(radio.getNestedField( ...
        item, 'extra.tuned.channel_id', uint64(0))), state.pdus);
    for k = 1:5
        channelPduCounts(k) = sum(channelIds == k);
    end
end
if verbose
    fprintf('Parallel per-channel PDU counts: %s.\n', ...
        mat2str(channelPduCounts.'));
end

result = struct( ...
    'prepareElapsedSec', prepareElapsedSec, ...
    'runElapsedSec', runElapsedSec, ...
    'inputDurationSec', manifest.durationSec, ...
    'endToEndRealTimeFactor', runElapsedSec / manifest.durationSec, ...
    'maxInputLagSec', state.maxInputLagSec, ...
    'maxDecoderQueueSec', maxQueueSec, ...
    'finalDecoderQueueSec', state.decoderQueueSec, ...
    'pduCount', numel(state.pdus), ...
    'channelPduCounts', channelPduCounts, ...
    'allChannelsProducedPdus', all(channelPduCounts > 0), ...
    'selectedProtocols', {state.scanner.selectedProtocols}, ...
    'winnersMatchManifest', winnersMatch, ...
    'functionalPass', winnersMatch && all(channelPduCounts > 0), ...
    'continuousDecodeRealtime', maxQueueSec <= 0.25 && ...
        runElapsedSec <= manifest.durationSec + 0.5);
if verbose
    fprintf(['Frontend winners=%s, PDUs=%d, input max lag=%.3f s, ', ...
        'decoder max queue=%.3f s, end-to-end RTF=%.3f.\n'], ...
        strjoin(result.selectedProtocols, '/'), result.pduCount, ...
        result.maxInputLagSec, result.maxDecoderQueueSec, ...
        result.endToEndRealTimeFactor);
end
if strict
    assert(winnersMatch, ...
        'The five parallel protocol winners do not match the manifest.');
    assert(all(channelPduCounts > 0), ...
        'At least one locked carrier emitted no PDU in the parallel run.');
end
app.Close();
clear cleanup;
end

function values = replaceEmpty(values)
values = values(:).';
for k = 1:numel(values)
    if isempty(values{k}), values{k} = '-'; end
end
end

function iq = readCi16Segment(path, sampleRateHz, startSec, durationSec)
firstSample = round(startSec * sampleRateHz);
sampleCount = round(durationSec * sampleRateHz);
fid = fopen(path, 'rb', 'ieee-le');
if fid < 0
    error('tests:fiveSignal:Open', 'Unable to open %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
status = fseek(fid, 4 * firstSample, 'bof');
assert(status == 0, 'Unable to seek to the spectrum validation segment.');
raw = fread(fid, [2, sampleCount], 'int16=>double');
assert(size(raw, 2) == sampleCount, ...
    'The spectrum validation segment is incomplete.');
iq = complex(raw(1, :), raw(2, :)).' ./ 32768;
clear cleanup;
end

function manifest = readManifest(path)
if exist(path, 'file') ~= 2
    error('tests:fiveSignal:Manifest', ...
        'Missing fixture manifest: %s', path);
end
manifest = jsondecode(fileread(path));
end

function root = projectRoot()
root = fileparts(fileparts(mfilename('fullpath')));
end
