function report = runLongRealtimeAcceptance(varargin)
%RUNLONGREALTIMEACCEPTANCE Observe queue growth at 1/2/5 minute marks.
% This opt-in test is intentionally excluded from tests.runAll.
p = inputParser;
p.addParameter('ManifestPath', fullfile(projectRoot(), 'signal_data', ...
    'synthesized_5sync_2.5MHz.rawiq.json'));
p.addParameter('ChannelIndices', 1:5);
p.addParameter('CheckpointsSec', [60 120 300]);
p.addParameter('PollPeriodSec', 0.25);
p.addParameter('TimeoutMarginSec', 90);
p.addParameter('Verbose', true);
p.parse(varargin{:});
options = p.Results;

manifest = jsondecode(fileread(options.ManifestPath));
indices = double(options.ChannelIndices(:).');
checkpoints = sort(double(options.CheckpointsSec(:).'));
validateattributes(indices, {'numeric'}, ...
    {'vector', 'integer', 'positive'});
assert(all(indices <= numel(manifest.channels)));
validateattributes(checkpoints, {'numeric'}, ...
    {'vector', 'real', 'finite', 'positive'});
maxLoops = ceil(max(checkpoints) / manifest.durationSec);
expectedDurationSec = maxLoops * manifest.durationSec;

app = radio_parallel_frontend( ...
    'Visible', 'off', ...
    'DefaultFile', manifest.outputPath, ...
    'SampleRate', manifest.sampleRateHz, ...
    'CenterFrequencyHz', manifest.centerFrequencyHz, ...
    'ReplayMode', 'continuous-test', ...
    'MaxLoops', maxLoops, ...
    'ProtocolNames', {}, ...
    'NumWorkers', 5, ...
    'Deduplicate', false, ...
    'PrintToCommandWindow', false);
cleanup = onCleanup(@() app.Close());

prepareToken = tic;
app.StartPreview('StartTimer', false);
prepareElapsedSec = toc(prepareToken);
for k = indices
    app.SelectOffsetHz(manifest.channels(k).frequencyOffsetHz, ...
        'Refine', false);
end

runToken = tic;
app.StartDecode();
wallHistory = zeros(0, 1);
logicalHistory = zeros(0, 1);
queueHistory = zeros(0, 1);
inputLagHistory = zeros(0, 1);
wallMinusLogicalHistory = zeros(0, 1);
checkpointResults = repmat(emptyCheckpoint(), numel(checkpoints), 1);
nextCheckpoint = 1;
lastProgressPrintSec = 0;
timeoutSec = expectedDurationSec + options.TimeoutMarginSec;
while toc(runToken) < timeoutSec
    pause(options.PollPeriodSec);
    state = app.GetState();
    wallSec = toc(runToken);
    logicalSec = double(state.sourceNextSample) / manifest.sampleRateHz;
    wallHistory(end+1, 1) = wallSec; %#ok<AGROW>
    logicalHistory(end+1, 1) = logicalSec; %#ok<AGROW>
    queueHistory(end+1, 1) = ...
        state.decoderPipelineQueueSec; %#ok<AGROW>
    inputLagHistory(end+1, 1) = state.inputLagSec; %#ok<AGROW>
    wallMinusLogicalHistory(end+1, 1) = wallSec - logicalSec; %#ok<AGROW>
    while nextCheckpoint <= numel(checkpoints) && ...
            logicalSec >= checkpoints(nextCheckpoint)
        checkpointResults(nextCheckpoint) = checkpointFromState( ...
            checkpoints(nextCheckpoint), wallSec, logicalSec, state);
        if options.Verbose
            printCheckpoint(checkpointResults(nextCheckpoint));
        end
        nextCheckpoint = nextCheckpoint + 1;
    end
    if options.Verbose && wallSec - lastProgressPrintSec >= 30
        fprintf(['Long realtime progress: logical %.1f/%.1f s, ', ...
            'wall %.1f s, queue %.3f s, max lag %.3f s.\n'], ...
            logicalSec, expectedDurationSec, wallSec, ...
            state.decoderPipelineQueueSec, state.maxInputLagSec);
        lastProgressPrintSec = wallSec;
    end
    if any(strcmp(state.mode, {'COMPLETED', 'ERROR'})), break; end
end
runElapsedSec = toc(runToken);
state = app.GetState();

intervalEdges = [0, checkpoints];
intervals = repmat(emptyInterval(), numel(checkpoints), 1);
for k = 1:numel(checkpoints)
    intervals(k) = intervalStats( ...
        intervalEdges(k), intervalEdges(k + 1), ...
        wallHistory, logicalHistory, queueHistory, ...
        wallMinusLogicalHistory);
end

expectedProtocols = reshape( ...
    {manifest.channels(indices).protocol}, [], 1);
selectedProtocols = cell(0, 1);
if ~isempty(state.scanner)
    selectedProtocols = state.scanner.selectedProtocols;
end
winnersMatch = isequal(selectedProtocols, expectedProtocols);
allCheckpointsReached = nextCheckpoint > numel(checkpoints);
logicalRates = [intervals.logicalRate];
queueSlopes = [intervals.queueSlopeSecPerSec];
streamingRealtimePass = strcmp(state.mode, 'COMPLETED') && ...
    winnersMatch && allCheckpointsReached && ...
    all(logicalRates >= 0.98 & logicalRates <= 1.02) && ...
    all(queueSlopes <= 1e-3) && ...
    max(queueHistory, [], 'omitnan') <= 0.25 && ...
    state.decoderPipelineQueueSec == 0;
strictOfflinePass = runElapsedSec <= expectedDurationSec;

report = struct( ...
    'channelIndices', indices, ...
    'protocols', {expectedProtocols}, ...
    'checkpointsSec', checkpoints, ...
    'maxLoops', maxLoops, ...
    'expectedDurationSec', expectedDurationSec, ...
    'prepareElapsedSec', prepareElapsedSec, ...
    'runElapsedSec', runElapsedSec, ...
    'endToEndRealTimeFactor', runElapsedSec / expectedDurationSec, ...
    'completionOverrunSec', runElapsedSec - expectedDurationSec, ...
    'mode', state.mode, ...
    'selectedProtocols', {selectedProtocols}, ...
    'winnersMatch', winnersMatch, ...
    'allCheckpointsReached', allCheckpointsReached, ...
    'checkpointResults', checkpointResults, ...
    'intervals', intervals, ...
    'maxObservedQueueSec', max(queueHistory, [], 'omitnan'), ...
    'finalQueueSec', state.decoderPipelineQueueSec, ...
    'maxInputLagSec', state.maxInputLagSec, ...
    'maxProducerLagSec', state.maxProducerLagSec, ...
    'maxDdcInputQueueSec', state.maxDdcInputQueueSec, ...
    'maxDdcResultQueueSec', state.maxDdcResultQueueSec, ...
    'spectrumDroppedChunks', state.spectrumDroppedChunks, ...
    'streamingRealtimePass', streamingRealtimePass, ...
    'strictOfflinePass', strictOfflinePass, ...
    'log', {state.log});
if options.Verbose
    fprintf(['Long realtime result: mode=%s, protocols=%s, ', ...
        'logical=%.3f s, wall=%.3f s, RTF=%.6f, overrun=%+.3f s, ', ...
        'queue max/final=%.3f/%.3f s, streaming=%d, strict=%d.\n'], ...
        state.mode, strjoin(selectedProtocols, '/'), ...
        expectedDurationSec, runElapsedSec, ...
        report.endToEndRealTimeFactor, report.completionOverrunSec, ...
        report.maxObservedQueueSec, report.finalQueueSec, ...
        report.streamingRealtimePass, report.strictOfflinePass);
    for k = 1:numel(intervals)
        item = intervals(k);
        fprintf(['  %.0f-%.0f s: logical rate %.6fx, queue ', ...
            'mean/p95/max %.4f/%.4f/%.4f s, slope %+.6f s/s, ', ...
            'latency slope %+.6f s/s.\n'], ...
            item.startLogicalSec, item.endLogicalSec, item.logicalRate, ...
            item.queueMeanSec, item.queueP95Sec, item.queueMaxSec, ...
            item.queueSlopeSecPerSec, ...
            item.wallMinusLogicalSlopeSecPerSec);
    end
end
app.Close();
clear cleanup;
end

function result = checkpointFromState(targetSec, wallSec, logicalSec, state)
result = emptyCheckpoint();
result.targetLogicalSec = targetSec;
result.actualLogicalSec = logicalSec;
result.wallSec = wallSec;
result.wallMinusLogicalSec = wallSec - logicalSec;
result.currentQueueSec = state.decoderPipelineQueueSec;
result.maxInputLagSec = state.maxInputLagSec;
result.maxDdcInputQueueSec = state.maxDdcInputQueueSec;
result.maxDdcResultQueueSec = state.maxDdcResultQueueSec;
result.pduCount = numel(state.pdus);
result.mode = state.mode;
if ~isempty(state.scanner)
    result.selectedProtocols = state.scanner.selectedProtocols;
end
end

function printCheckpoint(result)
fprintf(['Checkpoint %.0f s: logical %.3f, wall %.3f, wall-logical ', ...
    '%+.3f, queue %.3f, max lag %.3f, winners=%s, PDUs=%d.\n'], ...
    result.targetLogicalSec, result.actualLogicalSec, result.wallSec, ...
    result.wallMinusLogicalSec, result.currentQueueSec, ...
    result.maxInputLagSec, ...
    strjoin(result.selectedProtocols, '/'), result.pduCount);
end

function result = intervalStats(startSec, endSec, wall, logical, queue, lag)
mask = logical >= startSec & logical <= endSec;
result = emptyInterval();
result.startLogicalSec = startSec;
result.endLogicalSec = endSec;
if nnz(mask) < 2, return; end
xLogical = logical(mask);
xWall = wall(mask);
xQueue = queue(mask);
xLag = lag(mask);
logicalFit = polyfit(xWall, xLogical, 1);
queueFit = polyfit(xLogical, xQueue, 1);
lagFit = polyfit(xLogical, xLag, 1);
result.logicalRate = logicalFit(1);
result.queueMeanSec = mean(xQueue);
result.queueP95Sec = percentile(xQueue, 0.95);
result.queueMaxSec = max(xQueue);
result.queueStartSec = xQueue(1);
result.queueEndSec = xQueue(end);
result.queueSlopeSecPerSec = queueFit(1);
result.wallMinusLogicalSlopeSecPerSec = lagFit(1);
result.sampleCount = nnz(mask);
end

function value = percentile(values, fraction)
values = sort(values(:));
index = max(1, min(numel(values), ceil(fraction * numel(values))));
value = values(index);
end

function value = emptyCheckpoint()
value = struct( ...
    'targetLogicalSec', 0, ...
    'actualLogicalSec', 0, ...
    'wallSec', 0, ...
    'wallMinusLogicalSec', 0, ...
    'currentQueueSec', 0, ...
    'maxInputLagSec', 0, ...
    'maxDdcInputQueueSec', 0, ...
    'maxDdcResultQueueSec', 0, ...
    'pduCount', 0, ...
    'mode', '', ...
    'selectedProtocols', {cell(0, 1)});
end

function value = emptyInterval()
value = struct( ...
    'startLogicalSec', 0, ...
    'endLogicalSec', 0, ...
    'logicalRate', NaN, ...
    'queueMeanSec', NaN, ...
    'queueP95Sec', NaN, ...
    'queueMaxSec', NaN, ...
    'queueStartSec', NaN, ...
    'queueEndSec', NaN, ...
    'queueSlopeSecPerSec', NaN, ...
    'wallMinusLogicalSlopeSecPerSec', NaN, ...
    'sampleCount', 0);
end

function root = projectRoot()
root = fileparts(fileparts(mfilename('fullpath')));
end
