function report = runTetraStreaming()
%RUNTETRASTREAMING Validate causal TETRA DMO state across IQ chunks.
path = fullfile(pybackend.defaultPythonRoot(), 'data', ...
    'tetra_dmo_20240413_430050000_baseband.wav');
if exist(path, 'file') ~= 2
    fprintf('[SKIP] TETRA streaming sample is not present.\n');
    report = struct('skipped', true);
    return;
end
fs = common.detectSampleRate(path);
allIq = common.readRawIq(path);
base = round(5.15 * fs);
iq = allIq(base+1:min(numel(allIq), base + round(2.0 * fs)));
cfg = tetra.config();

timer = tic;
context = struct( ...
    'activeStartSec', double(base) / fs, ...
    'activeEndSec', double(base + numel(iq)) / fs);
[offlinePdus, offlineDiagnostics] = ...
    tetra.decodeIqWindow(iq, fs, cfg, context);
offlineElapsed = toc(timer);

scheduleA = round(fs .* [0.037 0.083 0.211 0.059 0.127]);
scheduleB = round(fs .* [0.200 0.200 0.200]);
[streamA, samplesA, stateA, elapsedA] = ...
    decodeChunks(iq, fs, uint64(base), cfg, scheduleA);
[streamB, samplesB, stateB, elapsedB] = ...
    decodeChunks(iq, fs, uint64(base), cfg, scheduleB);
keysA = signatures(streamA);
keysB = signatures(streamB);
assertSameKeys(keysA, keysB, ...
    'TETRA streaming PDU output changed with IQ chunk boundaries.');
assert(isequal(samplesA, samplesB), ...
    'TETRA streaming source positions changed with IQ chunk boundaries.');
assert(isequal(sort(signatures(streamA)), ...
    sort(signatures(offlinePdus))), ...
    'TETRA streaming output differs semantically from offline decode.');
assert(stateA.frameState.validControlPduCount > 0);
assert(stateA.frameState.confirmedBurstCount == ...
    offlineDiagnostics.slots.confirmedCount);
assert(stateA.maxMatchedBufferSamples < ...
    uint64(round(1.0 * cfg.frontendSampleRateHz)));
assert(stateA.maxBitBufferBits < ...
    uint64(round(1.0 * 2 * cfg.symbolRateHz)));
assert(stateB.maxMatchedBufferSamples < ...
    uint64(round(1.0 * cfg.frontendSampleRateHz)));

% Exercise the normal 2.5 MHz DDC output rate and independent chunking.
tunedFs = 125000;
tunedIq = common.resampleTo(iq, fs, tunedFs);
[tunedA, tunedSamplesA] = decodeChunks( ...
    tunedIq, tunedFs, uint64(0), cfg, ...
    round(tunedFs .* [0.041 0.097 0.203]));
[tunedB, tunedSamplesB] = decodeChunks( ...
    tunedIq, tunedFs, uint64(0), cfg, ...
    round(tunedFs .* [0.125 0.250]));
assert(~isempty(tunedA));
assert(isequal(signatures(tunedA), signatures(tunedB)));
assert(isequal(tunedSamplesA, tunedSamplesB));

durationSec = numel(iq) / fs;
report = struct( ...
    'skipped', false, ...
    'offlinePduCount', numel(offlinePdus), ...
    'streamPduCount', numel(streamA), ...
    'streamValidControlPduCount', ...
        double(stateA.frameState.validControlPduCount), ...
    'streamConfirmedBurstCount', ...
        double(stateA.frameState.confirmedBurstCount), ...
    'offlineElapsedSec', offlineElapsed, ...
    'streamElapsedSec', elapsedA, ...
    'secondScheduleElapsedSec', elapsedB, ...
    'streamRealtimeFactor', elapsedA / durationSec, ...
    'warmRealtimeFactor', elapsedB / durationSec, ...
    'maxMatchedBufferSamples', ...
        double(stateA.maxMatchedBufferSamples), ...
    'maxBitBufferBits', double(stateA.maxBitBufferBits));
fprintf(['TETRA streaming: offline=%d PDU, stream=%d PDU, ', ...
    'control=%d, bursts=%d, cold/warm RTF=%.3f/%.3f.\n'], ...
    report.offlinePduCount, report.streamPduCount, ...
    report.streamValidControlPduCount, ...
    report.streamConfirmedBurstCount, ...
    report.streamRealtimeFactor, report.warmRealtimeFactor);
end

function [pdus, sourceSamples, state, elapsed] = ...
        decodeChunks(iq, fs, sourceStart, cfg, schedule)
state = tetra.streamInit(fs, cfg, 'SourceSampleStart', sourceStart);
pdus = struct([]);
sourceSamples = zeros(0, 1, 'uint64');
position = 1;
sequence = uint64(0);
scheduleIndex = 1;
timer = tic;
while position <= numel(iq)
    count = min(schedule(scheduleIndex), numel(iq) - position + 1);
    chunk = radio.stream.makeIqChunk( ...
        iq(position:position+count-1), fs, ...
        sourceStart + uint64(position-1), ...
        'SequenceNumber', sequence);
    [state, output] = tetra.streamDecodeChunk(state, chunk);
    pdus = appendPdus(pdus, output.pdus);
    sourceSamples = [sourceSamples; output.sourceSamples(:)]; %#ok<AGROW>
    position = position + count;
    sequence = sequence + uint64(1);
    scheduleIndex = mod(scheduleIndex, numel(schedule)) + 1;
end
[state, output] = tetra.streamFlush(state);
pdus = appendPdus(pdus, output.pdus);
sourceSamples = [sourceSamples; output.sourceSamples(:)];
elapsed = toc(timer);
pdus = tetra.postprocess(pdus);
end

function keys = signatures(pdus)
keys = cell(numel(pdus), 1);
for k = 1:numel(pdus)
    keys{k} = jsonencode({ ...
        pdus(k).type, pdus(k).src, pdus(k).dst, pdus(k).flco, ...
        radio.getNestedField(pdus(k), 'extra.logical_channel', ''), ...
        radio.getNestedField(pdus(k), 'extra.block_name', ''), ...
        radio.getNestedField(pdus(k), 'extra.frame_number', []), ...
        radio.getNestedField(pdus(k), 'extra.slot_number', [])});
end
end

function values = appendPdus(values, items)
if isempty(items), return; end
if isempty(values)
    values = items;
else
    values(end+1:end+numel(items)) = items;
end
end

function assertSameKeys(first, second, message)
if isequal(first, second), return; end
limit = min(numel(first), numel(second));
index = find(~strcmp(first(1:limit), second(1:limit)), 1);
if isempty(index), index = limit + 1; end
firstValue = '<missing>';
secondValue = '<missing>';
if index <= numel(first), firstValue = first{index}; end
if index <= numel(second), secondValue = second{index}; end
error('tests:tetraStreaming:ChunkBoundary', ...
    '%s Counts %d/%d, first mismatch %d: %s <> %s', ...
    message, numel(first), numel(second), index, ...
    firstValue, secondValue);
end
