function line = formatPdu(pdu, foStr)
%FORMATPDU Format a DMR PDU.
if nargin < 2
    foStr = '';
end
if strcmp(char(radio.getField(pdu, 'type', '')), 'DMR_CALL')
    line = formatCall(pdu, foStr);
    return;
end
line = sprintf('[%-12s] PROTO=%s SRC=%s DST=%s FLCO=%s FID=%s%s', ...
    char(radio.getField(pdu, 'type', '')), ...
    char(radio.getField(pdu, 'protocol', 'DMR')), ...
    valueToText(radio.getField(pdu, 'src', 0)), ...
    valueToText(radio.getField(pdu, 'dst', 0)), ...
    valueToText(radio.getField(pdu, 'flco', '')), ...
    valueToText(radio.getField(pdu, 'fid', '')), ...
    foStr);
end

function line = formatCall(pdu, foStr)
extra = radio.getField(pdu, 'extra', struct());
callType = upper(char(radio.getNestedField(extra, 'call_type', 'unknown')));
colorCode = radio.getNestedField(extra, 'color_code', []);
if isempty(colorCode)
    cc = '';
else
    cc = sprintf(' CC=%s', valueToText(colorCode));
end
duration = radio.getNestedField(extra, 'duration_s', []);
if isempty(duration)
    dur = '';
else
    dur = sprintf(' DUR=%ss', valueToText(duration));
end
line = sprintf('[%-12s] PROTO=DMR CALL=%s SRC=%s DST=%s%s FLCO=%s FID=%s%s SIG=%s LATE=%s CSBK=%s CLOSED=%s%s', ...
    char(radio.getField(pdu, 'type', '')), ...
    callType, ...
    valueToText(radio.getField(pdu, 'src', 0)), ...
    valueToText(radio.getField(pdu, 'dst', 0)), ...
    cc, ...
    valueToText(radio.getField(pdu, 'flco', '')), ...
    valueToText(radio.getField(pdu, 'fid', '')), ...
    dur, ...
    valueToText(radio.getNestedField(extra, 'signalling_count', 0)), ...
    valueToText(radio.getNestedField(extra, 'late_entry_count', 0)), ...
    valueToText(radio.getNestedField(extra, 'csbk_count', 0)), ...
    valueToText(radio.getNestedField(extra, 'closed_by', '')), ...
    foStr);
end

function text = valueToText(value)
if isnumeric(value)
    if isscalar(value)
        text = num2str(value);
    else
        text = mat2str(value);
    end
elseif isstring(value)
    text = char(value);
elseif ischar(value)
    text = value;
else
    text = char(string(value));
end
end
