function state = frameDecoderInit(cfg)
%FRAMEDECODERINIT Initialize persistent DMR burst/session state.
if nargin < 1 || isempty(cfg), cfg = dmr.config(); end
state = struct( ...
    'cfg', cfg, ...
    'session', dmr.sessionInit(), ...
    'seenKeys', {cell(0, 1)}, ...
    'candidateCount', uint64(0), ...
    'decodedPduCount', uint64(0), ...
    'strongPduCount', uint64(0), ...
    'finalized', false);
end
