function report = frameDecoderReport(state)
%FRAMEDECODERREPORT Summarize persistent DMR frame state.
report = struct( ...
    'candidateCount', double(state.candidateCount), ...
    'decodedPduCount', double(state.decodedPduCount), ...
    'strongPduCount', double(state.strongPduCount), ...
    'seenKeyCount', numel(state.seenKeys), ...
    'sessionActive', logical(state.session.active), ...
    'finalized', logical(state.finalized));
end
