function y = frontend(iqDec, sampleRate, cfg)
%FRONTEND Native MATLAB DMR/C4FM 4FSK frontend.
if nargin < 2 || isempty(sampleRate)
    sampleRate = 48000.0;
end
if nargin < 3 || isempty(cfg)
    cfg = dmr.config();
end
y = common.fskFrontend(iqDec, ...
    'Fo', 0.0, ...
    'Fs', sampleRate, ...
    'Cutoff', cfg.frontendCutoffHz, ...
    'NTaps', cfg.frontendTaps, ...
    'DevNominal', cfg.nominalDeviationHz, ...
    'MinSamples', cfg.frontendMinSamples, ...
    'PsdNperseg', cfg.frontendPsdNperseg);
end

