function session = sessionInit()
%SESSIONINIT Initialize lightweight DMR call summary state.
session = struct( ...
    'active', false, ...
    'src', 0, ...
    'dst', 0, ...
    'flco', '', ...
    'fid', '', ...
    'callType', 'unknown', ...
    'colorCode', [], ...
    'firstSample', [], ...
    'lastSample', [], ...
    'signallingCount', 0, ...
    'lateEntryCount', 0, ...
    'csbkCount', 0);
end
