function spec = spec()
%SPEC DMR ProtocolSpec-compatible adapter.
spec = struct( ...
    'name', 'DMR', ...
    'aliases', {{'dmr'}}, ...
    'config', dmr.config(), ...
    'frontendKey', 'c4fm_4fsk', ...
    'frontendFcn', @dmr.frontend, ...
    'decodeFcn', @dmr.decode, ...
    'postprocessFcn', @dmr.postprocess, ...
    'dedupFcn', @dmr.dedupKey, ...
    'formatterFcn', @dmr.formatPdu, ...
    'scanMode', 'narrowband_4fsk', ...
    'targetSampleRateHz', 48000.0, ...
    'scanIqFcn', [], ...
    'supportsBlindSearch', true, ...
    'supportsFrequencyOffsets', true, ...
    'defaultBasebandScan', true, ...
    'defaultFreqListScan', true, ...
    'defaultBlindSearch', true);
end
