function spec = spec()
%SPEC DMR ProtocolSpec-compatible adapter.
spec = struct( ...
    'name', 'DMR', ...
    'aliases', {{'dmr'}}, ...
    'config', dmr.config(), ...
    'frontendFcn', @dmr.frontend, ...
    'decodeFcn', @dmr.decode, ...
    'postprocessFcn', @dmr.postprocess, ...
    'dedupFcn', @dmr.dedupKey, ...
    'formatterFcn', @dmr.formatPdu, ...
    'targetSampleRateHz', 48000.0, ...
    'scanIqFcn', []);
end
