function state = ddcInit(inputSampleRateHz, frequencyOffsetHz, varargin)
%DDCINIT Initialize a stateful known-carrier digital downconverter.
p = inputParser;
p.addParameter('Config', radio.tuned.defaultConfig());
p.addParameter('InputCenterFrequencyHz', 0);
p.addParameter('TargetCenterFrequencyHz', []);
p.addParameter('ChannelId', 1);
p.addParameter('MixerMode', 'internal');
p.parse(varargin{:});

cfg = p.Results.Config;
radio.tuned.validateConfig(cfg, inputSampleRateHz);
validateattributes(frequencyOffsetHz, {'numeric'}, ...
    {'scalar', 'real', 'finite'}, mfilename, 'frequencyOffsetHz');
inputCenterFrequencyHz = p.Results.InputCenterFrequencyHz;
validateattributes(inputCenterFrequencyHz, {'numeric'}, ...
    {'scalar', 'real', 'finite'}, mfilename, 'InputCenterFrequencyHz');
targetCenterFrequencyHz = p.Results.TargetCenterFrequencyHz;
if isempty(targetCenterFrequencyHz)
    targetCenterFrequencyHz = inputCenterFrequencyHz + frequencyOffsetHz;
end
validateattributes(targetCenterFrequencyHz, {'numeric'}, ...
    {'scalar', 'real', 'finite'}, mfilename, 'TargetCenterFrequencyHz');

nyquistHz = inputSampleRateHz / 2;
if abs(frequencyOffsetHz) + cfg.stopbandFrequencyHz >= nyquistHz
    error('radio:tuned:ddcInit:FrequencyOutsideInput', ...
        ['The requested channel plus its anti-alias transition band must ', ...
         'remain inside the captured Nyquist band.']);
end
mixerMode = lower(char(p.Results.MixerMode));
if ~any(strcmp(mixerMode, {'internal', 'external'}))
    error('radio:tuned:ddcInit:MixerMode', ...
        'MixerMode must be internal or external.');
end
if strcmp(mixerMode, 'external')
    converterCenterFrequencyHz = 0;
else
    converterCenterFrequencyHz = frequencyOffsetHz;
end

decimationFactor = round(inputSampleRateHz / cfg.outputSampleRateHz);
inputBlockSamples = max(decimationFactor, ...
    round(cfg.chunkDurationSec * inputSampleRateHz));
inputBlockSamples = ceil(inputBlockSamples / decimationFactor) * ...
    decimationFactor;
converter = dsp.DigitalDownConverter( ...
    'SampleRate', double(inputSampleRateHz), ...
    'DecimationFactor', decimationFactor, ...
    'Bandwidth', double(cfg.channelBandwidthHz), ...
    'StopbandFrequencySource', 'Property', ...
    'StopbandFrequency', double(cfg.stopbandFrequencyHz), ...
    'PassbandRipple', double(cfg.passbandRippleDb), ...
    'StopbandAttenuation', double(cfg.stopbandAttenuationDb), ...
    'CenterFrequency', double(converterCenterFrequencyHz));

state = struct( ...
    'converter', converter, ...
    'config', cfg, ...
    'inputSampleRateHz', double(inputSampleRateHz), ...
    'outputSampleRateHz', double(cfg.outputSampleRateHz), ...
    'decimationFactor', double(decimationFactor), ...
    'inputBlockSamples', double(inputBlockSamples), ...
    'frequencyOffsetHz', double(frequencyOffsetHz), ...
    'mixerMode', mixerMode, ...
    'mixerStep', exp(-1i * 2 * pi * double(frequencyOffsetHz) / ...
        double(inputSampleRateHz)), ...
    'mixerPhase', complex(1), ...
    'inputCenterFrequencyHz', double(inputCenterFrequencyHz), ...
    'targetCenterFrequencyHz', double(targetCenterFrequencyHz), ...
    'channelId', p.Results.ChannelId, ...
    'pendingIq', complex(zeros(0, 1)), ...
    'pendingSourceSampleStart', uint64(0), ...
    'expectedInputSample', [], ...
    'nextOutputSample', uint64(0), ...
    'nextSequenceNumber', uint64(0), ...
    'continuityGeneration', uint64(0), ...
    'inputSamplesReceived', uint64(0), ...
    'inputSamplesConverted', uint64(0), ...
    'outputSamplesProduced', uint64(0));
end
