function metric = decoderMetricFromCoordinatorOutput(output)
%DECODERMETRICFROMCOORDINATOROUTPUT Extract one completed locked decode.
metric = repmat(struct( ...
    'protocol', '', 'computeSec', 0, 'dispatchSec', 0, ...
    'newPduCount', 0, 'mode', ''), 0, 1);
decoder = radio.getNestedField(output, 'decoder', []);
if ~isstruct(decoder) || isempty(decoder) || ...
        ~isfield(decoder, 'elapsedSec')
    return;
end
metric = struct( ...
    'protocol', char(decoder.protocol), ...
    'computeSec', double(decoder.elapsedSec), ...
    'dispatchSec', double(radio.getNestedField( ...
        decoder, 'dispatch.totalElapsedSec', decoder.elapsedSec)), ...
    'newPduCount', double(decoder.newPduCount), ...
    'mode', char(radio.getNestedField( ...
        decoder, 'dispatch.mode', '')));
end
