function [basebandIq, report] = extractFile(path, targetFrequencyHz, varargin)
%EXTRACTFILE Extract one known RF carrier as continuous 120 kS/s baseband.
p = inputParser;
p.addParameter('SampleRate', []);
p.addParameter('CenterFrequencyHz', []);
p.addParameter('IqDType', 'int16');
p.addParameter('HeaderBytes', []);
p.addParameter('Config', radio.tuned.defaultConfig());
p.addParameter('ChannelId', 1);
p.addParameter('ShowProgress', false);
p.parse(varargin{:});

validateattributes(targetFrequencyHz, {'numeric'}, ...
    {'scalar', 'real', 'finite'}, mfilename, 'targetFrequencyHz');
metadata = radio.tuned.captureInfo(path, ...
    'SampleRate', p.Results.SampleRate, ...
    'CenterFrequencyHz', p.Results.CenterFrequencyHz, ...
    'IqDType', p.Results.IqDType, ...
    'HeaderBytes', p.Results.HeaderBytes);
frequencyOffsetHz = targetFrequencyHz - metadata.centerFrequencyHz;
state = radio.tuned.ddcInit( ...
    metadata.sampleRateHz, frequencyOffsetHz, ...
    'Config', p.Results.Config, ...
    'InputCenterFrequencyHz', metadata.centerFrequencyHz, ...
    'TargetCenterFrequencyHz', targetFrequencyHz, ...
    'ChannelId', p.Results.ChannelId);
source = radio.stream.fileSourceInit(path, ...
    'SampleRateHz', metadata.sampleRateHz, ...
    'ChunkDurationSec', p.Results.Config.chunkDurationSec, ...
    'DType', p.Results.IqDType, ...
    'HeaderBytes', metadata.headerBytes, ...
    'ChannelId', p.Results.ChannelId, ...
    'CenterFrequencyHz', metadata.centerFrequencyHz);

parts = cell(0, 1);
timerToken = tic;
nextProgress = 0.1;
try
    done = false;
    while ~done
        [source, inputChunk, done] = radio.stream.fileSourceRead(source);
        if isempty(inputChunk), break; end
        [state, outputChunk] = radio.tuned.ddcFeed(state, inputChunk);
        if ~isempty(outputChunk)
            parts{end+1, 1} = outputChunk.iq; %#ok<AGROW>
        end
        if p.Results.ShowProgress && metadata.totalSamples > 0
            fraction = double(source.nextSample) / ...
                double(metadata.totalSamples);
            if fraction >= nextProgress || done
                fprintf('Known-carrier DDC: %5.1f%%  %.6f MHz -> baseband\n', ...
                    100 * fraction, targetFrequencyHz / 1e6);
                nextProgress = nextProgress + 0.1;
            end
        end
    end
    inputSampleCount = source.nextSample;
    [state, flushChunk] = radio.tuned.ddcFlush(state);
    if ~isempty(flushChunk)
        parts{end+1, 1} = flushChunk.iq;
        flushOutputSamples = uint64(numel(flushChunk.iq));
    else
        flushOutputSamples = uint64(0);
    end
    radio.stream.fileSourceClose(source);
catch ME
    source = radio.stream.fileSourceClose(source); %#ok<NASGU>
    rethrow(ME);
end
elapsedSec = toc(timerToken);

if isempty(parts)
    basebandIq = complex(zeros(0, 1));
else
    basebandIq = vertcat(parts{:});
end
filterOrders = getFilterOrders(state.converter);
report = struct( ...
    'path', char(path), ...
    'format', metadata.format, ...
    'headerBytes', metadata.headerBytes, ...
    'inputSampleRateHz', metadata.sampleRateHz, ...
    'outputSampleRateHz', state.outputSampleRateHz, ...
    'inputCenterFrequencyHz', metadata.centerFrequencyHz, ...
    'targetFrequencyHz', double(targetFrequencyHz), ...
    'frequencyOffsetHz', frequencyOffsetHz, ...
    'decimationFactor', state.decimationFactor, ...
    'inputBlockSamples', state.inputBlockSamples, ...
    'decimationFactors', getDecimationFactors(state.converter), ...
    'filterOrders', filterOrders, ...
    'channelBandwidthHz', p.Results.Config.channelBandwidthHz, ...
    'stopbandFrequencyHz', p.Results.Config.stopbandFrequencyHz, ...
    'inputSampleCount', uint64(inputSampleCount), ...
    'outputSampleCount', uint64(numel(basebandIq)), ...
    'filterFlushOutputSamples', flushOutputSamples, ...
    'inputDurationSec', double(inputSampleCount) / metadata.sampleRateHz, ...
    'elapsedSec', elapsedSec, ...
    'realTimeFactor', elapsedSec / max(metadata.durationSec, eps), ...
    'metadata', metadata);
end
