function [scanner, report] = multiStreamScannerFinalize(scanner, varargin)
%MULTISTREAMSCANNERFINALIZE Flush and report every selected carrier.
p = inputParser;
p.addParameter('SilenceDurationSec', []);
p.addParameter('WaitForTasks', true);
p.addParameter('TaskTimeoutSec', 120);
p.addParameter('PollIntervalSec', 0.020);
p.parse(varargin{:});
if scanner.finalized
    report = buildReport(scanner, cell(scanner.channelCount, 1));
    return;
end

channelReports = cell(scanner.channelCount, 1);
for k = 1:scanner.channelCount
    priorPduCount = numel(scanner.channels{k}.pdus);
    priorEpochCount = numel(scanner.channels{k}.closedEpochs);
    [scanner.channels{k}, channelReports{k}] = ...
        radio.tuned.streamScannerFinalize(scanner.channels{k}, ...
        'SilenceDurationSec', p.Results.SilenceDurationSec, ...
        'WaitForTasks', p.Results.WaitForTasks, ...
        'TaskTimeoutSec', p.Results.TaskTimeoutSec, ...
        'PollIntervalSec', p.Results.PollIntervalSec);
    if numel(scanner.channels{k}.pdus) > priorPduCount
        scanner.pdus = appendStruct(scanner.pdus, ...
            scanner.channels{k}.pdus(priorPduCount+1:end));
    end
    if numel(scanner.channels{k}.closedEpochs) > priorEpochCount
        scanner.closedEpochs = appendStruct(scanner.closedEpochs, ...
            scanner.channels{k}.closedEpochs(priorEpochCount+1:end));
    end
end
scanner.finalized = true;
report = buildReport(scanner, channelReports);
end

function report = buildReport(scanner, channelReports)
selected = cell(scanner.channelCount, 1);
states = cell(scanner.channelCount, 1);
backlogSamples = zeros(scanner.channelCount, 1, 'uint64');
for k = 1:scanner.channelCount
    states{k} = scanner.channels{k}.coordinator.state;
    selected{k} = scanner.channels{k}.lastSelectedProtocol;
    decoder = scanner.channels{k}.coordinator.decoderState;
    if ~isempty(decoder)
        backlogSamples(k) = scanner.channels{k}.basebandNextSample - ...
            decoder.lastProcessedEndSample;
    end
end
report = struct( ...
    'channelCount', scanner.channelCount, ...
    'frequencyOffsetsHz', scanner.frequencyOffsetsHz, ...
    'targetFrequenciesHz', scanner.targetFrequenciesHz, ...
    'states', {states}, ...
    'selectedProtocols', {selected}, ...
    'decoderBacklogSamples', backlogSamples, ...
    'inputSampleCount', scanner.inputSampleCount, ...
    'feedCount', scanner.feedCount, ...
    'pduCount', numel(scanner.pdus), ...
    'pdus', scanner.pdus, ...
    'closedEpochs', scanner.closedEpochs, ...
    'channelReports', {channelReports}, ...
    'elapsedSec', toc(scanner.timerToken), ...
    'finalized', scanner.finalized);
end

function value = appendStruct(value, items)
if isempty(items), return; end
if isempty(value), value = items(:); else, value = [value(:); items(:)]; end
end
