function [scanner, output] = multiStreamScannerFeed(scanner, widebandChunk)
%MULTISTREAMSCANNERFEED Send one input block to every selected carrier.
if radio.getField(scanner, 'externalBaseband', false)
    error('radio:tuned:multiStreamScannerFeed:ExternalBaseband', ...
        ['This scanner receives externally computed basebands; call ', ...
         'multiStreamScannerFeedBasebands instead.']);
end
if scanner.finalized
    error('radio:tuned:multiStreamScannerFeed:Finalized', ...
        'A finalized multi-carrier scanner cannot accept more input.');
end
radio.stream.validateIqChunk(widebandChunk);
if widebandChunk.sampleRateHz ~= scanner.inputSampleRateHz
    error('radio:tuned:multiStreamScannerFeed:SampleRate', ...
        'Wideband input sample rate changed.');
end
if widebandChunk.centerFrequencyHz ~= scanner.inputCenterFrequencyHz
    error('radio:tuned:multiStreamScannerFeed:CenterFrequency', ...
        'Retuning requires a new multi-carrier scanner.');
end

feedToken = tic;
channelOutputs = cell(scanner.channelCount, 1);
newPdus = struct([]);
closedEpochs = repmat(radio.stream.newEpoch(0, 0, 0, 0), 0, 1);
basebandChunks = cell(scanner.channelCount, 1);
channelElapsedSec = zeros(scanner.channelCount, 1);
ddcToken = tic;
if scanner.useFusedDdc
    [scanner.fusedDdc, basebandChunks] = ...
        radio.tuned.multiDdcFeed(scanner.fusedDdc, widebandChunk);
end
ddcElapsedSec = toc(ddcToken);
if scanner.useFusedDdc
    [scanner, output] = radio.tuned.multiStreamScannerFeedBasebands( ...
        scanner, widebandChunk, basebandChunks, ...
        'DdcElapsedSec', ddcElapsedSec);
    return;
end
[deferLockedDecode, admission] = ...
    radio.tuned.multiStreamLockedDecodeDeferrals(scanner);
scanner.lastLockedDecodeAdmission = admission;
if ~isempty(admission.admittedIndices)
    interval = uint64(scanner.persistentActorStartIntervalFeeds);
    scanner.nextPersistentActorStartFeed = scanner.feedCount + interval;
end
for k = 1:scanner.channelCount
    scanner.channels{k}.coordinator.deferLockedDecode = ...
        deferLockedDecode(k);
end
for k = 1:scanner.channelCount
    channelToken = tic;
    [scanner.channels{k}, channelOutputs{k}] = ...
        radio.tuned.streamScannerFeed(scanner.channels{k}, widebandChunk);
    ddcElapsedSec = ddcElapsedSec + toc(channelToken);
    channelElapsedSec(k) = toc(channelToken);
    decoderMetrics = radio.getField( ...
        channelOutputs{k}, 'decoderMetrics', struct([]));
    for decoderIndex = 1:numel(decoderMetrics)
        decoderMetric = decoderMetrics(decoderIndex);
        scanner.decoderCompletionCount(k) = ...
            scanner.decoderCompletionCount(k) + uint64(1);
        computeSec = double(decoderMetric.computeSec);
        dispatchSec = double(decoderMetric.dispatchSec);
        scanner.totalDecoderComputeSec(k) = ...
            scanner.totalDecoderComputeSec(k) + computeSec;
        scanner.maxDecoderComputeSec(k) = max( ...
            scanner.maxDecoderComputeSec(k), computeSec);
        scanner.totalDecoderDispatchSec(k) = ...
            scanner.totalDecoderDispatchSec(k) + dispatchSec;
        scanner.maxDecoderDispatchSec(k) = max( ...
            scanner.maxDecoderDispatchSec(k), dispatchSec);
    end
    newPdus = appendStruct(newPdus, channelOutputs{k}.newPdus);
    closedEpochs = appendStruct( ...
        closedEpochs, channelOutputs{k}.closedEpochs);
end
scanner.pdus = appendStruct(scanner.pdus, newPdus);
scanner.closedEpochs = appendStruct(scanner.closedEpochs, closedEpochs);
scanner.lastOutputs = channelOutputs;
scanner.feedCount = scanner.feedCount + uint64(1);
scanner.inputSampleCount = scanner.inputSampleCount + ...
    uint64(numel(widebandChunk.iq));
scanner.lastDdcElapsedSec = ddcElapsedSec;
scanner.maxDdcElapsedSec = max(scanner.maxDdcElapsedSec, ddcElapsedSec);
scanner.totalDdcElapsedSec = scanner.totalDdcElapsedSec + ddcElapsedSec;
scanner.lastFeedElapsedSec = toc(feedToken);
if scanner.lastFeedElapsedSec > scanner.maxFeedElapsedSec
    scanner.maxFeedElapsedSec = scanner.lastFeedElapsedSec;
    dispatch = cell(scanner.channelCount, 1);
    for channelIndex = 1:scanner.channelCount
        dispatch{channelIndex} = radio.getNestedField( ...
            channelOutputs{channelIndex}, ...
            'coordinator.decoder.dispatch', struct());
    end
    scanner.maxFeedBreakdown = struct( ...
        'feedIndex', scanner.feedCount, ...
        'ddcElapsedSec', ddcElapsedSec, ...
        'channelElapsedSec', channelElapsedSec, ...
        'decoderDispatch', {dispatch}, ...
        'states', {cellfun(@(item) item.state, channelOutputs, ...
            'UniformOutput', false)}, ...
        'selectedProtocols', {cellfun(@(item) item.selectedProtocol, ...
            channelOutputs, 'UniformOutput', false)});
end
scanner.totalFeedElapsedSec = scanner.totalFeedElapsedSec + ...
    scanner.lastFeedElapsedSec;

output = struct( ...
    'channelOutputs', {channelOutputs}, ...
    'states', {cellfun(@(item) item.state, channelOutputs, ...
        'UniformOutput', false)}, ...
    'selectedProtocols', {cellfun(@(item) item.selectedProtocol, ...
        channelOutputs, 'UniformOutput', false)}, ...
    'newPdus', newPdus, ...
    'closedEpochs', closedEpochs, ...
    'feedCount', scanner.feedCount, ...
    'inputSampleCount', scanner.inputSampleCount);
output.ddcElapsedSec = scanner.lastDdcElapsedSec;
output.feedElapsedSec = scanner.lastFeedElapsedSec;
output.useFusedDdc = scanner.useFusedDdc;
end

function value = appendStruct(value, items)
if isempty(items), return; end
if isempty(value), value = items(:); else, value = [value(:); items(:)]; end
end
