function [scanner, output] = multiStreamScannerFeedBasebands( ...
        scanner, widebandDescriptor, basebandChunks, varargin)
%MULTISTREAMSCANNERFEEDBASEBANDS Feed externally computed carrier chunks.
p = inputParser;
p.addParameter('DdcElapsedSec', 0);
p.parse(varargin{:});
if scanner.finalized
    error('radio:tuned:multiStreamScannerFeedBasebands:Finalized', ...
        'A finalized multi-carrier scanner cannot accept more input.');
end
widebandSampleCount = ...
    radio.stream.validateIqChunkDescriptor(widebandDescriptor);
if widebandDescriptor.sampleRateHz ~= scanner.inputSampleRateHz
    error('radio:tuned:multiStreamScannerFeedBasebands:SampleRate', ...
        'Wideband input sample rate changed.');
end
if widebandDescriptor.centerFrequencyHz ~= scanner.inputCenterFrequencyHz
    error('radio:tuned:multiStreamScannerFeedBasebands:CenterFrequency', ...
        'Retuning requires a new multi-carrier scanner.');
end
if ~iscell(basebandChunks)
    error('radio:tuned:multiStreamScannerFeedBasebands:BasebandType', ...
        'basebandChunks must be a cell array.');
end

feedToken = tic;
ddcElapsedSec = double(p.Results.DdcElapsedSec);
channelOutputs = cell(scanner.channelCount, 1);
newPdus = struct([]);
closedEpochs = repmat(radio.stream.newEpoch(0, 0, 0, 0), 0, 1);
channelElapsedSec = zeros(scanner.channelCount, 1);
[deferLockedDecode, admission] = ...
    radio.tuned.multiStreamLockedDecodeDeferrals(scanner);
scanner.lastLockedDecodeAdmission = admission;
if ~isempty(admission.admittedIndices)
    interval = uint64(scanner.persistentActorStartIntervalFeeds);
    scanner.nextPersistentActorStartFeed = scanner.feedCount + interval;
end
for k = 1:scanner.channelCount
    scanner.channels{k}.coordinator.deferLockedDecode = ...
        deferLockedDecode(k);
end
[processOrder, probeBudget] = probeStartPlan(scanner);
probeStarts = 0;
startedChannels = zeros(0, 1);
deferredChannels = zeros(0, 1);
for orderIndex = 1:numel(processOrder)
    k = processOrder(orderIndex);
    beforeRaceActive = ...
        ~isempty(scanner.channels{k}.coordinator.activeRace);
    deferProbe = probeStarts >= probeBudget;
    scanner.channels{k}.coordinator.deferProbeStart = deferProbe;
    if deferProbe
        deferredChannels(end+1, 1) = k; %#ok<AGROW>
    end
    channelToken = tic;
    basebandChunk = [];
    if k <= numel(basebandChunks), basebandChunk = basebandChunks{k}; end
    [scanner.channels{k}, channelOutputs{k}] = ...
        radio.tuned.streamScannerFeedBaseband( ...
            scanner.channels{k}, widebandDescriptor, basebandChunk);
    channelElapsedSec(k) = toc(channelToken);
    afterRaceActive = ...
        ~isempty(scanner.channels{k}.coordinator.activeRace);
    if ~beforeRaceActive && afterRaceActive
        probeStarts = probeStarts + 1;
        startedChannels(end+1, 1) = k; %#ok<AGROW>
        scanner.nextProbeStartChannel = uint64( ...
            mod(k, scanner.channelCount) + 1);
    end
    decoderMetrics = radio.getField( ...
        channelOutputs{k}, 'decoderMetrics', struct([]));
    for decoderIndex = 1:numel(decoderMetrics)
        decoderMetric = decoderMetrics(decoderIndex);
        scanner.decoderCompletionCount(k) = ...
            scanner.decoderCompletionCount(k) + uint64(1);
        computeSec = double(decoderMetric.computeSec);
        dispatchSec = double(decoderMetric.dispatchSec);
        scanner.totalDecoderComputeSec(k) = ...
            scanner.totalDecoderComputeSec(k) + computeSec;
        scanner.maxDecoderComputeSec(k) = max( ...
            scanner.maxDecoderComputeSec(k), computeSec);
        scanner.totalDecoderDispatchSec(k) = ...
            scanner.totalDecoderDispatchSec(k) + dispatchSec;
        scanner.maxDecoderDispatchSec(k) = max( ...
            scanner.maxDecoderDispatchSec(k), dispatchSec);
    end
    newPdus = appendStruct(newPdus, channelOutputs{k}.newPdus);
    closedEpochs = appendStruct( ...
        closedEpochs, channelOutputs{k}.closedEpochs);
end
scanner.lastProbeStartAdmission = struct( ...
    'budget', probeBudget, ...
    'processOrder', processOrder(:), ...
    'startedChannels', startedChannels, ...
    'deferredChannels', unique(deferredChannels, 'stable'));
scanner.pdus = appendStruct(scanner.pdus, newPdus);
scanner.closedEpochs = appendStruct(scanner.closedEpochs, closedEpochs);
scanner.lastOutputs = channelOutputs;
scanner.feedCount = scanner.feedCount + uint64(1);
scanner.inputSampleCount = scanner.inputSampleCount + widebandSampleCount;
scanner.lastDdcElapsedSec = ddcElapsedSec;
scanner.maxDdcElapsedSec = max(scanner.maxDdcElapsedSec, ddcElapsedSec);
scanner.totalDdcElapsedSec = scanner.totalDdcElapsedSec + ddcElapsedSec;
scanner.lastFeedElapsedSec = ddcElapsedSec + toc(feedToken);
if scanner.lastFeedElapsedSec > scanner.maxFeedElapsedSec
    scanner.maxFeedElapsedSec = scanner.lastFeedElapsedSec;
    dispatch = cell(scanner.channelCount, 1);
    for channelIndex = 1:scanner.channelCount
        dispatch{channelIndex} = radio.getNestedField( ...
            channelOutputs{channelIndex}, ...
            'coordinator.decoder.dispatch', struct());
    end
    scanner.maxFeedBreakdown = struct( ...
        'feedIndex', scanner.feedCount, ...
        'ddcElapsedSec', ddcElapsedSec, ...
        'channelElapsedSec', channelElapsedSec, ...
        'decoderDispatch', {dispatch}, ...
        'states', {cellfun(@(item) item.state, channelOutputs, ...
            'UniformOutput', false)}, ...
        'selectedProtocols', {cellfun(@(item) item.selectedProtocol, ...
            channelOutputs, 'UniformOutput', false)});
end
scanner.totalFeedElapsedSec = scanner.totalFeedElapsedSec + ...
    scanner.lastFeedElapsedSec;

output = struct( ...
    'channelOutputs', {channelOutputs}, ...
    'states', {cellfun(@(item) item.state, channelOutputs, ...
        'UniformOutput', false)}, ...
    'selectedProtocols', {cellfun(@(item) item.selectedProtocol, ...
        channelOutputs, 'UniformOutput', false)}, ...
    'newPdus', newPdus, ...
    'closedEpochs', closedEpochs, ...
    'feedCount', scanner.feedCount, ...
    'inputSampleCount', scanner.inputSampleCount, ...
    'ddcElapsedSec', scanner.lastDdcElapsedSec, ...
    'feedElapsedSec', scanner.lastFeedElapsedSec, ...
    'useFusedDdc', scanner.useFusedDdc, ...
    'externalBaseband', true);
end

function [order, budget] = probeStartPlan(scanner)
order = (1:scanner.channelCount).';
budget = inf;
if scanner.channelCount <= 1
    return;
end
mode = lower(char(scanner.channels{1}.coordinator.options.mode));
if ~any(strcmp(mode, {'auto', 'parallel'}))
    return;
end
budget = max(1, floor(scanner.maxProbeRaceStartsPerFeed));
first = min(scanner.channelCount, max(1, ...
    double(scanner.nextProbeStartChannel)));
order = [first:scanner.channelCount, 1:first-1].';
end

function value = appendStruct(value, items)
if isempty(items), return; end
if isempty(value), value = items(:); else, value = [value(:); items(:)]; end
end
