function state = multiDdcInit(inputSampleRateHz, frequencyOffsetsHz, varargin)
%MULTIDDCINIT Initialize one matrix-valued DDC for several known carriers.
p = inputParser;
p.addParameter('Config', radio.tuned.defaultConfig());
p.addParameter('InputCenterFrequencyHz', 0);
p.addParameter('ChannelIds', []);
p.addParameter('Capacity', []);
p.addParameter('Prewarm', false);
p.parse(varargin{:});

cfg = p.Results.Config;
radio.tuned.validateConfig(cfg, inputSampleRateHz);
frequencyOffsetsHz = double(frequencyOffsetsHz(:));
if isempty(frequencyOffsetsHz)
    error('radio:tuned:multiDdcInit:Offsets', ...
        'At least one frequency offset is required.');
end
capacity = p.Results.Capacity;
if isempty(capacity), capacity = numel(frequencyOffsetsHz); end
validateattributes(capacity, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'});
if capacity < numel(frequencyOffsetsHz)
    error('radio:tuned:multiDdcInit:Capacity', ...
        'Capacity cannot be smaller than the active offset count.');
end
offsets = zeros(capacity, 1);
offsets(1:numel(frequencyOffsetsHz)) = frequencyOffsetsHz;
channelIds = p.Results.ChannelIds;
if isempty(channelIds), channelIds = (1:capacity).'; end
channelIds = channelIds(:);
if numel(channelIds) < capacity
    channelIds = [channelIds; ...
        (numel(channelIds)+1:capacity).']; %#ok<AGROW>
end

nyquistHz = inputSampleRateHz / 2;
if any(abs(frequencyOffsetsHz) + cfg.stopbandFrequencyHz >= nyquistHz)
    error('radio:tuned:multiDdcInit:FrequencyOutsideInput', ...
        'Every selected channel must remain inside the input Nyquist band.');
end
decimationFactor = round(inputSampleRateHz / cfg.outputSampleRateHz);
inputBlockSamples = max(decimationFactor, ...
    round(cfg.chunkDurationSec * inputSampleRateHz));
inputBlockSamples = ceil(inputBlockSamples / decimationFactor) * ...
    decimationFactor;
converter = dsp.DigitalDownConverter( ...
    'SampleRate', double(inputSampleRateHz), ...
    'DecimationFactor', decimationFactor, ...
    'Bandwidth', double(cfg.channelBandwidthHz), ...
    'StopbandFrequencySource', 'Property', ...
    'StopbandFrequency', double(cfg.stopbandFrequencyHz), ...
    'PassbandRipple', double(cfg.passbandRippleDb), ...
    'StopbandAttenuation', double(cfg.stopbandAttenuationDb), ...
    'CenterFrequency', 0);
mixerSteps = exp(-1i .* 2 .* pi .* offsets.' ./ inputSampleRateHz);
mixerTemplate = buildMixerTemplate( ...
    offsets, inputSampleRateHz, inputBlockSamples);

state = struct( ...
    'converter', converter, ...
    'config', cfg, ...
    'capacity', double(capacity), ...
    'activeChannelCount', numel(frequencyOffsetsHz), ...
    'channelIds', channelIds(1:capacity), ...
    'frequencyOffsetsHz', offsets, ...
    'mixerSteps', mixerSteps, ...
    'mixerBlockSteps', mixerSteps .^ inputBlockSamples, ...
    'mixerTemplate', mixerTemplate, ...
    'mixerPhases', complex(ones(1, capacity)), ...
    'inputSampleRateHz', double(inputSampleRateHz), ...
    'outputSampleRateHz', double(cfg.outputSampleRateHz), ...
    'decimationFactor', double(decimationFactor), ...
    'inputBlockSamples', double(inputBlockSamples), ...
    'inputCenterFrequencyHz', double(p.Results.InputCenterFrequencyHz), ...
    'targetCenterFrequenciesHz', ...
        double(p.Results.InputCenterFrequencyHz) + offsets, ...
    'pendingIq', complex(zeros(0, 1)), ...
    'pendingSourceSampleStart', uint64(0), ...
    'expectedInputSample', [], ...
    'nextOutputSample', uint64(0), ...
    'nextSequenceNumber', uint64(0), ...
    'continuityGeneration', uint64(0), ...
    'inputSamplesReceived', uint64(0), ...
    'inputSamplesConverted', uint64(0), ...
    'outputSamplesProduced', uint64(0), ...
    'feedCount', uint64(0));

if p.Results.Prewarm
    converter(complex(zeros(inputBlockSamples, capacity)));
    reset(converter);
    state.converter = converter;
    dummy = radio.stream.makeIqChunk( ...
        complex(zeros(inputBlockSamples, 1)), inputSampleRateHz, 0, ...
        'CenterFrequencyHz', p.Results.InputCenterFrequencyHz);
    [warmState, ~] = radio.tuned.multiDdcFeed(state, dummy);
    reset(warmState.converter);
    state.converter = warmState.converter;
end

function values = buildMixerTemplate(offsets, sampleRateHz, count)
phase = (-1i .* 2 .* pi ./ sampleRateHz) .* ...
    (0:count-1).' .* offsets.';
values = exp(phase);
end
end
