function [scanner, report] = multiStreamScannerFinalize(scanner, varargin)
%MULTISTREAMSCANNERFINALIZE Flush and report every selected carrier.
p = inputParser;
p.addParameter('SilenceDurationSec', []);
p.addParameter('WaitForTasks', true);
p.addParameter('TaskTimeoutSec', 120);
p.addParameter('PollIntervalSec', 0.020);
p.addParameter('FlushDdc', true);
p.parse(varargin{:});
if scanner.finalized
    report = buildReport(scanner, cell(scanner.channelCount, 1));
    return;
end

% No more source IQ will arrive.  Release classification-priority admission
% so a carrier that was deferred behind another carrier can drain its
% ordered locked-decoder backlog during the final flush.
for k = 1:scanner.channelCount
    scanner.channels{k}.coordinator.deferLockedDecode = false;
end

if p.Results.FlushDdc && scanner.useFusedDdc
    [scanner.fusedDdc, flushChunks] = ...
        radio.tuned.multiDdcFlush(scanner.fusedDdc);
    for k = 1:min(scanner.channelCount, numel(flushChunks))
        priorPduCount = numel(scanner.channels{k}.pdus);
        priorEpochCount = numel(scanner.channels{k}.closedEpochs);
        widebandMarker = radio.stream.makeIqChunk( ...
            complex(zeros(0, 1)), scanner.inputSampleRateHz, ...
            scanner.inputSampleCount, ...
            'CenterFrequencyHz', scanner.inputCenterFrequencyHz);
        [scanner.channels{k}, basebandOutput] = ...
            radio.tuned.streamScannerFeedBaseband( ...
                scanner.channels{k}, widebandMarker, flushChunks{k});
        scanner = accumulateDecoderMetrics( ...
            scanner, k, basebandOutput.decoderMetrics);
        if numel(scanner.channels{k}.pdus) > priorPduCount
            scanner.pdus = appendStruct(scanner.pdus, ...
                scanner.channels{k}.pdus(priorPduCount+1:end));
        end
        if numel(scanner.channels{k}.closedEpochs) > priorEpochCount
            scanner.closedEpochs = appendStruct(scanner.closedEpochs, ...
                scanner.channels{k}.closedEpochs(priorEpochCount+1:end));
        end
    end
end

channelReports = cell(scanner.channelCount, 1);
for k = 1:scanner.channelCount
    priorPduCount = numel(scanner.channels{k}.pdus);
    priorEpochCount = numel(scanner.channels{k}.closedEpochs);
    [scanner.channels{k}, channelReports{k}] = ...
        radio.tuned.streamScannerFinalize(scanner.channels{k}, ...
        'SilenceDurationSec', p.Results.SilenceDurationSec, ...
        'WaitForTasks', p.Results.WaitForTasks, ...
        'TaskTimeoutSec', p.Results.TaskTimeoutSec, ...
        'PollIntervalSec', p.Results.PollIntervalSec, ...
        'FlushDdc', p.Results.FlushDdc && ~scanner.useFusedDdc);
    scanner = accumulateDecoderMetrics( ...
        scanner, k, channelReports{k}.decoderMetrics);
    if numel(scanner.channels{k}.pdus) > priorPduCount
        scanner.pdus = appendStruct(scanner.pdus, ...
            scanner.channels{k}.pdus(priorPduCount+1:end));
    end
    if numel(scanner.channels{k}.closedEpochs) > priorEpochCount
        scanner.closedEpochs = appendStruct(scanner.closedEpochs, ...
            scanner.channels{k}.closedEpochs(priorEpochCount+1:end));
    end
end
scanner.finalized = true;
report = buildReport(scanner, channelReports);
end

function report = buildReport(scanner, channelReports)
selected = cell(scanner.channelCount, 1);
states = cell(scanner.channelCount, 1);
backlogSamples = zeros(scanner.channelCount, 1, 'uint64');
for k = 1:scanner.channelCount
    states{k} = scanner.channels{k}.coordinator.state;
    selected{k} = scanner.channels{k}.lastSelectedProtocol;
    decoder = scanner.channels{k}.coordinator.decoderState;
    if ~isempty(decoder)
        backlogSamples(k) = scanner.channels{k}.basebandNextSample - ...
            decoder.lastProcessedEndSample;
    end
end
decoderCounts = max(1, double(scanner.decoderCompletionCount));
report = struct( ...
    'channelCount', scanner.channelCount, ...
    'frequencyOffsetsHz', scanner.frequencyOffsetsHz, ...
    'targetFrequenciesHz', scanner.targetFrequenciesHz, ...
    'states', {states}, ...
    'selectedProtocols', {selected}, ...
    'decoderBacklogSamples', backlogSamples, ...
    'inputSampleCount', scanner.inputSampleCount, ...
    'useFusedDdc', scanner.useFusedDdc, ...
    'meanDdcElapsedSec', scanner.totalDdcElapsedSec / ...
        max(1, double(scanner.feedCount)), ...
    'maxDdcElapsedSec', scanner.maxDdcElapsedSec, ...
    'meanFeedElapsedSec', scanner.totalFeedElapsedSec / ...
        max(1, double(scanner.feedCount)), ...
    'maxFeedElapsedSec', scanner.maxFeedElapsedSec, ...
    'decoderCompletionCount', scanner.decoderCompletionCount, ...
    'meanDecoderComputeSec', scanner.totalDecoderComputeSec ./ decoderCounts, ...
    'maxDecoderComputeSec', scanner.maxDecoderComputeSec, ...
    'meanDecoderDispatchSec', ...
        scanner.totalDecoderDispatchSec ./ decoderCounts, ...
    'maxDecoderDispatchSec', scanner.maxDecoderDispatchSec, ...
    'feedCount', scanner.feedCount, ...
    'pduCount', numel(scanner.pdus), ...
    'pdus', scanner.pdus, ...
    'closedEpochs', scanner.closedEpochs, ...
    'channelReports', {channelReports}, ...
    'elapsedSec', toc(scanner.timerToken), ...
    'finalized', scanner.finalized);
end

function value = appendStruct(value, items)
if isempty(items), return; end
if isempty(value), value = items(:); else, value = [value(:); items(:)]; end
end

function scanner = accumulateDecoderMetrics(scanner, channelIndex, metrics)
for metricIndex = 1:numel(metrics)
    metric = metrics(metricIndex);
    scanner.decoderCompletionCount(channelIndex) = ...
        scanner.decoderCompletionCount(channelIndex) + uint64(1);
    scanner.totalDecoderComputeSec(channelIndex) = ...
        scanner.totalDecoderComputeSec(channelIndex) + metric.computeSec;
    scanner.maxDecoderComputeSec(channelIndex) = max( ...
        scanner.maxDecoderComputeSec(channelIndex), metric.computeSec);
    scanner.totalDecoderDispatchSec(channelIndex) = ...
        scanner.totalDecoderDispatchSec(channelIndex) + metric.dispatchSec;
    scanner.maxDecoderDispatchSec(channelIndex) = max( ...
        scanner.maxDecoderDispatchSec(channelIndex), metric.dispatchSec);
end
end
