function scanner = multiStreamScannerInit( ...
        inputSampleRateHz, frequencyOffsetsHz, varargin)
%MULTISTREAMSCANNERINIT Fan one wideband stream into known-carrier scanners.
p = inputParser;
p.addParameter('InputCenterFrequencyHz', 0);
p.addParameter('Config', radio.tuned.defaultConfig());
p.addParameter('StreamConfig', radio.stream.defaultConfig());
p.addParameter('ProtocolNames', {});
p.addParameter('NumWorkers', 5);
p.addParameter('TaskFcn', []);
p.addParameter('TaskContext', struct());
p.addParameter('LockedDecodeFcn', []);
p.addParameter('Deduplicate', true);
p.addParameter('PrewarmDdc', true);
p.addParameter('WarmParallelPool', false);
p.addParameter('DdcStates', {});
p.addParameter('ProbeMaxInFlightPerChannel', []);
p.addParameter('EarlyProbeConfirm', false);
p.addParameter('EarlyProbeConfirmMinConfidence', 0.99);
p.addParameter('CandidateGateEnabled', false);
p.addParameter('UseFusedDdc', true);
p.addParameter('FusedDdcState', []);
p.addParameter('ExternalBaseband', false);
p.addParameter('MaxPersistentActorStartsPerFeed', 1);
p.addParameter('PersistentActorStartIntervalFeeds', 3);
p.addParameter('MaxProbeRaceStartsPerFeed', 1);
p.parse(varargin{:});

validateattributes(frequencyOffsetsHz, {'numeric'}, ...
    {'vector', 'real', 'finite', 'nonempty'}, mfilename, ...
    'frequencyOffsetsHz');
frequencyOffsetsHz = double(frequencyOffsetsHz(:));
if numel(unique(frequencyOffsetsHz)) ~= numel(frequencyOffsetsHz)
    error('radio:tuned:multiStreamScannerInit:DuplicateFrequency', ...
        'Each selected carrier frequency must be unique.');
end

channelCount = numel(frequencyOffsetsHz);
probeMaxInFlight = p.Results.ProbeMaxInFlightPerChannel;
if isempty(probeMaxInFlight)
    probeMaxInFlight = max(1, floor( ...
        double(p.Results.NumWorkers) / channelCount));
end
validateattributes(probeMaxInFlight, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'}, mfilename, ...
    'ProbeMaxInFlightPerChannel');
validateattributes(p.Results.MaxPersistentActorStartsPerFeed, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'nonnegative'}, mfilename, ...
    'MaxPersistentActorStartsPerFeed');
validateattributes(p.Results.PersistentActorStartIntervalFeeds, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'nonnegative'}, mfilename, ...
    'PersistentActorStartIntervalFeeds');
validateattributes(p.Results.MaxProbeRaceStartsPerFeed, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'}, mfilename, ...
    'MaxProbeRaceStartsPerFeed');
ddcStates = p.Results.DdcStates;
if ~isempty(ddcStates) && ...
        (~iscell(ddcStates) || numel(ddcStates) < channelCount)
    error('radio:tuned:multiStreamScannerInit:DdcStates', ...
        'DdcStates must contain one prepared DDC per selected carrier.');
end
channels = cell(channelCount, 1);
useFusedDdc = logical(p.Results.UseFusedDdc);
externalBaseband = logical(p.Results.ExternalBaseband);
fusedDdc = [];
if useFusedDdc && ~externalBaseband
    if isempty(p.Results.FusedDdcState)
        fusedDdc = radio.tuned.multiDdcInit( ...
            inputSampleRateHz, frequencyOffsetsHz, ...
            'Config', p.Results.Config, ...
            'InputCenterFrequencyHz', p.Results.InputCenterFrequencyHz, ...
            'Capacity', channelCount, ...
            'Prewarm', p.Results.PrewarmDdc);
    else
        fusedDdc = p.Results.FusedDdcState;
        if fusedDdc.inputSampleRateHz ~= double(inputSampleRateHz)
            error('radio:tuned:multiStreamScannerInit:FusedSampleRate', ...
                'Prepared matrix DDC sample rate does not match input.');
        end
        fusedDdc = radio.tuned.multiDdcRetarget( ...
            fusedDdc, frequencyOffsetsHz, ...
            'InputCenterFrequencyHz', p.Results.InputCenterFrequencyHz);
    end
end
for k = 1:channelCount
    ddcState = [];
    if ~isempty(ddcStates), ddcState = ddcStates{k}; end
    channels{k} = radio.tuned.streamScannerInit( ...
        inputSampleRateHz, frequencyOffsetsHz(k), ...
        'InputCenterFrequencyHz', p.Results.InputCenterFrequencyHz, ...
        'Config', p.Results.Config, ...
        'StreamConfig', p.Results.StreamConfig, ...
        'ProtocolNames', p.Results.ProtocolNames, ...
        'NumWorkers', p.Results.NumWorkers, ...
        'TaskFcn', p.Results.TaskFcn, ...
        'TaskContext', p.Results.TaskContext, ...
        'LockedDecodeFcn', p.Results.LockedDecodeFcn, ...
        'Deduplicate', p.Results.Deduplicate, ...
        'ChannelId', k, ...
        'PrewarmDdc', p.Results.PrewarmDdc && ~useFusedDdc, ...
        'WarmParallelPool', p.Results.WarmParallelPool && k == 1, ...
        'DdcState', ddcState, ...
        'ExternalBaseband', externalBaseband, ...
        'ProbeMaxInFlight', probeMaxInFlight, ...
        'EarlyProbeConfirm', p.Results.EarlyProbeConfirm, ...
        'EarlyProbeConfirmMinConfidence', ...
            p.Results.EarlyProbeConfirmMinConfidence, ...
        'CandidateGateEnabled', p.Results.CandidateGateEnabled);
end

scanner = struct( ...
    'channels', {channels}, ...
    'channelCount', channelCount, ...
    'frequencyOffsetsHz', frequencyOffsetsHz, ...
    'targetFrequenciesHz', p.Results.InputCenterFrequencyHz + ...
        frequencyOffsetsHz, ...
    'inputSampleRateHz', double(inputSampleRateHz), ...
    'inputCenterFrequencyHz', double(p.Results.InputCenterFrequencyHz), ...
    'useFusedDdc', useFusedDdc, ...
    'externalBaseband', externalBaseband, ...
    'fusedDdc', fusedDdc, ...
    'probeMaxInFlightPerChannel', double(probeMaxInFlight), ...
    'maxPersistentActorStartsPerFeed', ...
        double(p.Results.MaxPersistentActorStartsPerFeed), ...
    'persistentActorStartIntervalFeeds', ...
        double(p.Results.PersistentActorStartIntervalFeeds), ...
    'nextPersistentActorStartFeed', uint64(0), ...
    'maxProbeRaceStartsPerFeed', ...
        double(p.Results.MaxProbeRaceStartsPerFeed), ...
    'nextProbeStartChannel', uint64(1), ...
    'lastProbeStartAdmission', struct(), ...
    'lastLockedDecodeAdmission', struct(), ...
    'pdus', struct([]), ...
    'closedEpochs', repmat(radio.stream.newEpoch(0, 0, 0, 0), 0, 1), ...
    'feedCount', uint64(0), ...
    'inputSampleCount', uint64(0), ...
    'lastOutputs', {cell(channelCount, 1)}, ...
    'lastDdcElapsedSec', 0, ...
    'maxDdcElapsedSec', 0, ...
    'totalDdcElapsedSec', 0, ...
    'lastFeedElapsedSec', 0, ...
    'maxFeedElapsedSec', 0, ...
    'decoderCompletionCount', zeros(channelCount, 1, 'uint64'), ...
    'totalDecoderComputeSec', zeros(channelCount, 1), ...
    'maxDecoderComputeSec', zeros(channelCount, 1), ...
    'totalDecoderDispatchSec', zeros(channelCount, 1), ...
    'maxDecoderDispatchSec', zeros(channelCount, 1), ...
    'maxFeedBreakdown', struct( ...
        'feedIndex', uint64(0), 'ddcElapsedSec', 0, ...
        'channelElapsedSec', zeros(channelCount, 1), ...
        'decoderDispatch', {cell(channelCount, 1)}, ...
        'states', {cell(channelCount, 1)}, ...
        'selectedProtocols', {cell(channelCount, 1)}), ...
    'totalFeedElapsedSec', 0, ...
    'finalized', false, ...
    'timerToken', tic);
end
