function scanner = multiStreamScannerInit( ...
        inputSampleRateHz, frequencyOffsetsHz, varargin)
%MULTISTREAMSCANNERINIT Fan one wideband stream into known-carrier scanners.
p = inputParser;
p.addParameter('InputCenterFrequencyHz', 0);
p.addParameter('Config', radio.tuned.defaultConfig());
p.addParameter('StreamConfig', radio.stream.defaultConfig());
p.addParameter('ProtocolNames', {});
p.addParameter('Mode', 'auto');
p.addParameter('NumWorkers', 5);
p.addParameter('PoolType', 'auto');
p.addParameter('TaskFcn', []);
p.addParameter('TaskContext', struct());
p.addParameter('LockedDecodeFcn', []);
p.addParameter('Deduplicate', true);
p.addParameter('PrewarmDdc', true);
p.addParameter('WarmParallelPool', false);
p.addParameter('DdcStates', {});
p.parse(varargin{:});

validateattributes(frequencyOffsetsHz, {'numeric'}, ...
    {'vector', 'real', 'finite', 'nonempty'}, mfilename, ...
    'frequencyOffsetsHz');
frequencyOffsetsHz = double(frequencyOffsetsHz(:));
if numel(unique(frequencyOffsetsHz)) ~= numel(frequencyOffsetsHz)
    error('radio:tuned:multiStreamScannerInit:DuplicateFrequency', ...
        'Each selected carrier frequency must be unique.');
end

channelCount = numel(frequencyOffsetsHz);
ddcStates = p.Results.DdcStates;
if ~isempty(ddcStates) && ...
        (~iscell(ddcStates) || numel(ddcStates) < channelCount)
    error('radio:tuned:multiStreamScannerInit:DdcStates', ...
        'DdcStates must contain one prepared DDC per selected carrier.');
end
channels = cell(channelCount, 1);
for k = 1:channelCount
    ddcState = [];
    if ~isempty(ddcStates), ddcState = ddcStates{k}; end
    channels{k} = radio.tuned.streamScannerInit( ...
        inputSampleRateHz, frequencyOffsetsHz(k), ...
        'InputCenterFrequencyHz', p.Results.InputCenterFrequencyHz, ...
        'Config', p.Results.Config, ...
        'StreamConfig', p.Results.StreamConfig, ...
        'ProtocolNames', p.Results.ProtocolNames, ...
        'Mode', p.Results.Mode, ...
        'NumWorkers', p.Results.NumWorkers, ...
        'PoolType', p.Results.PoolType, ...
        'TaskFcn', p.Results.TaskFcn, ...
        'TaskContext', p.Results.TaskContext, ...
        'LockedDecodeFcn', p.Results.LockedDecodeFcn, ...
        'Deduplicate', p.Results.Deduplicate, ...
        'ChannelId', k, ...
        'PrewarmDdc', p.Results.PrewarmDdc, ...
        'WarmParallelPool', p.Results.WarmParallelPool && k == 1, ...
        'DdcState', ddcState);
end

scanner = struct( ...
    'channels', {channels}, ...
    'channelCount', channelCount, ...
    'frequencyOffsetsHz', frequencyOffsetsHz, ...
    'targetFrequenciesHz', p.Results.InputCenterFrequencyHz + ...
        frequencyOffsetsHz, ...
    'inputSampleRateHz', double(inputSampleRateHz), ...
    'inputCenterFrequencyHz', double(p.Results.InputCenterFrequencyHz), ...
    'pdus', struct([]), ...
    'closedEpochs', repmat(radio.stream.newEpoch(0, 0, 0, 0), 0, 1), ...
    'feedCount', uint64(0), ...
    'inputSampleCount', uint64(0), ...
    'lastOutputs', {cell(channelCount, 1)}, ...
    'finalized', false, ...
    'timerToken', tic);
end
