function [cfg, report] = resolveInputConfig(inputSampleRateHz, cfg)
%RESOLVEINPUTCONFIG Choose a valid narrowband rate for the capture rate.
if nargin < 2 || isempty(cfg)
    cfg = radio.tuned.defaultConfig();
end
validateattributes(inputSampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, ...
    'inputSampleRateHz');

requestedRateHz = double(cfg.outputSampleRateHz);
ratio = inputSampleRateHz / requestedRateHz;
adapted = abs(ratio - round(ratio)) > 1e-9;
if adapted
    % Keep the selected baseband Nyquist above the configured DDC stopband.
    % Prefer the two rates used by the current 61.44 MHz hardware capture
    % and 2.5 MHz synthetic acceptance capture, then conservative fallbacks.
    candidates = [125000, 120000, 128000, 100000, 96000, 80000];
    valid = candidates > 2 * cfg.stopbandFrequencyHz & ...
        abs(inputSampleRateHz ./ candidates - ...
        round(inputSampleRateHz ./ candidates)) < 1e-9;
    index = find(valid, 1);
    if isempty(index)
        error('radio:tuned:resolveInputConfig:NoIntegerDecimation', ...
            ['No supported output sample rate divides %.9g Hz while ', ...
             'preserving the %.9g Hz DDC stopband.'], ...
            inputSampleRateHz, cfg.stopbandFrequencyHz);
    end
    cfg.outputSampleRateHz = candidates(index);
end
radio.tuned.validateConfig(cfg, inputSampleRateHz);
report = struct( ...
    'inputSampleRateHz', double(inputSampleRateHz), ...
    'requestedOutputSampleRateHz', requestedRateHz, ...
    'outputSampleRateHz', double(cfg.outputSampleRateHz), ...
    'decimationFactor', round(inputSampleRateHz / cfg.outputSampleRateHz), ...
    'adapted', adapted);
end
