function [pdus, report] = scanFile(path, varargin)
%SCANFILE Extract one known carrier and run the shared protocol race.
p = inputParser;
p.addParameter('FrequencyOffsetHz', []);
p.addParameter('TargetFrequencyHz', []);
p.addParameter('SampleRate', []);
p.addParameter('CenterFrequencyHz', []);
p.addParameter('IqDType', 'int16');
p.addParameter('HeaderBytes', []);
p.addParameter('Config', radio.tuned.defaultConfig());
p.addParameter('StreamConfig', radio.stream.defaultConfig());
p.addParameter('ProtocolNames', {});
p.addParameter('NumWorkers', 5);
p.addParameter('TimeoutSec', 120);
p.addParameter('Deduplicate', true);
p.addParameter('ShowProgress', false);
p.addParameter('ChannelId', 1);
p.parse(varargin{:});

metadata = radio.tuned.captureInfo(path, ...
    'SampleRate', p.Results.SampleRate, ...
    'CenterFrequencyHz', p.Results.CenterFrequencyHz, ...
    'IqDType', p.Results.IqDType, ...
    'HeaderBytes', p.Results.HeaderBytes);
frequencyOffsetHz = p.Results.FrequencyOffsetHz;
targetFrequencyHz = p.Results.TargetFrequencyHz;
if isempty(frequencyOffsetHz) == isempty(targetFrequencyHz)
    error('radio:tuned:scanFile:Frequency', ...
        ['Specify exactly one of FrequencyOffsetHz or ', ...
         'TargetFrequencyHz.']);
end
if ~isempty(frequencyOffsetHz)
    validateattributes(frequencyOffsetHz, {'numeric'}, ...
        {'scalar', 'real', 'finite'});
    targetFrequencyHz = metadata.centerFrequencyHz + frequencyOffsetHz;
else
    validateattributes(targetFrequencyHz, {'numeric'}, ...
        {'scalar', 'real', 'finite'});
    frequencyOffsetHz = targetFrequencyHz - metadata.centerFrequencyHz;
end

[basebandIq, extraction] = radio.tuned.extractFile( ...
    path, targetFrequencyHz, ...
    'SampleRate', metadata.sampleRateHz, ...
    'CenterFrequencyHz', metadata.centerFrequencyHz, ...
    'IqDType', p.Results.IqDType, ...
    'HeaderBytes', metadata.headerBytes, ...
    'Config', p.Results.Config, ...
    'ChannelId', p.Results.ChannelId, ...
    'ShowProgress', p.Results.ShowProgress);
[pdus, basebandReport] = radio.stream.scanBasebandIqEpochs( ...
    basebandIq, extraction.outputSampleRateHz, ...
    'ProtocolNames', p.Results.ProtocolNames, ...
    'Config', p.Results.StreamConfig, ...
    'NumWorkers', p.Results.NumWorkers, ...
    'TimeoutSec', p.Results.TimeoutSec, ...
    'Deduplicate', p.Results.Deduplicate, ...
    'ShowProgress', p.Results.ShowProgress, ...
    'ChannelId', p.Results.ChannelId, ...
    'CenterFrequencyHz', targetFrequencyHz);
pdus = addTunedMetadata(pdus, extraction);

report = basebandReport;
report.executionMode = 'tuned-parallel';
report.path = char(path);
report.inputSampleRateHz = extraction.inputSampleRateHz;
report.basebandSampleRateHz = extraction.outputSampleRateHz;
report.inputCenterFrequencyHz = metadata.centerFrequencyHz;
report.targetFrequencyHz = double(targetFrequencyHz);
report.frequencyOffsetHz = double(frequencyOffsetHz);
report.inputSampleCount = extraction.inputSampleCount;
report.inputDurationSec = extraction.inputDurationSec;
report.extractionElapsedSec = extraction.elapsedSec;
report.totalElapsedSec = extraction.elapsedSec + ...
    basebandReport.totalElapsedSec;
report.realTimeFactor = report.totalElapsedSec / ...
    max(extraction.inputDurationSec, eps);
report.extraction = extraction;
report.pduCount = numel(pdus);
end

function pdus = addTunedMetadata(pdus, extraction)
for k = 1:numel(pdus)
    if ~isfield(pdus(k), 'extra') || ~isstruct(pdus(k).extra)
        pdus(k).extra = struct();
    end
    pdus(k).extra.tuned = struct( ...
        'input_center_frequency_hz', extraction.inputCenterFrequencyHz, ...
        'target_frequency_hz', extraction.targetFrequencyHz, ...
        'frequency_offset_hz', extraction.frequencyOffsetHz, ...
        'input_sample_rate_hz', extraction.inputSampleRateHz, ...
        'baseband_sample_rate_hz', extraction.outputSampleRateHz, ...
        'decimation_factor', extraction.decimationFactor);
end
pdus = radio.normalizePdus(pdus);
end
