function [scanner, output] = streamScannerFeedBaseband( ...
        scanner, widebandChunk, basebandChunk)
%STREAMSCANNERFEEDBASEBAND Feed a precomputed DDC output to one channel.
if scanner.finalized
    error('radio:tuned:streamScannerFeedBaseband:Finalized', ...
        'A finalized tuned stream scanner cannot accept more input.');
end
radio.stream.validateIqChunk(widebandChunk);
if ~isempty(basebandChunk)
    radio.stream.validateIqChunk(basebandChunk);
end
scanner.feedCount = scanner.feedCount + uint64(1);
scanner.inputSampleCount = scanner.inputSampleCount + ...
    uint64(numel(widebandChunk.iq));
[scanner, coordinatorChunks] = ...
    radio.tuned.streamScannerQueueBaseband(scanner, basebandChunk);

coordinatorOutput = [];
newPdus = struct([]);
closedEpochs = repmat(radio.stream.newEpoch( ...
    scanner.channelId, 0, 0, 0), 0, 1);
for k = 1:numel(coordinatorChunks)
    [scanner, coordinatorOutput, chunkPdus, chunkEpochs] = ...
        radio.tuned.streamScannerCoordinatorFeed( ...
            scanner, coordinatorChunks{k});
    newPdus = appendStruct(newPdus, chunkPdus);
    closedEpochs = appendStruct(closedEpochs, chunkEpochs);
end
output = struct( ...
    'state', scanner.coordinator.state, ...
    'selectedProtocol', scanner.coordinator.selectedProtocol, ...
    'epochId', scanner.coordinator.currentEpochId, ...
    'widebandChunk', widebandChunk, ...
    'basebandChunk', basebandChunk, ...
    'coordinator', coordinatorOutput, ...
    'coordinatorChunkCount', numel(coordinatorChunks), ...
    'newPdus', newPdus, ...
    'closedEpochs', closedEpochs, ...
    'pduCount', numel(scanner.pdus), ...
    'feedCount', scanner.feedCount, ...
    'inputSampleCount', scanner.inputSampleCount, ...
    'basebandSampleCount', scanner.basebandSampleCount, ...
    'basebandPendingSampleCount', uint64(scanner.basebandPendingCount));
scanner.lastOutput = output;
end

function value = appendStruct(value, items)
if isempty(items), return; end
if isempty(value), value = items(:); else, value = [value(:); items(:)]; end
end
