function [scanner, report] = streamScannerFinalize(scanner, varargin)
%STREAMSCANNERFINALIZE Flush DDC, micro-batch tail, and the finite Epoch.
p = inputParser;
p.addParameter('SilenceDurationSec', []);
p.addParameter('WaitForTasks', true);
p.addParameter('TaskTimeoutSec', 120);
p.addParameter('PollIntervalSec', 0.020);
p.addParameter('FlushDdc', true);
p.parse(varargin{:});
if scanner.finalized
    report = buildReport(scanner);
    return;
end

if p.Results.FlushDdc
    [scanner.ddc, flushChunk] = radio.tuned.ddcFlush(scanner.ddc);
    [scanner, readyChunks] = ...
        radio.tuned.streamScannerQueueBaseband(scanner, flushChunk);
    scanner = feedChunks(scanner, readyChunks);
end
[scanner, finalChunks] = radio.tuned.streamScannerQueueBaseband( ...
    scanner, [], 'Flush', true);
scanner = feedChunks(scanner, finalChunks);

validateattributes(p.Results.TaskTimeoutSec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
validateattributes(p.Results.PollIntervalSec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
if p.Results.WaitForTasks
    [scanner, waitElapsedSec, waitTimedOut] = awaitActiveTasks( ...
        scanner, p.Results.TaskTimeoutSec, p.Results.PollIntervalSec);
    scanner.finalizeTaskWaitElapsedSec = waitElapsedSec;
    scanner.finalizeTaskWaitTimedOut = waitTimedOut;
end

silenceSec = p.Results.SilenceDurationSec;
if isempty(silenceSec)
    if strcmp(scanner.coordinator.state, 'NO_SIGNAL')
        silenceSec = 0;
    else
        silenceSec = scanner.streamConfig.activity.offHangSec + ...
            2 * scanner.streamConfig.chunkDurationSec;
    end
end
validateattributes(silenceSec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});
remaining = ceil(silenceSec * scanner.basebandSampleRateHz);
chunkSamples = scanner.coordinatorChunkSamples;
while remaining > 0
    count = min(remaining, chunkSamples);
    chunk = radio.stream.makeIqChunk( ...
        complex(zeros(count, 1)), scanner.basebandSampleRateHz, ...
        scanner.basebandNextSample, ...
        'ChannelId', scanner.channelId, ...
        'SequenceNumber', scanner.basebandNextSequenceNumber, ...
        'CenterFrequencyHz', scanner.targetCenterFrequencyHz);
    scanner.basebandNextSequenceNumber = ...
        scanner.basebandNextSequenceNumber + uint64(1);
    [scanner, ~, ~, ~] = ...
        radio.tuned.streamScannerCoordinatorFeed(scanner, chunk);
    remaining = remaining - count;
end
scanner.finalized = true;
report = buildReport(scanner);
end

function [scanner, elapsedSec, timedOut] = awaitActiveTasks( ...
        scanner, timeoutSec, pollIntervalSec)
token = tic;
while hasActiveTask(scanner.coordinator) && toc(token) < timeoutSec
    chunk = radio.stream.makeIqChunk( ...
        complex(zeros(0, 1)), scanner.basebandSampleRateHz, ...
        scanner.basebandNextSample, ...
        'ChannelId', scanner.channelId, ...
        'SequenceNumber', scanner.basebandNextSequenceNumber, ...
        'CenterFrequencyHz', scanner.targetCenterFrequencyHz);
    scanner.basebandNextSequenceNumber = ...
        scanner.basebandNextSequenceNumber + uint64(1);
    [scanner, ~, ~, ~] = ...
        radio.tuned.streamScannerCoordinatorFeed(scanner, chunk);
    if hasActiveTask(scanner.coordinator)
        pause(pollIntervalSec);
    end
end
elapsedSec = toc(token);
timedOut = hasActiveTask(scanner.coordinator);
end

function tf = hasActiveTask(coordinator)
tf = ~isempty(coordinator.activeRace) || ...
    ~isempty(coordinator.activeCatchup) || ...
    ~isempty(coordinator.activeDecode);
end

function scanner = feedChunks(scanner, chunks)
for k = 1:numel(chunks)
    [scanner, ~, ~, ~] = ...
        radio.tuned.streamScannerCoordinatorFeed(scanner, chunks{k});
end
end

function report = buildReport(scanner)
protocols = {};
if ~isempty(scanner.pdus), protocols = unique({scanner.pdus.protocol}, 'stable'); end
selectedProtocol = scanner.coordinator.selectedProtocol;
if isempty(selectedProtocol), selectedProtocol = scanner.lastSelectedProtocol; end
report = struct( ...
    'state', scanner.coordinator.state, ...
    'selectedProtocol', selectedProtocol, ...
    'protocolsDetected', {protocols}, ...
    'inputSampleRateHz', scanner.inputSampleRateHz, ...
    'basebandSampleRateHz', scanner.basebandSampleRateHz, ...
    'inputCenterFrequencyHz', scanner.inputCenterFrequencyHz, ...
    'targetCenterFrequencyHz', scanner.targetCenterFrequencyHz, ...
    'frequencyOffsetHz', scanner.frequencyOffsetHz, ...
    'deduplicate', scanner.deduplicate, ...
    'inputSampleCount', scanner.inputSampleCount, ...
    'basebandSampleCount', scanner.basebandSampleCount, ...
    'feedCount', scanner.feedCount, ...
    'coordinatorChunkSamples', scanner.coordinatorChunkSamples, ...
    'epochCount', numel(scanner.closedEpochs), ...
    'epochs', scanner.closedEpochs, ...
    'pduCount', numel(scanner.pdus), ...
    'pdus', scanner.pdus, ...
    'events', scanner.events, ...
    'warmupElapsedSec', scanner.warmupElapsedSec, ...
    'poolInfo', scanner.poolInfo, ...
    'finalizeTaskWaitElapsedSec', scanner.finalizeTaskWaitElapsedSec, ...
    'finalizeTaskWaitTimedOut', scanner.finalizeTaskWaitTimedOut, ...
    'elapsedSec', toc(scanner.timerToken), ...
    'finalized', scanner.finalized);
end
