function [scanner, output] = streamScannerFeed(scanner, widebandChunk)
%STREAMSCANNERFEED Route one wideband block through DDC and protocol race.
if scanner.finalized
    error('radio:tuned:streamScannerFeed:Finalized', ...
        'A finalized tuned stream scanner cannot accept more input.');
end
radio.stream.validateIqChunk(widebandChunk);
if widebandChunk.sampleRateHz ~= scanner.inputSampleRateHz
    error('radio:tuned:streamScannerFeed:SampleRate', ...
        'Wideband input sample rate changed.');
end
if widebandChunk.centerFrequencyHz ~= scanner.inputCenterFrequencyHz
    error('radio:tuned:streamScannerFeed:CenterFrequency', ...
        'Retuning requires a new tuned stream scanner.');
end

[scanner.ddc, basebandChunk] = ...
    radio.tuned.ddcFeed(scanner.ddc, widebandChunk);
scanner.feedCount = scanner.feedCount + uint64(1);
scanner.inputSampleCount = scanner.inputSampleCount + ...
    uint64(numel(widebandChunk.iq));
[scanner, coordinatorChunks] = ...
    radio.tuned.streamScannerQueueBaseband(scanner, basebandChunk);

coordinatorOutput = [];
newPdus = struct([]);
closedEpochs = emptyEpochs(scanner.channelId);
for k = 1:numel(coordinatorChunks)
    [scanner, coordinatorOutput, chunkPdus, chunkEpochs] = ...
        radio.tuned.streamScannerCoordinatorFeed( ...
            scanner, coordinatorChunks{k});
    newPdus = appendStruct(newPdus, chunkPdus);
    closedEpochs = appendStruct(closedEpochs, chunkEpochs);
end
output = makeOutput(scanner, widebandChunk, basebandChunk, ...
    coordinatorOutput, newPdus, closedEpochs, numel(coordinatorChunks));
scanner.lastOutput = output;
end

function output = makeOutput(scanner, widebandChunk, basebandChunk, ...
        coordinator, newPdus, closedEpochs, coordinatorChunkCount)
output = struct( ...
    'state', scanner.coordinator.state, ...
    'selectedProtocol', scanner.coordinator.selectedProtocol, ...
    'epochId', scanner.coordinator.currentEpochId, ...
    'widebandChunk', widebandChunk, ...
    'basebandChunk', basebandChunk, ...
    'coordinator', coordinator, ...
    'coordinatorChunkCount', coordinatorChunkCount, ...
    'newPdus', newPdus, ...
    'closedEpochs', closedEpochs, ...
    'pduCount', numel(scanner.pdus), ...
    'feedCount', scanner.feedCount, ...
    'inputSampleCount', scanner.inputSampleCount, ...
    'basebandSampleCount', scanner.basebandSampleCount, ...
    'basebandPendingSampleCount', ...
        uint64(numel(scanner.basebandPendingIq)));
end

function value = appendStruct(value, items)
if isempty(items), return; end
if isempty(value), value = items(:); else, value = [value(:); items(:)]; end
end

function epochs = emptyEpochs(channelId)
epochs = repmat(radio.stream.newEpoch(channelId, 0, 0, 0), 0, 1);
end
