function scanner = streamScannerInit(inputSampleRateHz, frequencyOffsetHz, varargin)
%STREAMSCANNERINIT Initialize known-carrier DDC plus protocol coordinator.
p = inputParser;
p.addParameter('InputCenterFrequencyHz', 0);
p.addParameter('TargetCenterFrequencyHz', []);
p.addParameter('Config', radio.tuned.defaultConfig());
p.addParameter('StreamConfig', radio.stream.defaultConfig());
p.addParameter('ProtocolNames', {});
p.addParameter('Mode', 'auto');
p.addParameter('NumWorkers', 5);
p.addParameter('PoolType', 'auto');
p.addParameter('TaskFcn', []);
p.addParameter('TaskContext', struct());
p.addParameter('LockedDecodeFcn', []);
p.addParameter('Deduplicate', true);
p.addParameter('ChannelId', 1);
p.addParameter('PrewarmDdc', true);
p.addParameter('WarmParallelPool', false);
p.addParameter('DdcState', []);
p.parse(varargin{:});

if isempty(p.Results.DdcState)
    ddc = radio.tuned.ddcInit(inputSampleRateHz, frequencyOffsetHz, ...
        'Config', p.Results.Config, ...
        'InputCenterFrequencyHz', p.Results.InputCenterFrequencyHz, ...
        'TargetCenterFrequencyHz', p.Results.TargetCenterFrequencyHz, ...
        'ChannelId', p.Results.ChannelId);
    warmupElapsedSec = 0;
    if p.Results.PrewarmDdc
        warmTimer = tic;
        converter = ddc.converter;
        converter(complex(zeros(ddc.inputBlockSamples, 1)));
        reset(converter);
        ddc.converter = converter;
        warmupElapsedSec = toc(warmTimer);
    end
else
    ddc = p.Results.DdcState;
    if ddc.inputSampleRateHz ~= double(inputSampleRateHz)
        error('radio:tuned:streamScannerInit:DdcSampleRate', ...
            'The prepared DDC sample rate does not match the input stream.');
    end
    ddc = radio.tuned.ddcRetarget(ddc, frequencyOffsetHz, ...
        'InputCenterFrequencyHz', p.Results.InputCenterFrequencyHz, ...
        'TargetCenterFrequencyHz', p.Results.TargetCenterFrequencyHz, ...
        'ChannelId', p.Results.ChannelId);
    warmupElapsedSec = 0;
end

poolInfo = emptyPoolInfo(p.Results.NumWorkers);
mode = char(p.Results.Mode);
if p.Results.WarmParallelPool && any(strcmpi(mode, {'auto', 'parallel'}))
    [~, poolInfo] = radio.stream.acquireParallelPool( ...
        'NumWorkers', p.Results.NumWorkers, ...
        'PoolType', p.Results.PoolType);
end
coordinator = radio.stream.raceCoordinatorInit( ...
    ddc.outputSampleRateHz, ...
    'Config', p.Results.StreamConfig, ...
    'ChannelId', p.Results.ChannelId, ...
    'CenterFrequencyHz', ddc.targetCenterFrequencyHz, ...
    'ProtocolNames', p.Results.ProtocolNames, ...
    'Mode', p.Results.Mode, ...
    'NumWorkers', p.Results.NumWorkers, ...
    'PoolType', p.Results.PoolType, ...
    'TaskFcn', p.Results.TaskFcn, ...
    'TaskContext', p.Results.TaskContext, ...
    'LockedDecodeFcn', p.Results.LockedDecodeFcn, ...
    'Deduplicate', p.Results.Deduplicate);
coordinatorChunkSamples = max(1, round( ...
    p.Results.StreamConfig.chunkDurationSec * ddc.outputSampleRateHz));

scanner = struct( ...
    'ddc', ddc, ...
    'coordinator', coordinator, ...
    'streamConfig', p.Results.StreamConfig, ...
    'inputSampleRateHz', double(inputSampleRateHz), ...
    'basebandSampleRateHz', ddc.outputSampleRateHz, ...
    'inputCenterFrequencyHz', ddc.inputCenterFrequencyHz, ...
    'targetCenterFrequencyHz', ddc.targetCenterFrequencyHz, ...
    'frequencyOffsetHz', ddc.frequencyOffsetHz, ...
    'channelId', p.Results.ChannelId, ...
    'deduplicate', logical(p.Results.Deduplicate), ...
    'pdus', struct([]), ...
    'closedEpochs', repmat(radio.stream.newEpoch( ...
        p.Results.ChannelId, 0, 0, 0), 0, 1), ...
    'events', emptyEvents(), ...
    'lastSelectedProtocol', '', ...
    'feedCount', uint64(0), ...
    'inputSampleCount', uint64(0), ...
    'basebandSampleCount', uint64(0), ...
    'basebandNextSample', uint64(0), ...
    'basebandNextSequenceNumber', uint64(0), ...
    'coordinatorChunkSamples', double(coordinatorChunkSamples), ...
    'basebandPendingIq', complex(zeros(0, 1)), ...
    'basebandPendingStartSample', uint64(0), ...
    'basebandPendingDiscontinuity', false, ...
    'basebandPendingDroppedSamples', uint64(0), ...
    'warmupElapsedSec', double(warmupElapsedSec), ...
    'poolInfo', poolInfo, ...
    'finalizeTaskWaitElapsedSec', 0, ...
    'finalizeTaskWaitTimedOut', false, ...
    'lastOutput', [], ...
    'finalized', false, ...
    'timerToken', tic);
end

function info = emptyPoolInfo(numWorkers)
info = struct( ...
    'available', false, ...
    'created', false, ...
    'reused', false, ...
    'profile', '', ...
    'poolType', '', ...
    'jobStorageLocation', '', ...
    'numWorkers', 0, ...
    'requestedWorkers', double(numWorkers), ...
    'createAttempts', 0, ...
    'reason', 'not_requested');
end

function events = emptyEvents()
events = struct('type', {}, 'fromState', {}, 'toState', {}, ...
    'sample', {}, 'protocol', {}, 'reason', {});
end
