function [scanner, output] = streamScannerFeedBaseband( ...
        scanner, widebandChunk, basebandChunk)
%STREAMSCANNERFEEDBASEBAND Feed a precomputed DDC output to one channel.
if scanner.finalized
    error('radio:tuned:streamScannerFeedBaseband:Finalized', ...
        'A finalized tuned stream scanner cannot accept more input.');
end
widebandSampleCount = ...
    radio.stream.validateIqChunkDescriptor(widebandChunk);
if ~isempty(basebandChunk)
    radio.stream.validateIqChunk(basebandChunk);
end
scanner.feedCount = scanner.feedCount + uint64(1);
scanner.inputSampleCount = scanner.inputSampleCount + ...
    widebandSampleCount;
[scanner, coordinatorChunks] = ...
    radio.tuned.streamScannerQueueBaseband(scanner, basebandChunk);

coordinatorOutput = [];
newPdus = struct([]);
closedEpochs = repmat(radio.stream.newEpoch( ...
    scanner.channelId, 0, 0, 0), 0, 1);
decoderMetrics = emptyDecoderMetrics();
for k = 1:numel(coordinatorChunks)
    [scanner, coordinatorOutput, chunkPdus, chunkEpochs] = ...
        radio.tuned.streamScannerCoordinatorFeed( ...
            scanner, coordinatorChunks{k});
    newPdus = appendStruct(newPdus, chunkPdus);
    closedEpochs = appendStruct(closedEpochs, chunkEpochs);
    decoderMetrics = appendStruct(decoderMetrics, ...
        radio.tuned.decoderMetricFromCoordinatorOutput(coordinatorOutput));
end
output = struct( ...
    'state', scanner.coordinator.state, ...
    'selectedProtocol', scanner.coordinator.selectedProtocol, ...
    'epochId', scanner.coordinator.currentEpochId, ...
    'widebandChunk', widebandChunk, ...
    'basebandChunk', basebandChunk, ...
    'coordinator', coordinatorOutput, ...
    'coordinatorChunkCount', numel(coordinatorChunks), ...
    'newPdus', newPdus, ...
    'closedEpochs', closedEpochs, ...
    'decoderMetrics', decoderMetrics, ...
    'pduCount', numel(scanner.pdus), ...
    'feedCount', scanner.feedCount, ...
    'inputSampleCount', scanner.inputSampleCount, ...
    'basebandSampleCount', scanner.basebandSampleCount, ...
    'basebandPendingSampleCount', uint64(scanner.basebandPendingCount));
scanner.lastOutput = output;
end

function value = appendStruct(value, items)
if isempty(items), return; end
if isempty(value), value = items(:); else, value = [value(:); items(:)]; end
end

function values = emptyDecoderMetrics()
values = repmat(struct( ...
    'protocol', '', 'computeSec', 0, 'dispatchSec', 0, ...
    'newPduCount', 0, 'mode', ''), 0, 1);
end
