function validateConfig(cfg, inputSampleRateHz)
%VALIDATECONFIG Validate a known-carrier transition configuration.
required = { ...
    'outputSampleRateHz', 'channelBandwidthHz', ...
    'stopbandFrequencyHz', 'passbandRippleDb', ...
    'stopbandAttenuationDb', 'chunkDurationSec', 'filterFlushSec'};
missing = required(~isfield(cfg, required));
if ~isempty(missing)
    error('radio:tuned:validateConfig:MissingField', ...
        'Tuned configuration is missing field: %s', missing{1});
end

positive = required(1:6);
for k = 1:numel(positive)
    validateattributes(cfg.(positive{k}), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, mfilename, positive{k});
end
validateattributes(cfg.filterFlushSec, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'}, ...
    mfilename, 'filterFlushSec');
validateattributes(inputSampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, 'inputSampleRateHz');

factor = inputSampleRateHz / cfg.outputSampleRateHz;
if factor < 2 || abs(factor - round(factor)) > ...
        16 * eps(max(abs(factor), 1))
    error('radio:tuned:validateConfig:DecimationFactor', ...
        ['InputSampleRateHz / outputSampleRateHz must be an integer ', ...
         'decimation factor of at least two.']);
end
if cfg.channelBandwidthHz >= cfg.outputSampleRateHz
    error('radio:tuned:validateConfig:ChannelBandwidth', ...
        'channelBandwidthHz must be below the output sample rate.');
end
passbandEdgeHz = cfg.channelBandwidthHz / 2;
nyquistHz = cfg.outputSampleRateHz / 2;
if cfg.stopbandFrequencyHz <= passbandEdgeHz || ...
        cfg.stopbandFrequencyHz >= nyquistHz
    error('radio:tuned:validateConfig:StopbandFrequency', ...
        ['stopbandFrequencyHz must be above the channel passband edge ', ...
         'and below the output Nyquist frequency.']);
end
end
