function pdus = scanIqNarrowband(iq, sampleRate, enabledProtocols, varargin)
%SCANIQNARROWBAND Run the 48 kHz narrowband 4FSK candidate pipeline.
p = inputParser;
p.addParameter('FreqList', []);
p.addParameter('BlindSearch', false);
p.addParameter('RadioConfig', radio.defaultConfig());
p.addParameter('DecoderBackend', 'matlab');
p.addParameter('PythonRoot', '');
p.addParameter('PythonExecutable', '');
p.addParameter('Deduplicate', true);
p.parse(varargin{:});

cfg = p.Results.RadioConfig;
freqList = p.Results.FreqList;

pdus = struct([]);
if ~isempty(freqList)
    for k = 1:numel(freqList)
        next = radio.processCandidate(iq, freqList(k), sampleRate, enabledProtocols, ...
            'RadioConfig', cfg, ...
            'DecoderBackend', p.Results.DecoderBackend, ...
            'PythonRoot', p.Results.PythonRoot, ...
            'PythonExecutable', p.Results.PythonExecutable, ...
            'Deduplicate', p.Results.Deduplicate);
        pdus = radio.appendPdus(pdus, next);
    end
elseif p.Results.BlindSearch
    offsets = radio.psdBlindSearch(iq, sampleRate, cfg);
    for k = 1:numel(offsets)
        next = radio.processCandidate(iq, offsets(k), sampleRate, enabledProtocols, ...
            'RadioConfig', cfg, ...
            'DecoderBackend', p.Results.DecoderBackend, ...
            'PythonRoot', p.Results.PythonRoot, ...
            'PythonExecutable', p.Results.PythonExecutable, ...
            'Deduplicate', p.Results.Deduplicate);
        pdus = radio.appendPdus(pdus, next);
    end
else
    pdus = radio.processBaseband(iq, sampleRate, enabledProtocols, ...
        'RadioConfig', cfg, ...
        'DecoderBackend', p.Results.DecoderBackend, ...
        'PythonRoot', p.Results.PythonRoot, ...
        'PythonExecutable', p.Results.PythonExecutable, ...
        'Deduplicate', p.Results.Deduplicate);
end
end
