function [pdus, report] = scanFile(path, varargin)
%SCANFILE Decode an offline IQ file with the native parallel pipeline.
p = inputParser;
p.addParameter('FreqList', []);
p.addParameter('ProtocolNames', {});
p.addParameter('SampleRate', []);
p.addParameter('IqDType', 'int16');
p.addParameter('Deduplicate', true);
p.addParameter('ShowProgress', false);
p.addParameter('ExecutionMode', 'parallel');
p.addParameter('StreamConfig', radio.stream.defaultConfig());
p.addParameter('WidebandConfig', radio.wideband.defaultConfig());
p.addParameter('TunedConfig', radio.tuned.defaultConfig());
p.addParameter('CenterFrequencyHz', 0);
p.addParameter('NumWorkers', 5);
p.addParameter('TimeoutSec', 120);
p.parse(varargin{:});

mode = normalizeExecutionMode(p.Results.ExecutionMode);
switch mode
    case 'tuned-parallel'
        if numel(p.Results.FreqList) ~= 1
            error('radio:scanFile:TunedFrequencyList', ...
                'Known-frequency decoding requires one relative offset.');
        end
        [pdus, report] = radio.tuned.scanFile(path, ...
            'FrequencyOffsetHz', p.Results.FreqList, ...
            'SampleRate', p.Results.SampleRate, ...
            'CenterFrequencyHz', p.Results.CenterFrequencyHz, ...
            'IqDType', p.Results.IqDType, ...
            'Config', p.Results.TunedConfig, ...
            'StreamConfig', p.Results.StreamConfig, ...
            'ProtocolNames', p.Results.ProtocolNames, ...
            'NumWorkers', p.Results.NumWorkers, ...
            'TimeoutSec', p.Results.TimeoutSec, ...
            'Deduplicate', p.Results.Deduplicate, ...
            'ShowProgress', p.Results.ShowProgress);

    case 'wideband'
        if ~isempty(p.Results.FreqList)
            error('radio:scanFile:WidebandFrequencyList', ...
                'Wideband discovery requires an empty FreqList.');
        end
        [pdus, report] = radio.wideband.scanFile(path, ...
            'SampleRate', p.Results.SampleRate, ...
            'IqDType', p.Results.IqDType, ...
            'CenterFrequencyHz', p.Results.CenterFrequencyHz, ...
            'Config', p.Results.WidebandConfig, ...
            'ProtocolNames', p.Results.ProtocolNames, ...
            'NumWorkers', p.Results.NumWorkers, ...
            'ShowProgress', p.Results.ShowProgress);

    case 'parallel'
        if ~isempty(p.Results.FreqList)
            error('radio:scanFile:KnownFrequencyMode', ...
                ['FreqList requires ', ...
                 'ExecutionMode=''tuned-parallel''.']);
        end
        [pdus, report] = radio.stream.scanBasebandFile(path, ...
            'ProtocolNames', p.Results.ProtocolNames, ...
            'SampleRate', p.Results.SampleRate, ...
            'IqDType', p.Results.IqDType, ...
            'StreamConfig', p.Results.StreamConfig, ...
            'NumWorkers', p.Results.NumWorkers, ...
            'TimeoutSec', p.Results.TimeoutSec, ...
            'Deduplicate', p.Results.Deduplicate, ...
            'ShowProgress', p.Results.ShowProgress);
end
pdus = radio.normalizePdus(pdus);
end

function mode = normalizeExecutionMode(value)
mode = lower(char(value));
switch mode
    case {'parallel', 'tuned-parallel', 'wideband'}
    otherwise
        error('radio:scanFile:ExecutionMode', ...
            ['ExecutionMode must be parallel, tuned-parallel, ', ...
             'or wideband.']);
end
end
