function [pdus, report] = scanFile(path, varargin)
%SCANFILE Scan an offline IQ file for DMR, P25, dPMR, NXDN, and TETRA metadata.
p = inputParser;
p.addParameter('FreqList', []);
p.addParameter('BlindSearch', false);
p.addParameter('ProtocolNames', {});
p.addParameter('SampleRate', []);
p.addParameter('IqDType', 'int16');
p.addParameter('RadioConfig', radio.defaultConfig());
p.addParameter('PipelineBackend', 'matlab');
p.addParameter('DecoderBackend', 'matlab');
p.addParameter('PythonRoot', '');
p.addParameter('PythonExecutable', '');
p.addParameter('Deduplicate', true);
p.addParameter('ShowProgress', false);
p.addParameter('ExecutionMode', 'serial');
p.addParameter('StreamConfig', radio.stream.defaultConfig());
p.addParameter('WidebandConfig', radio.wideband.defaultConfig());
p.addParameter('TunedConfig', radio.tuned.defaultConfig());
p.addParameter('CenterFrequencyHz', 0);
p.addParameter('ParallelMode', 'parallel');
p.addParameter('ParallelNumWorkers', 5);
p.addParameter('ParallelPoolType', 'processes');
p.addParameter('ParallelTimeoutSec', 120);
p.parse(varargin{:});

backend = lower(char(p.Results.PipelineBackend));
executionMode = normalizeExecutionMode(p.Results.ExecutionMode);
useTunedTransition = strcmp(executionMode, 'tuned-parallel') || ...
    (strcmp(executionMode, 'parallel') && ~isempty(p.Results.FreqList) && ...
    any(p.Results.FreqList(:) ~= 0));
if useTunedTransition
    if ~any(strcmp(backend, {'matlab', 'native'}))
        error('radio:scanFile:TunedBackend', ...
            'Known-frequency DDC requires PipelineBackend=matlab.');
    end
    if p.Results.BlindSearch
        error('radio:scanFile:TunedBlindSearch', ...
            'Known-frequency DDC requires BlindSearch=false.');
    end
    if numel(p.Results.FreqList) ~= 1
        error('radio:scanFile:TunedFrequencyList', ...
            ['The first tuned transition phase accepts exactly one ', ...
             'relative frequency offset in FreqList.']);
    end
    [pdus, report] = radio.tuned.scanFile(path, ...
        'FrequencyOffsetHz', p.Results.FreqList, ...
        'SampleRate', p.Results.SampleRate, ...
        'CenterFrequencyHz', p.Results.CenterFrequencyHz, ...
        'IqDType', p.Results.IqDType, ...
        'Config', p.Results.TunedConfig, ...
        'StreamConfig', p.Results.StreamConfig, ...
        'RadioConfig', p.Results.RadioConfig, ...
        'ProtocolNames', p.Results.ProtocolNames, ...
        'Mode', p.Results.ParallelMode, ...
        'NumWorkers', p.Results.ParallelNumWorkers, ...
        'PoolType', p.Results.ParallelPoolType, ...
        'TimeoutSec', p.Results.ParallelTimeoutSec, ...
        'DecoderBackend', p.Results.DecoderBackend, ...
        'PythonRoot', p.Results.PythonRoot, ...
        'PythonExecutable', p.Results.PythonExecutable, ...
        'Deduplicate', p.Results.Deduplicate, ...
        'ShowProgress', p.Results.ShowProgress);
    pdus = radio.normalizePdus(pdus);
    return;
end
if strcmp(executionMode, 'wideband')
    if ~any(strcmp(backend, {'matlab', 'native'}))
        error('radio:scanFile:WidebandBackend', ...
            'Wideband streaming requires PipelineBackend=matlab.');
    end
    if ~isempty(p.Results.FreqList)
        error('radio:scanFile:WidebandFrequencyList', ...
            ['Wideband streaming discovers carriers itself; leave ', ...
            'FreqList empty.']);
    end
    [pdus, report] = radio.wideband.scanFile(path, ...
        'SampleRate', p.Results.SampleRate, ...
        'IqDType', p.Results.IqDType, ...
        'CenterFrequencyHz', p.Results.CenterFrequencyHz, ...
        'Config', p.Results.WidebandConfig, ...
        'ProtocolNames', p.Results.ProtocolNames, ...
        'Mode', p.Results.ParallelMode, ...
        'NumWorkers', p.Results.ParallelNumWorkers, ...
        'PoolType', p.Results.ParallelPoolType, ...
        'ShowProgress', p.Results.ShowProgress);
    pdus = radio.normalizePdus(pdus);
    return;
end
if strcmp(executionMode, 'parallel')
    if ~any(strcmp(backend, {'matlab', 'native'}))
        error('radio:scanFile:ParallelBackend', ...
            'Parallel baseband scanning requires PipelineBackend=matlab.');
    end
    if p.Results.BlindSearch
        error('radio:scanFile:ParallelBlindSearch', ...
            ['Parallel mode currently accepts one already-centered baseband ', ...
             'channel; set BlindSearch=false.']);
    end
    [pdus, report] = radio.stream.scanBasebandFile(path, ...
        'ProtocolNames', p.Results.ProtocolNames, ...
        'SampleRate', p.Results.SampleRate, ...
        'IqDType', p.Results.IqDType, ...
        'StreamConfig', p.Results.StreamConfig, ...
        'RadioConfig', p.Results.RadioConfig, ...
        'Mode', p.Results.ParallelMode, ...
        'NumWorkers', p.Results.ParallelNumWorkers, ...
        'PoolType', p.Results.ParallelPoolType, ...
        'TimeoutSec', p.Results.ParallelTimeoutSec, ...
        'DecoderBackend', p.Results.DecoderBackend, ...
        'PythonRoot', p.Results.PythonRoot, ...
        'PythonExecutable', p.Results.PythonExecutable, ...
        'Deduplicate', p.Results.Deduplicate, ...
        'ShowProgress', p.Results.ShowProgress);
    pdus = radio.normalizePdus(pdus);
    return;
end

report = struct('outcome', 'serial', 'selectedProtocol', '', ...
    'executionMode', 'serial', 'pduCount', 0);
switch backend
    case {'python', 'compat', 'py'}
        pdus = pybackend.scanFile(path, ...
            'FreqList', p.Results.FreqList, ...
            'BlindSearch', p.Results.BlindSearch, ...
            'ProtocolNames', p.Results.ProtocolNames, ...
            'SampleRate', p.Results.SampleRate, ...
            'IqDType', p.Results.IqDType, ...
            'PythonRoot', p.Results.PythonRoot, ...
            'PythonExecutable', p.Results.PythonExecutable, ...
            'Deduplicate', p.Results.Deduplicate);
    case {'matlab', 'native'}
        iq = common.readRawIq(path, 'DType', p.Results.IqDType);
        fs = p.Results.SampleRate;
        if isempty(fs)
            fs = common.detectSampleRate(path);
        end
        if isempty(fs)
            error('radio:scanFile:MissingSampleRate', ...
                'Sample rate is required; pass SampleRate or use a filename with metadata.');
        end
        pdus = radio.scanIq(iq, fs, ...
            'FreqList', p.Results.FreqList, ...
            'BlindSearch', p.Results.BlindSearch, ...
            'ProtocolNames', p.Results.ProtocolNames, ...
            'RadioConfig', p.Results.RadioConfig, ...
            'DecoderBackend', p.Results.DecoderBackend, ...
            'PythonRoot', p.Results.PythonRoot, ...
            'PythonExecutable', p.Results.PythonExecutable, ...
            'Deduplicate', p.Results.Deduplicate, ...
            'ShowProgress', p.Results.ShowProgress);
    otherwise
        error('radio:scanFile:UnsupportedBackend', ...
            'Unsupported pipeline backend: %s', backend);
end
pdus = radio.normalizePdus(pdus);
report.pduCount = numel(pdus);
end

function mode = normalizeExecutionMode(value)
mode = lower(strrep(char(value), '_', '-'));
switch mode
    case {'serial', 'compatibility'}
        mode = 'serial';
    case {'parallel', 'streaming-parallel', 'protocol-race'}
        mode = 'parallel';
    case {'tuned-parallel', 'known-frequency', 'known-carrier'}
        mode = 'tuned-parallel';
    case {'wideband', 'wideband-streaming', 'realtime-replay'}
        mode = 'wideband';
    otherwise
        error('radio:scanFile:ExecutionMode', ...
            ['ExecutionMode must be serial, parallel, tuned-parallel, ', ...
             'or wideband.']);
end
end
