function [bestDecision, bestTraining, variantReports] = ...
        bestDecisionVariant(sync, seqs, cfg)
%BESTDECISIONVARIANT Select the TETRA differential mapping with evidence.
if nargin < 2 || isempty(seqs), seqs = tetra.trainingSequences(); end
if nargin < 3 || isempty(cfg), cfg = tetra.config(); end
variants = {'standard', 'conjugate', 'swap_bits', 'conjugate_swap'};
variantReports = repmat(struct( ...
    'variant', '', 'score', 0, 'goodCount', 0, ...
    'candidateCount', 0), 0, 1);
bestScore = -inf;
bestDecision = [];
bestTraining = [];
variantPhaseOffsets = nan(numel(variants), 1);
for k = 1:numel(variants)
    phaseOffset = [];
    if k == 3
        % Bit swapping does not change the observed differential phase.
        phaseOffset = variantPhaseOffsets(1);
    elseif k == 4
        phaseOffset = variantPhaseOffsets(2);
    end
    decision = tetra.pi4dqpskDecision(sync.symbols, ...
        'Variant', variants{k}, ...
        'PhaseOffsetRad', phaseOffset, ...
        'PhaseOffsetStepRad', cfg.diffPhaseOffsetStepRad, ...
        'PhaseOffsetMaxTransitions', ...
            cfg.diffPhaseSearchMaxTransitions, ...
        'ValidTransitionMask', sync.validTransitionMask);
    variantPhaseOffsets(k) = decision.phaseOffsetRad;
    training = tetra.findTrainingSequences(decision.bits, seqs, cfg);
    variantReports(end+1, 1) = struct( ... %#ok<AGROW>
        'variant', variants{k}, ...
        'score', training.score, ...
        'goodCount', training.goodCount, ...
        'candidateCount', training.candidateCount);
    score = training.score + 1000 * training.goodCount + ...
        100 * training.candidateCount;
    if score > bestScore
        bestScore = score;
        bestDecision = decision;
        bestTraining = training;
    end
end
if isempty(bestDecision)
    bestDecision = tetra.pi4dqpskDecision(sync.symbols, ...
        'Variant', 'standard', ...
        'PhaseOffsetStepRad', cfg.diffPhaseOffsetStepRad, ...
        'PhaseOffsetMaxTransitions', ...
            cfg.diffPhaseSearchMaxTransitions, ...
        'ValidTransitionMask', sync.validTransitionMask);
    bestTraining = tetra.findTrainingSequences( ...
        bestDecision.bits, seqs, cfg);
end
end
