function result = classifyDmoBurst(slotBits, defs, cfg)
%CLASSIFYDMOBURST Classify one 510-bit DMO slot using fixed burst fields.
if nargin < 2 || isempty(defs)
    defs = tetra.dmoBurstDefinitions();
end
if nargin < 3 || isempty(cfg)
    cfg = tetra.config();
end

slotBits = slotBits(:) ~= 0;
if numel(slotBits) ~= cfg.slotBits
    error('tetra:classifyDmoBurst:BadLength', ...
        'DMO burst classification expects %d slot bits.', cfg.slotBits);
end

candidates = repmat(emptyResult(), 0, 1);
for k = 1:numel(defs)
    def = defs(k);
    preambleErrors = countErrors(slotBits(def.preambleStartBit:def.preambleEndBit), def.preambleBits);
    trainingErrors = countErrors(slotBits(def.trainingStartBit:def.trainingEndBit), def.trainingBits);
    tailErrors = countErrors(slotBits(def.tailStartBit:def.tailEndBit), def.tailBits);

    frequencyErrors = 0;
    frequencyLength = 0;
    if def.frequencyStartBit > 0
        frequencyErrors = countErrors( ...
            slotBits(def.frequencyStartBit:def.frequencyEndBit), def.frequencyBits);
        frequencyLength = numel(def.frequencyBits);
    end

    preambleLength = numel(def.preambleBits);
    trainingLength = numel(def.trainingBits);
    tailLength = numel(def.tailBits);
    totalErrors = preambleErrors + trainingErrors + tailErrors + frequencyErrors;
    totalChecked = preambleLength + trainingLength + tailLength + frequencyLength;

    trainingOk = trainingErrors <= maxErrors(trainingLength, ...
        getCfg(cfg, 'dmoTrainingMaxErrorFraction', cfg.trainingGoodErrorFraction));
    preambleOk = preambleErrors <= getCfg(cfg, 'dmoPreambleMaxErrors', 2);
    tailOk = tailErrors <= getCfg(cfg, 'dmoTailMaxErrors', 1);
    if frequencyLength > 0
        frequencyOk = frequencyErrors <= maxErrors(frequencyLength, ...
            getCfg(cfg, 'dmoFrequencyMaxErrorFraction', 0.10));
    else
        frequencyOk = true;
    end
    totalOk = totalErrors <= maxErrors(totalChecked, ...
        getCfg(cfg, 'dmoTotalMaxErrorFraction', 0.18));
    isConfirmed = trainingOk && preambleOk && tailOk && frequencyOk && totalOk;

    candidates(end+1, 1) = struct( ... %#ok<AGROW>
        'burstName', def.name, ...
        'burstType', def.burstType, ...
        'trainingName', def.trainingName, ...
        'preambleName', def.preambleName, ...
        'description', def.description, ...
        'isConfirmed', isConfirmed, ...
        'confidence', max(0, 1 - totalErrors / max(totalChecked, 1)), ...
        'totalErrors', totalErrors, ...
        'totalCheckedBits', totalChecked, ...
        'errorFraction', totalErrors / max(totalChecked, 1), ...
        'preambleErrors', preambleErrors, ...
        'preambleLength', preambleLength, ...
        'trainingErrors', trainingErrors, ...
        'trainingLength', trainingLength, ...
        'trainingErrorFraction', trainingErrors / max(trainingLength, 1), ...
        'frequencyErrors', frequencyErrors, ...
        'frequencyLength', frequencyLength, ...
        'frequencyErrorFraction', ratioOrNaN(frequencyErrors, frequencyLength), ...
        'tailErrors', tailErrors, ...
        'tailLength', tailLength, ...
        'bkn1StartBit', def.bkn1StartBit, ...
        'bkn1EndBit', def.bkn1EndBit, ...
        'bkn1Name', def.bkn1Name, ...
        'bkn1LogicalChannel', def.bkn1LogicalChannel, ...
        'bkn2StartBit', def.bkn2StartBit, ...
        'bkn2EndBit', def.bkn2EndBit, ...
        'bkn2Name', def.bkn2Name, ...
        'bkn2LogicalChannel', def.bkn2LogicalChannel);
end

if isempty(candidates)
    result = emptyResult();
    return;
end
result = bestCandidate(candidates);
end

function c = emptyResult()
c = struct( ...
    'burstName', '', ...
    'burstType', 'unknown', ...
    'trainingName', '', ...
    'preambleName', '', ...
    'description', '', ...
    'isConfirmed', false, ...
    'confidence', 0, ...
    'totalErrors', 0, ...
    'totalCheckedBits', 0, ...
    'errorFraction', 1, ...
    'preambleErrors', 0, ...
    'preambleLength', 0, ...
    'trainingErrors', 0, ...
    'trainingLength', 0, ...
    'trainingErrorFraction', 1, ...
    'frequencyErrors', 0, ...
    'frequencyLength', 0, ...
    'frequencyErrorFraction', NaN, ...
    'tailErrors', 0, ...
    'tailLength', 0, ...
    'bkn1StartBit', 0, ...
    'bkn1EndBit', 0, ...
    'bkn1Name', '', ...
    'bkn1LogicalChannel', '', ...
    'bkn2StartBit', 0, ...
    'bkn2EndBit', 0, ...
    'bkn2Name', '', ...
    'bkn2LogicalChannel', '');
end

function best = bestCandidate(candidates)
rank = zeros(numel(candidates), 4);
for k = 1:numel(candidates)
    rank(k, :) = [ ...
        -double(candidates(k).isConfirmed), ...
        candidates(k).errorFraction, ...
        candidates(k).totalErrors, ...
        k];
end
[~, order] = sortrows(rank);
best = candidates(order(1));
end

function errors = countErrors(a, b)
errors = nnz((a(:) ~= 0) ~= (b(:) ~= 0));
end

function n = maxErrors(lengthBits, fraction)
n = floor(lengthBits * fraction + 1e-9);
end

function r = ratioOrNaN(errors, lengthBits)
if lengthBits > 0
    r = errors / lengthBits;
else
    r = NaN;
end
end

function value = getCfg(cfg, name, defaultValue)
if isfield(cfg, name)
    value = cfg.(name);
else
    value = defaultValue;
end
end
