function defs = dmoBurstDefinitions(seqs, cfg)
%DMOBURSTDEFINITIONS DMO DNB/DSB bit layouts from EN 300 396-2.
if nargin < 1 || isempty(seqs)
    seqs = tetra.trainingSequences();
end
if nargin < 2 || isempty(cfg)
    cfg = tetra.config();
end

slotBits = cfg.slotBits;
bodyStart = 35;
tailStart = 503;
tailBits = [0 0] ~= 0;

p1 = [0 0 1 1 0 0 1 0 0 0 1 1] ~= 0;
p2 = [1 0 0 1 1 0 1 0 1 0 0 1] ~= 0;
p3 = [0 0 0 1 0 1 0 0 0 1 1 1] ~= 0;
freq = [ones(1, 8), zeros(1, 64), ones(1, 8)] ~= 0;

defs = repmat(emptyDef(), 0, 1);
defs(end+1, 1) = makeDef( ...
    'DSB_sync', 'DSB', 'sync', 'P3', p3, ...
    249, seqBits(seqs, 'sync'), 49, freq, ...
    129, 248, 'BKN1', 'SCH/S', ...
    287, 502, 'BKN2', 'SCH/H', ...
    'DMO synchronization burst');
defs(end+1, 1) = makeDef( ...
    'DNB_normal_1', 'DNB', 'normal_1', 'P1', p1, ...
    265, seqBits(seqs, 'normal_1'), 0, [], ...
    49, 264, 'BKN1', 'TCH or SCH/F', ...
    287, 502, 'BKN2', 'TCH or SCH/F', ...
    'DMO normal burst, training sequence 1');
defs(end+1, 1) = makeDef( ...
    'DNB_normal_2', 'DNB', 'normal_2', 'P2', p2, ...
    265, seqBits(seqs, 'normal_2'), 0, [], ...
    49, 264, 'BKN1', 'STCH', ...
    287, 502, 'BKN2', 'TCH or STCH', ...
    'DMO normal burst, training sequence 2');

for k = 1:numel(defs)
    defs(k).slotBits = slotBits;
    defs(k).bodyStartBit = bodyStart;
    defs(k).preambleStartBit = bodyStart;
    defs(k).preambleEndBit = bodyStart + numel(defs(k).preambleBits) - 1;
    defs(k).phaseStartBit = 47;
    defs(k).phaseEndBit = 48;
    defs(k).trainingEndBit = defs(k).trainingStartBit + numel(defs(k).trainingBits) - 1;
    defs(k).tailStartBit = tailStart;
    defs(k).tailEndBit = tailStart + numel(tailBits) - 1;
    defs(k).tailBits = tailBits(:);
    defs(k).guardBeforeStartBit = 1;
    defs(k).guardBeforeEndBit = 34;
    defs(k).guardAfterStartBit = 505;
    defs(k).guardAfterEndBit = slotBits;
end
end

function def = emptyDef()
def = struct( ...
    'name', '', ...
    'burstType', '', ...
    'trainingName', '', ...
    'preambleName', '', ...
    'description', '', ...
    'slotBits', 0, ...
    'bodyStartBit', 0, ...
    'guardBeforeStartBit', 0, ...
    'guardBeforeEndBit', 0, ...
    'guardAfterStartBit', 0, ...
    'guardAfterEndBit', 0, ...
    'preambleStartBit', 0, ...
    'preambleEndBit', 0, ...
    'preambleBits', false(0, 1), ...
    'phaseStartBit', 0, ...
    'phaseEndBit', 0, ...
    'frequencyStartBit', 0, ...
    'frequencyEndBit', 0, ...
    'frequencyBits', false(0, 1), ...
    'trainingStartBit', 0, ...
    'trainingEndBit', 0, ...
    'trainingBits', false(0, 1), ...
    'bkn1StartBit', 0, ...
    'bkn1EndBit', 0, ...
    'bkn1Name', '', ...
    'bkn1LogicalChannel', '', ...
    'bkn2StartBit', 0, ...
    'bkn2EndBit', 0, ...
    'bkn2Name', '', ...
    'bkn2LogicalChannel', '', ...
    'tailStartBit', 0, ...
    'tailEndBit', 0, ...
    'tailBits', false(0, 1));
end

function def = makeDef(name, burstType, trainingName, preambleName, preambleBits, ...
        trainingStartBit, trainingBits, frequencyStartBit, frequencyBits, ...
        bkn1StartBit, bkn1EndBit, bkn1Name, bkn1LogicalChannel, ...
        bkn2StartBit, bkn2EndBit, bkn2Name, bkn2LogicalChannel, description)
def = emptyDef();
def.name = name;
def.burstType = burstType;
def.trainingName = trainingName;
def.preambleName = preambleName;
def.description = description;
def.preambleBits = preambleBits(:);
def.trainingStartBit = trainingStartBit;
def.trainingBits = trainingBits(:);
def.frequencyStartBit = frequencyStartBit;
if frequencyStartBit > 0
    def.frequencyEndBit = frequencyStartBit + numel(frequencyBits) - 1;
    def.frequencyBits = frequencyBits(:);
end
def.bkn1StartBit = bkn1StartBit;
def.bkn1EndBit = bkn1EndBit;
def.bkn1Name = bkn1Name;
def.bkn1LogicalChannel = bkn1LogicalChannel;
def.bkn2StartBit = bkn2StartBit;
def.bkn2EndBit = bkn2EndBit;
def.bkn2Name = bkn2Name;
def.bkn2LogicalChannel = bkn2LogicalChannel;
end

function bits = seqBits(seqs, name)
idx = find(strcmp({seqs.name}, name), 1);
if isempty(idx)
    error('tetra:dmoBurstDefinitions:MissingSequence', ...
        'Missing TETRA training sequence %s.', name);
end
bits = seqs(idx).bits ~= 0;
end
