function blocks = extractDmoPayload(slotBits, classification, slotStartBit, slotValidMask)
%EXTRACTDMOPAYLOAD Slice BKN1/BKN2 payload fields from a confirmed DMO slot.
if nargin < 3 || isempty(slotStartBit)
    slotStartBit = NaN;
end
if nargin < 4 || isempty(slotValidMask) || numel(slotValidMask) ~= numel(slotBits)
    slotValidMask = true(size(slotBits(:)));
else
    slotValidMask = logical(slotValidMask(:));
end

slotBits = slotBits(:) ~= 0;
blocks = repmat(emptyBlock(), 0, 1);
if isempty(classification) || ~classification.isConfirmed
    return;
end

blocks(end+1, 1) = makeBlock(slotBits, classification, slotStartBit, ...
    1, classification.bkn1Name, classification.bkn1LogicalChannel, ...
    classification.bkn1StartBit, classification.bkn1EndBit, slotValidMask);
blocks(end+1, 1) = makeBlock(slotBits, classification, slotStartBit, ...
    2, classification.bkn2Name, classification.bkn2LogicalChannel, ...
    classification.bkn2StartBit, classification.bkn2EndBit, slotValidMask);
end

function block = emptyBlock()
block = struct( ...
    'blockIndex', 0, ...
    'blockName', '', ...
    'burstType', '', ...
    'burstName', '', ...
    'trainingName', '', ...
    'logicalChannelHint', '', ...
    'slotStartBit', NaN, ...
    'startBitInSlot', 0, ...
    'endBitInSlot', 0, ...
    'absoluteStartBit', NaN, ...
    'absoluteEndBit', NaN, ...
    'length', 0, ...
    'bits', false(0, 1), ...
    'validMask', false(0, 1), ...
    'validBitCount', 0, ...
    'invalidBitCount', 0, ...
    'validRatio', NaN, ...
    'allBitsValid', false, ...
    'bitString', '');
end

function block = makeBlock(slotBits, classification, slotStartBit, blockIndex, ...
        blockName, logicalChannel, startBit, endBit, slotValidMask)
if startBit <= 0 || endBit < startBit || endBit > numel(slotBits)
    block = emptyBlock();
    return;
end
bits = slotBits(startBit:endBit);
validMask = slotValidMask(startBit:endBit);
absStart = slotStartBit + startBit - 1;
absEnd = slotStartBit + endBit - 1;
validCount = nnz(validMask);
invalidCount = numel(validMask) - validCount;
block = struct( ...
    'blockIndex', blockIndex, ...
    'blockName', blockName, ...
    'burstType', classification.burstType, ...
    'burstName', classification.burstName, ...
    'trainingName', classification.trainingName, ...
    'logicalChannelHint', logicalChannel, ...
    'slotStartBit', slotStartBit, ...
    'startBitInSlot', startBit, ...
    'endBitInSlot', endBit, ...
    'absoluteStartBit', absStart, ...
    'absoluteEndBit', absEnd, ...
    'length', numel(bits), ...
    'bits', bits, ...
    'validMask', validMask, ...
    'validBitCount', validCount, ...
    'invalidBitCount', invalidCount, ...
    'validRatio', safeRatio(validCount, numel(validMask)), ...
    'allBitsValid', all(validMask), ...
    'bitString', char('0' + double(bits(:).')));
end

function r = safeRatio(n, d)
if d <= 0
    r = NaN;
else
    r = double(n) / double(d);
end
end
