function blocks = extractDmoPayload(slotBits, classification, slotStartBit)
%EXTRACTDMOPAYLOAD Slice BKN1/BKN2 payload fields from a confirmed DMO slot.
if nargin < 3 || isempty(slotStartBit)
    slotStartBit = NaN;
end

slotBits = slotBits(:) ~= 0;
blocks = repmat(emptyBlock(), 0, 1);
if isempty(classification) || ~classification.isConfirmed
    return;
end

blocks(end+1, 1) = makeBlock(slotBits, classification, slotStartBit, ...
    1, classification.bkn1Name, classification.bkn1LogicalChannel, ...
    classification.bkn1StartBit, classification.bkn1EndBit);
blocks(end+1, 1) = makeBlock(slotBits, classification, slotStartBit, ...
    2, classification.bkn2Name, classification.bkn2LogicalChannel, ...
    classification.bkn2StartBit, classification.bkn2EndBit);
end

function block = emptyBlock()
block = struct( ...
    'blockIndex', 0, ...
    'blockName', '', ...
    'burstType', '', ...
    'burstName', '', ...
    'trainingName', '', ...
    'logicalChannelHint', '', ...
    'slotStartBit', NaN, ...
    'startBitInSlot', 0, ...
    'endBitInSlot', 0, ...
    'absoluteStartBit', NaN, ...
    'absoluteEndBit', NaN, ...
    'length', 0, ...
    'bits', false(0, 1), ...
    'bitString', '');
end

function block = makeBlock(slotBits, classification, slotStartBit, blockIndex, ...
        blockName, logicalChannel, startBit, endBit)
if startBit <= 0 || endBit < startBit || endBit > numel(slotBits)
    block = emptyBlock();
    return;
end
bits = slotBits(startBit:endBit);
absStart = slotStartBit + startBit - 1;
absEnd = slotStartBit + endBit - 1;
block = struct( ...
    'blockIndex', blockIndex, ...
    'blockName', blockName, ...
    'burstType', classification.burstType, ...
    'burstName', classification.burstName, ...
    'trainingName', classification.trainingName, ...
    'logicalChannelHint', logicalChannel, ...
    'slotStartBit', slotStartBit, ...
    'startBitInSlot', startBit, ...
    'endBitInSlot', endBit, ...
    'absoluteStartBit', absStart, ...
    'absoluteEndBit', absEnd, ...
    'length', numel(bits), ...
    'bits', bits, ...
    'bitString', char('0' + double(bits(:).')));
end
