function report = frameDecoderReport(state)
%FRAMEDECODERREPORT Summarize persistent TETRA DMO decoder state.
contextValid = false;
if isstruct(state.dmoContext) && isfield(state.dmoContext, 'valid')
    contextValid = logical(state.dmoContext.valid);
end
report = struct( ...
    'candidateCount', double(state.candidateCount), ...
    'confirmedBurstCount', double(state.confirmedBurstCount), ...
    'validControlPduCount', double(state.validControlPduCount), ...
    'decodedPduCount', double(state.decodedPduCount), ...
    'dmoContextValid', contextValid, ...
    'sessionActive', logical(state.sessionState.session.active), ...
    'finalized', logical(state.finalized));
end
