function state = frameDecoderInit(cfg)
%FRAMEDECODERINIT Initialize persistent TETRA DMO slot and MAC state.
if nargin < 1 || isempty(cfg), cfg = tetra.config(); end
state = struct( ...
    'cfg', cfg, ...
    'sequences', tetra.trainingSequences(), ...
    'dmoContext', [], ...
    'sessionState', tetra.sessionDecoderInit(), ...
    'candidateCount', uint64(0), ...
    'confirmedBurstCount', uint64(0), ...
    'validControlPduCount', uint64(0), ...
    'decodedPduCount', uint64(0), ...
    'finalized', false);
end
