function pdu = sessionDecoderPdu(session, stateName)
%SESSIONDECODERPDU Format one persistent TETRA DMO session summary.
extra = struct( ...
    'mode', 'DMO', ...
    'state', char(stateName), ...
    'start_time_s', session.startTime, ...
    'end_time_s', session.lastTime, ...
    'duration_s', session.lastTime - session.startTime, ...
    'start_bit', session.startBit, ...
    'end_bit', session.endBit, ...
    'start_frame_number', session.startFrame, ...
    'start_slot_number', session.startSlot, ...
    'end_frame_number', session.endFrame, ...
    'end_slot_number', session.endSlot, ...
    'mni', session.mni, ...
    'dcc', session.dcc, ...
    'sync_event_count', session.syncEventCount, ...
    'stch_event_count', session.stchEventCount, ...
    'control_event_count', session.controlEventCount, ...
    'tch_candidate_count', session.tchCandidateCount, ...
    'release_message', session.releaseMessage, ...
    'service', session.service);
pdu = struct( ...
    'protocol', 'TETRA', ...
    'type', 'TETRA_SESSION', ...
    'src', session.src, ...
    'dst', session.dst, ...
    'ts', [], ...
    'flco', 'DMO_SESSION', ...
    'fid', '', ...
    'extra', extra, ...
    'raw_bits', []);
pdu = radio.normalizePdus(pdu);
end
