function state = sessionDecoderInit()
%SESSIONDECODERINIT Initialize persistent TETRA DMO session state.
session = struct( ...
    'active', false, ...
    'src', 0, ...
    'dst', 0, ...
    'mni', NaN, ...
    'dcc', '', ...
    'startTime', NaN, ...
    'lastTime', NaN, ...
    'startBit', NaN, ...
    'endBit', NaN, ...
    'startFrame', NaN, ...
    'startSlot', NaN, ...
    'endFrame', NaN, ...
    'endSlot', NaN, ...
    'syncEventCount', 0, ...
    'stchEventCount', 0, ...
    'controlEventCount', 0, ...
    'tchCandidateCount', 0, ...
    'releaseMessage', '', ...
    'service', '');
state = struct('session', session, 'finalized', false);
end
