function spec = spec()
%SPEC TETRA ProtocolSpec-compatible adapter.
cfg = tetra.config();
spec = struct( ...
    'name', 'TETRA', ...
    'aliases', {{'tetra'}}, ...
    'config', cfg, ...
    'frontendKey', 'tetra_iq', ...
    'frontendFcn', @tetra.frontend, ...
    'decodeFcn', @tetra.decode, ...
    'postprocessFcn', @tetra.postprocess, ...
    'dedupFcn', @tetra.dedupKey, ...
    'formatterFcn', @tetra.formatPdu, ...
    'scanMode', 'windowed_iq', ...
    'targetSampleRateHz', cfg.frontendSampleRateHz, ...
    'scanIqFcn', @tetra.scanIqWindows, ...
    'supportsBlindSearch', false, ...
    'supportsFrequencyOffsets', true, ...
    'defaultBasebandScan', false, ...
    'defaultFreqListScan', true, ...
    'defaultBlindSearch', false);
end
