function spec = spec()
%SPEC TETRA ProtocolSpec-compatible adapter.
spec = struct( ...
    'name', 'TETRA', ...
    'aliases', {{'tetra'}}, ...
    'config', tetra.config(), ...
    'frontendKey', 'tetra_iq', ...
    'frontendFcn', @tetra.frontend, ...
    'decodeFcn', @tetra.decode, ...
    'postprocessFcn', @tetra.postprocess, ...
    'dedupFcn', @tetra.dedupKey, ...
    'formatterFcn', @tetra.formatPdu);
end
