function spec = spec()
%SPEC TETRA ProtocolSpec-compatible adapter.
cfg = tetra.config();
spec = struct( ...
    'name', 'TETRA', ...
    'aliases', {{'tetra'}}, ...
    'config', cfg, ...
    'frontendFcn', @tetra.frontend, ...
    'decodeFcn', @tetra.decode, ...
    'postprocessFcn', @tetra.postprocess, ...
    'dedupFcn', @tetra.dedupKey, ...
    'formatterFcn', @tetra.formatPdu, ...
    'targetSampleRateHz', cfg.frontendSampleRateHz, ...
    'scanIqFcn', @tetra.scanIqWindows);
end
