function state = streamInit(inputSampleRateHz, cfg, varargin)
%STREAMINIT Initialize a causal, persistent TETRA DMO IQ decoder.
if nargin < 2 || isempty(cfg), cfg = tetra.config(); end
p = inputParser;
p.addParameter('SourceSampleStart', []);
p.parse(varargin{:});
validateattributes(inputSampleRateHz, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
inputRate = double(inputSampleRateHz);
targetRate = double(cfg.frontendSampleRateHz);
[up, down] = rationalRate(inputRate, targetRate);
converter = [];
converterDelaySec = 0;
rateMode = 'none';
if up ~= down
    if exist('dsp.FIRRateConverter', 'class') ~= 8
        error('tetra:streamInit:MissingRateConverter', ...
            'dsp.FIRRateConverter is required for streaming resampling.');
    end
    converter = dsp.FIRRateConverter(up, down, ...
        'AllowArbitraryInputLength', true);
    [converterDelaySec, ~] = outputDelay(converter, FsIn=inputRate);
    rateMode = 'system_object';
end
h = tetra.rrcTaps( ...
    cfg.rrcAlpha, cfg.samplesPerSymbol, cfg.rrcSpanSymbols);
pipelineDelaySamples = converterDelaySec * targetRate + ...
    (numel(h) - 1) / 2;
sourceStart = p.Results.SourceSampleStart;
if ~isempty(sourceStart), sourceStart = uint64(sourceStart); end
state = struct( ...
    'cfg', cfg, ...
    'inputSampleRateHz', inputRate, ...
    'targetSampleRateHz', targetRate, ...
    'rateUp', double(up), ...
    'rateDown', double(down), ...
    'rateMode', rateMode, ...
    'rateConverter', converter, ...
    'rateConverterDelaySec', double(converterDelaySec), ...
    'calibrationMinSamples', max(256, ...
        round(cfg.streamCalibrationSec * targetRate)), ...
    'calibrationBuffer', complex(zeros(0, 1)), ...
    'calibrated', false, ...
    'coarseFrequencyOffsetHz', NaN, ...
    'residualCorrectionHz', NaN, ...
    'totalFrequencyOffsetHz', NaN, ...
    'usedResidualCorrection', false, ...
    'timingPhaseSamples', NaN, ...
    'timingErrorRad', NaN, ...
    'decisionVariant', '', ...
    'decisionPhaseOffsetRad', NaN, ...
    'variantReports', struct([]), ...
    'amplitudeThreshold', 0, ...
    'mixedSamplesProcessed', uint64(0), ...
    'matchedNumerator', h(:).', ...
    'matchedZi', complex(zeros(numel(h) - 1, 1)), ...
    'matchedBuffer', complex(zeros(0, 1)), ...
    'matchedBufferStart', uint64(0), ...
    'nextSymbolPosition', NaN, ...
    'previousSymbol', complex(zeros(0, 1)), ...
    'bitBuffer', false(0, 1), ...
    'bitValidBuffer', false(0, 1), ...
    'bitBufferStart', uint64(1), ...
    'bitsProduced', uint64(0), ...
    'nextSlotStartBit', uint64(1), ...
    'pipelineDelaySamples', double(pipelineDelaySamples), ...
    'sourceOriginSample', sourceStart, ...
    'expectedSourceSample', sourceStart, ...
    'inputSamplesReceived', uint64(0), ...
    'resampledSamplesProduced', uint64(0), ...
    'symbolsProduced', uint64(0), ...
    'feedCount', uint64(0), ...
    'maxMatchedBufferSamples', uint64(0), ...
    'maxBitBufferBits', uint64(0), ...
    'frameState', tetra.frameDecoderInit(cfg), ...
    'finalized', false);
end

function [up, down] = rationalRate(inputRate, targetRate)
roundedInput = round(inputRate);
roundedTarget = round(targetRate);
if abs(inputRate - roundedInput) > 1e-6 || ...
        abs(targetRate - roundedTarget) > 1e-6
    error('tetra:streamInit:NonIntegerRate', ...
        'Streaming TETRA currently requires integer sample rates.');
end
divisor = gcd(roundedInput, roundedTarget);
up = roundedTarget / divisor;
down = roundedInput / divisor;
end
