function [state, output] = streamFlush(state)
%STREAMFLUSH Drain causal TETRA frontend latency and finalize DMO session.
if state.finalized
    output = emptyOutput(state);
    return;
end
if isempty(state.sourceOriginSample)
    state.finalized = true;
    output = emptyOutput(state);
    return;
end
calibrationRemaining = max(0, state.calibrationMinSamples - ...
    numel(state.calibrationBuffer));
calibrationInput = ceil(calibrationRemaining * ...
    state.inputSampleRateHz / state.targetSampleRateHz);
paddingCount = max(1, calibrationInput + ceil( ...
    (state.cfg.streamFlushPaddingSec + state.rateConverterDelaySec) * ...
    state.inputSampleRateHz));
padding = radio.stream.makeIqChunk( ...
    complex(zeros(paddingCount, 1)), state.inputSampleRateHz, ...
    state.expectedSourceSample, 'SequenceNumber', state.feedCount);
[state, drained] = tetra.streamDecodeChunk(state, padding);
[state.frameState, finalPdus] = ...
    tetra.frameDecoderFinalize(state.frameState);
finalSamples = pduSourceSamples(state, finalPdus);
pdus = appendPdus(drained.pdus, finalPdus);
sourceSamples = [drained.sourceSamples; finalSamples];
state.finalized = true;
output = struct( ...
    'pdus', radio.normalizePdus(pdus), ...
    'sourceSamples', sourceSamples, ...
    'diagnostics', tetra.frameDecoderReport(state.frameState), ...
    'frequencyOffsetHz', drained.frequencyOffsetHz, ...
    'timingState', drained.timingState, ...
    'nativeStreaming', true, ...
    'inputSampleCount', paddingCount, ...
    'resampledSampleCount', drained.resampledSampleCount, ...
    'symbolCount', drained.symbolCount, ...
    'bitCount', drained.bitCount, ...
    'elapsedSec', drained.elapsedSec);
end

function output = emptyOutput(state)
output = struct('pdus', struct([]), ...
    'sourceSamples', zeros(0, 1, 'uint64'), ...
    'diagnostics', tetra.frameDecoderReport(state.frameState), ...
    'frequencyOffsetHz', state.totalFrequencyOffsetHz, ...
    'timingState', struct(), 'nativeStreaming', true, ...
    'inputSampleCount', 0, 'resampledSampleCount', 0, ...
    'symbolCount', 0, 'bitCount', 0, 'elapsedSec', 0);
end

function samples = pduSourceSamples(state, pdus)
samples = zeros(numel(pdus), 1, 'uint64');
for k = 1:numel(pdus)
    bitIndex = radio.getNestedField( ...
        pdus(k), 'extra.slot_start_bit', []);
    if isempty(bitIndex)
        bitIndex = radio.getNestedField(pdus(k), 'extra.start_bit', 1);
    end
    targetOffset = (max(1, double(bitIndex)) - 1) * ...
        state.targetSampleRateHz / (2 * state.cfg.symbolRateHz) - ...
        state.pipelineDelaySamples;
    inputOffset = round(max(0, targetOffset) * ...
        state.inputSampleRateHz / state.targetSampleRateHz);
    samples(k) = state.sourceOriginSample + uint64(max(0, inputOffset));
end
end

function values = appendPdus(values, items)
if isempty(items), return; end
if isempty(values), values = items; else, values(end+1:end+numel(items)) = items; end
end
